- ACE/ace/Intrusive_Auto_Ptr.inl
- ACE/tests/Intrusive_Auto_Ptr_Test.cpp
> Fix memory leak by incorrect assignment of Intrusive_Auto_Ptr.

- ACE/ace/Process.cpp
- TAO/TAO_IDL/driver/drv_args.cpp
- TAO/TAO_IDL/driver/drv_preproc.cpp
- TAO/TAO_IDL/tao_idl.cpp
Allow redirection of child's stdout/stderr when there is no
stdin handle available (for example when running in a service).
TAO_IDL drv_preproc: check for errors from ACE_Process
> ACE_Process std file handles on Windows

- ACE/ace/config-win32-msvc-14.h
* ACE/ace/config-win32-msvc-14.h:
> Visual Studio 2015 has 3 parameter wcstok

- ACE/ace/OS_NS_Thread.cpp
- ACE/ace/OS_NS_Thread.h
- ACE/ace/OS_NS_signal.inl
- ACE/ace/OS_NS_stdlib.cpp
- ACE/ace/Stack_Trace.cpp
- ACE/ace/config-vxworks.h
This is a set of changes I am assisting a customer with. I do not have a build environment to test with, but the customer does and they've approved the changes for VxWorks.
> Net app vx works64

- ACE/include/makeinclude/rules.lib.GNU
Build ACE in AIX 5.1 error:
* Use ace/config-aix-5.x.h as config.h
* Use platform_aix_g++.GNU as platform_aix_g++.GNU
```
ACE/include/makeinclude/rules.lib.GNU:201: *** missing separator (did you mean TAB instead of 8 spaces?). Stop.
```
> Fix missing separator in rules.lib.GNU

- ACE/ace/Dev_Poll_Reactor.cpp
- ACE/tests/.gitignore
- ACE/tests/Dev_Poll_Reactor_Echo_Test.cpp
- ACE/tests/run_test.lst
- ACE/tests/tests.mpc
Dev_Poll_Reactor on Linux uses epoll with one-shot and
suspends handlers when an event is received.  New logic attempts
to resume handler when -1 is returned.  Added test.
From OCITAO 2.2a Fri Nov 14 16:47:56 UTC 2014
> Fix to resume and register event handlers after returning -1 from handle_*

- ACE/ace/ACE.cpp
When building in AIX 5.1, GCC reported
```
ACE.cpp: In function 'ssize_t ACE::t_snd_n_i(ACE_HANDLE, const void*, size_t, int, const ACE_Time_Value*, size_t*)':
ACE.cpp:1532:39: warning: suggest parentheses around '&&' within '||'
```
After reading ACE.cpp, I find it is not only a warning but also a bug.
> Fix errno checking logic in TLI

- ACE/ace/OS_NS_sys_stat.inl
In ACE_OS::stat WinCE case, It forgets to close the handle that open by FindFirstFile.
> Fix forgetting to close handle in ACE_OS::stat.

- TAO/MPC/config/taobaseidldefaults.mpb
Header output extension should be optional otherwise the make files always has an header included. This goes wrong when only an IDL file is created by the R/TAO IDL compiler.
> Header output extension should be optional

- ACE/ace/CDR_Base.cpp
- ACE/tests/CDR_Fixed_Test.cpp
- an index out-of-range problem
- a bug in emulated LongDouble conversion of 0 values
> ACE_CDR::Fixed corrected bugs in floating point conversions:

- ACE/ace/Time_Value.h
> Added truncate_cast because suseconds_t is 32bit on Windows x86

- ACE/ace/SSL/SSL_Context.cpp
version information : 
msvc community 2013 / ace (github DocGroup/ATCD master) / openssl 1.0.2a / zlib 1.2.8
> fix compile error for ssl (MAXHOSTNAMELEN missing)

- TAO/tao/CSD_ThreadPool/CSD_TP_Task.cpp
- TAO/tao/Dynamic_TP/DTP_Thread_Pool.cpp
relax limits on fixed POA pool size.
Ensure the dynamic thread activation succeeded before entering wait
> Thread pool bugfixes

- TAO/TAO_IDL/be/be_visitor_union/cdr_op_cs.cpp
- TAO/TAO_IDL/be/be_visitor_union/union.cpp
- TAO/TAO_IDL/be/be_visitor_union/union_cs.cpp
- TAO/TAO_IDL/be/be_visitor_union_branch/public_assign_cs.cpp
- TAO/TAO_IDL/be/be_visitor_union_branch/public_reset_cs.cpp
- TAO/TAO_IDL/be_include/be_visitor_union/cdr_op_cs.h
- TAO/TAO_IDL/be_include/be_visitor_union/union.h
- TAO/tests/IDL_Test/interface.idl
- TAO/tests/IDL_Test/union.idl
Eliminates warnings in generated code with newer clang and gcc.
> TAO_IDL: generate "if" instead of "switch" for bool-discriminated unions.

- TAO/TAO_IDL/util/utl_scope.cpp
- TAO/tests/IDL_Test/keyword_case_diff.idl
- TAO/tests/IDL_Test/run_test.pl
tao_idl is not able to compile IDL files which have an identifier
that differs only in case from an IDL keyword, even if the '-Cw'
flag is used. For example:
```
$ cat > MyModule.idl << EOF
module MyModule {
interface PortType {
exception MyException {
string myString;
};
void myMethod ()
raises (MyModule::PortType::MyException);
};
};
EOF
$ tao_idl -Cw MyModule.idl
Error - tao_idl: "MyModule.idl", line 2: Warning - spelling differs from IDL keyword only in case: "PortType"
Error - tao_idl: "MyModule.idl", line 2: Warning - spelling differs from IDL keyword only in case: "PortType"
Error - tao_idl: "MyModule.idl", line 8: Warning - spelling differs from IDL keyword only in case: "PortType"
Error - tao_idl: "MyModule.idl", line 8: error in lookup of symbol: MyModule::PortType::MyException …
```
> Honor '-Cw' flag passed to tao_idl

- TAO/NEWS
- TAO/bin/tao_other_tests.lst
- TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Invocation_Interceptor.cpp
- TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Invocation_Interceptor.h
- TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_ORBInitializer.cpp
- TAO/orbsvcs/orbsvcs/Security/SL2_SecurityManager.cpp
- TAO/orbsvcs/orbsvcs/Security/SL2_SecurityManager.h
- TAO/orbsvcs/orbsvcs/Security/SL3_SecurityManager.h
- TAO/orbsvcs/orbsvcs/SecurityLevel2.idl
- TAO/orbsvcs/tests/Security/Bug_2908_Regression/Messenger.idl
- TAO/orbsvcs/tests/Security/Bug_2908_Regression/MessengerClient.cpp
- TAO/orbsvcs/tests/Security/Bug_2908_Regression/MessengerServer.cpp
- TAO/orbsvcs/tests/Security/Bug_2908_Regression/Messenger_i.cpp
- TAO/orbsvcs/tests/Security/Bug_2908_Regression/Messenger_i.h
- TAO/tao/PI_Server/ServerRequestInfo.h
Extend SL2 Security Manager with the ability to allow non-secure collocated request with one flag and still disable non-secure remote requests. Because within an interceptor we don't know whether we are invoked collocated or not we register two interceptors, one for the collocated and one for the remote case.
> Extend SL2 Security Manager

- ACE/ace/config-macosx-elcapitan.h
- ACE/include/makeinclude/platform_macosx_elcapitan.GNU
This simply points to the Yosemite configs, which seems to work fine.
> Add ACE support for MacOS X 10.11 El Capitan

- ACE/ace/SSL/SSL_Context.cpp
- ACE/ace/SSL/SSL_Context.h
- ACE/ace/SSL/SSL_Initializer.cpp
Because ACE_SSL_Context is a unmanaged singleton, it would not
destruct without calling static close method explicitly.
ACE_SSL_Initializer can load and unload ACE_SSL_Context, but ACE_SSL_Context could not be closed without it.
> Add static ACE_SSL_Context::close for deleting it.

- TAO/tao/GIOP_Message_Base.cpp
- TAO/tests/ZIOP/Hello.cpp
- TAO/tests/ZIOP/Hello.h
- TAO/tests/ZIOP/Test.idl
- TAO/tests/ZIOP/client.cpp
- TAO/tests/ZIOP/server.cpp
in the stack allocated buffer. Modify the test to accept a size value for testing the message size fix.
> Fix for the case when the compressed data is too large to fit

- ACE/bin/make_release.py
A user notified me of this issue privately. Simple fix needed for *nix users that download .zip version of release.
> add .sh files to "don't convert endings" pattern for zip distro.

- ACE/ace/SSL/SSL_Context.cpp
- ACE/ace/SSL/SSL_Context.h
- ACE/examples/C++NPv2/AC_Client_Logging_Daemon.cpp
- ACE/examples/C++NPv2/AIO_Client_Logging_Daemon.cpp
- ACE/examples/C++NPv2/TPC_Logging_Server.cpp
- ACE/protocols/ace/INet/HTTPS_Context.cpp
- ACE/protocols/examples/INet/HTTP_Simple_exec.cpp
The SSLv23_* methods are the only one that support multiple versions.
This is https://bugs.debian.org/804326
> Remove version specific OpenSSL methods

- TAO/NEWS
- TAO/bin/imr_tests.lst
- TAO/bin/tao_other_tests.lst
- TAO/orbsvcs/ImplRepo_Service/AsyncAccessManager.cpp
- TAO/orbsvcs/ImplRepo_Service/AsyncAccessManager.h
- TAO/orbsvcs/ImplRepo_Service/ImR_Locator_i.cpp
- TAO/orbsvcs/ImplRepo_Service/ImR_Locator_i.h
- TAO/orbsvcs/ImplRepo_Service/tao_imr_i.cpp
- TAO/orbsvcs/ImplRepo_Service/tao_imr_i.h
- TAO/orbsvcs/tests/ImplRepo/kill_server/run_test.pl
- TAO/tao/ImR_Client/ImplRepo.idl
This combines the steps of disabling restarts, shutting down or killing, then removing the registry entry into a single tao_imr invocation.
> New ImR feature to force a remove of a running server.

- ACE/ace/OS_NS_stdio.cpp
- ACE/ace/config-sunos5.10.h
- ACE/ace/config-sunos5.9.h
Fixes Solaris 9 (INET_Addr related) and MinGW-W64 64-bit (snprintf floating pt).
> Even more compatibility fixes after pull request #159 (merged FACE safety).

- ACE/NEWS
@jwillemsen, please pull the fix for the news item according to our conversation on acb5b1f1f00653bcdf840afa6dc042a0b880a454.
Please keep in mind that `ACE_SSL_Context::filter_versions()` has issues that
should be addressed (I don't intend to spend time on ACE, sorry):
* documentation of `filter_versions()` says nothing - you either have to try or to read the ACE source code
* the interface of `filter_versions()` - passing a string with comma-delimited constants - is fragile
* `filter_versions()` requires constant maintenance - each time a new protocol is added
* `filter_versions()` is not (necessarily) forward-compatible because it disables any but the given protocols (also see kroeckx's comment on #156 about a new OpenSSL API for that)
> reword the news item about OpenSSL compatibility

- TAO/MPC/config/ft_naming_serv.mpb
- TAO/MPC/config/ftnaming.mpb
- TAO/MPC/config/ftnaming_replication.mpb
- TAO/orbsvcs/ImplRepo_Service/ImplRepo_Service.mpc
By listing all required libraries in mpb files, when executables are built all
used libraries (even indirectly used) will appear on the linker command line.
This is required for static libs and probably a good idea for shared libs.
> Updated mpc/mpb files to accurately reflect library dependencies.

- ACE/ace/Service_Repository.h
- ACE/ace/Service_Repository.inl
* ACE/ace/Service_Repository.h:
* ACE/ace/Service_Repository.inl:
> Make the lock accessor const to prevent a const cast in user code

- TAO/orbsvcs/orbsvcs/Naming/Storable_Naming_Context.cpp
- TAO/orbsvcs/orbsvcs/Naming/Storable_Naming_Context_ReaderWriter.cpp
- TAO/orbsvcs/orbsvcs/PortableGroup/PG_Group_List_Store.cpp
- TAO/tao/Storable_File_Guard.cpp
- TAO/tao/Storable_FlatFileStream.cpp
These failures are actually quite old (circa 2013) but were masked. OCI TAO addressed the problem by first fixing the errant PG_Group_List_Store file lock, and then simply ignoring the "Error" of not creating a backup for empty persistence files. However this causes the FT_Naming/Failover/Persistence test to fail, so this commit now fixes that behavior, so a backup file is once again created as soon as the primary persistence file is created.
> Fix for new persistence failures that appeared after earlier commits.

- ACE/ace/INET_Addr.cpp
Resolves BZ4211 which has been plaguing Riverace and OCI for quite some time.
> Remove AI_ADDRCONFIG use from ACE_INET_Addr::set; see Bugzilla 4211

- ACE/tests/Compiler_Features_36_Test.cpp
- ACE/tests/run_test.lst
- ACE/tests/tests.mpc
* ACE/tests/Compiler_Features_36_Test.cpp:
Added.
* ACE/tests/run_test.lst:
* ACE/tests/tests.mpc:
> Added C++11 test for using incomplete types and std::is_base_of

- .gitignore
- TAO/orbsvcs/ImplRepo_Service/AsyncAccessManager.cpp
- TAO/orbsvcs/ImplRepo_Service/ImR_Activator_i.cpp
- TAO/orbsvcs/ImplRepo_Service/ImR_Activator_i.h
- TAO/orbsvcs/ImplRepo_Service/ImR_Locator_i.cpp
- TAO/orbsvcs/ImplRepo_Service/ImplRepo_Service.mpc
- TAO/orbsvcs/ImplRepo_Service/LiveCheck.cpp
- TAO/orbsvcs/ImplRepo_Service/LiveCheck.h
- TAO/orbsvcs/ImplRepo_Service/Server_Info.cpp
- TAO/orbsvcs/ImplRepo_Service/tao_imr_i.cpp
- TAO/orbsvcs/tests/ImplRepo/Bug_4152_Regression/Test_i.cpp
- TAO/orbsvcs/tests/ImplRepo/Bug_4152_Regression/run_test.pl
- TAO/utils/logWalker/Invocation.cpp
- TAO/utils/logWalker/Log.cpp
This time the behavior of the Activator is modified to accommodate the peculiar behavior of the client trying to open a new connection to a recently closed acceptor. This is all fine because it is modifying test-specific behavior that is only relevant on non-windows systems anyway.
> Another attempt to silence the Bug 4152 failures on windows

- ACE/ace/config-suncc-common.h
- ACE/ace/config-sunos5.10.h
Solaris Studio 12.4 now implements symbol lookup correctly.
Added #define ACE_ANY_OPS_USE_NAMESPACE to
config-sunos5.10.h when 12.4 or later compiler is detected.
> Fix compile for Solaris Studio 12.4

- TAO/tests/ORB_init/Portspan/run_test.pl
The test didn't fail when the startup of server3 was successful, because SpawnWaitKill not only returns -1 when the server couldn't start, but also when the server's still running after the wait.
> Test on successful startup of the 3rd server did not fail while it should

- ACE/include/makeinclude/macros.GNU
- ACE/include/makeinclude/rules.local.GNU
- ACE/include/makeinclude/rules.nested.GNU
2 items motivating these changes:
1. The desire to add more targets to the nested make structure; now defining a make variable PRIVATE_TARGETS_LOCAL will cause those targets to be appended to the current set of nested targets.
2. Change the default MAKEFILE variable name from GNUmakefile to the name of the makefile referenced first in the make invocation. Makes it easier to manage nested makes without always remembering to set the MAKEFILE variable. If the MAKEFILE variable is set, it is not changed.
> Make nested makes easier to manage

- ACE/ace/POSIX_Proactor.cpp
[Changed]
POSIX_Proactor.cpp
- disable an OS bounds check for Android since it does not support AIO
and ACE_HAS_AIO_CALLS will only be defined if a 3rd party lib is used
[Tests]
Test 1:
1) Compile ACE for Android using a 3rd party AIO lib
2) In the implementation of ACE_Service_Handler::open, try to read from
an ACE_Asynch_Read_Stream
3) Verify it returns >= 0 with no error
> BZ-4217 Android 6 with 3rd party AIO not working

- ACE/ace/Time_Value.cpp
- ACE/ace/Time_Value.inl
- ACE/tests/Time_Value_Test.cpp
ACE_Time_Value::set(double):
- Handle large positive and negative double values by limiting them to possible values for sec and usec
- Correct round for negative double values: -10.5 => -10 -500000 (not -10 -499999)
- No normalize needed cause result is already normalized
ACE_Time_Value::normalize():
- Better performance by not using a loop for normalizing time values which will take very long time for 64 bit values.
Tests:
- Added tests for setting of double values and to check performance of normalize for large numbers.
> Fix for  Bug 4084 - ACE_Time_Value::set(double) hangs on large numbers 

- ACE/include/makeinclude/platform_android.GNU
[Changed]
platform_android.GNU
- replace the platform_linux_common.GNU include with its contents
except the erroneous call to getconf
[Tests]
Test 1:
1) Compile ACE for Android using OSX or Windows
2) Verify build is successful
> BZ-4216 Android build fails when not cross-compiled on Linux

- ACE/tests/Time_Value_Test.cpp
* ACE/tests/Time_Value_Test.cpp:
> Extended test to check that max_time is not {0, -1}

- ACE/include/makeinclude/rules.nested.GNU
Improves start/finish logging for applications using the ACE-supplied GNU build system. This is not for the ACE build itself.
> Riverace-2053: improve start/finish build logging

- ACE/include/makeinclude/platform_g++_common.GNU
- TAO/docs/leader_follower.html
- TAO/orbsvcs/orbsvcs/SSLIOP/IIOP_SSL_Connector.cpp
- TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Connector.cpp
- TAO/tao/IIOP_Connector.cpp
- TAO/tao/LF_CH_Event.cpp
- TAO/tao/LF_CH_Event.h
- TAO/tao/LF_Connect_Strategy.cpp
- TAO/tao/LF_Event.cpp
- TAO/tao/LF_Event.h
- TAO/tao/LF_Event.inl
- TAO/tao/LF_Invocation_Event.cpp
- TAO/tao/LF_Invocation_Event.h
- TAO/tao/LF_Multi_Event.cpp
- TAO/tao/LF_Multi_Event.h
- TAO/tao/Leader_Follower.cpp
- TAO/tao/Leader_Follower.h
- TAO/tao/Reactive_Connect_Strategy.cpp
- TAO/tao/Strategies/SCIOP_Connector.cpp
- TAO/tao/Strategies/SHMIOP_Connector.cpp
- TAO/tao/Strategies/UIOP_Connector.cpp
- TAO/tao/Transport_Connector.cpp
- TAO/tao/Wait_On_Reactor.cpp
- TAO/tao/Wait_On_Read.cpp
- TAO/tests/Bug_3531b_Regression/server.cpp
The leader follower event is normally just used in the LF loop but when making a new connection the connector also checks the state of the event. This could trigger a possible race condition, the LF loop changes the event state at the moment the connector checks the state. Solves this by changing the keep_waiting/error_detected/successfull event accesses to required the LF so that they can check the state with the LF mutex locked. The LF loop can use the _i versions to check within the LF loop. 
Changed some signatures to use bool and enum, that uncovered an incorrect check in Wait_On_Read.
> Fix possible race conditions with leader follower

- ACE/ace/config-linux.h
- ACE/ace/config-macosx-lion.h
- ACE/ace/config-macosx-snowleopard.h
Making pull request upon request.  
More info can be found on [mailing lists](http://list.isis.vanderbilt.edu/pipermail/ace-bugs/2017-January/000032.html).
> ACE_HAS_GCC_ATOMIC_BUILTINS should be defined for clang

- TAO/orbsvcs/orbsvcs/FT_NamingReplication.idl
- TAO/orbsvcs/orbsvcs/FT_Naming_Serv.mpc
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Manager.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Manager.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Replication_Manager.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Replication_Manager.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Server.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Server.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Group_Factory.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Group_Factory.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Object_Group_Storable.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Object_Group_Storable.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context_Factory.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context_Factory.h
- TAO/orbsvcs/orbsvcs/Naming/Naming_Server.cpp
- TAO/orbsvcs/orbsvcs/Naming/Naming_Server.h
- TAO/orbsvcs/orbsvcs/Naming/Storable_Naming_Context.cpp
- TAO/orbsvcs/tests/FT_Naming/FaultTolerant/FaultTolerant.mpc
- TAO/orbsvcs/tests/FT_Naming/Replication/run_test.pl
This includes the whole feature replacement introducing a second ORB dedicate to managing state transfer between the primary and backup naming servers. Under heavy loads, updating the peer naming service can take a fair amount of time, which gets stolen from the primary application role of resolving request.
> Update to FT Naming hot-standby synchronization

- ACE/ace/INET_Addr.cpp
- ACE/tests/INET_Addr_Test_IPV6.cpp
Previously ignored a caller's specifying "tcp"
> Fix ability to request IPv4 address from ACE_INET_Addr::set

- ACE/include/makeinclude/rules.local.GNU
Allows postprocessor scripts to keep track of where problems are in parallel builds.
> Change recipe to use full pathname of source file for C/C++.

- ACE/ace/config-android.h
> When ACE_HAS_FD_MASK has not been defined we set ACE_LACKS_FD_MASK

- ACE/ace/Capabilities.cpp
- ACE/ace/Capabilities.h
- ACE/ace/OS_NS_Thread.cpp
- ACE/ace/OS_NS_Thread.inl
- ACE/ace/Object_Manager.cpp
- ACE/ace/Static_Object_Lock.h
* ACE/ace/Capabilities.cpp:
* ACE/ace/Capabilities.h:
* ACE/ace/OS_NS_Thread.inl:
* ACE/ace/Object_Manager.cpp:
* ACE/ace/Static_Object_Lock.h:
> Removed ACE_IS_SPLITTING, simplifies our code

- ACE/ASNMP/asnmp/octet.cpp
- ACE/ASNMP/tests/Counter64_Test.cpp
- ACE/ace/Configuration_Import_Export.cpp
- ACE/ace/config-win32-borland.h
- ACE/examples/Mem_Map/IO-tests/IO_Test.cpp
- ACE/examples/Mem_Map/IO-tests/test_io.cpp
- TAO/tao/orbconf.h
* ACE/ASNMP/asnmp/octet.cpp:
* ACE/ASNMP/tests/Counter64_Test.cpp:
* ACE/ace/Configuration_Import_Export.cpp:
* ACE/examples/Mem_Map/IO-tests/IO_Test.cpp:
* ACE/examples/Mem_Map/IO-tests/test_io.cpp:
* TAO/tao/orbconf.h:
> Use ACE_WIN32 and bcc32c doesn't set __WIN32__ but uses _WIN32

- ACE/protocols/ace/TMCast/Group.cpp
Use dynamic_cast to replace typeid() which causes the clang++ warning “expression with side effects will be evaluated despite being used as an operand to 'typeid' [-Wpotentially-evaluated-expression]”
> Avoid clang warning

- ACE/ace/Pipe.cpp
- ACE/ace/Shared_Memory_Pool.cpp
The fix allows ACE to compile on macOS when ACE_FACE_SAFETY_BASE or ACE_FACE_SAFETY_EXTENDED is defined.
> Fix compiler issues on macOS with ACE_FACE_SAFETY* defined

- ACE/ace/config-lite.h
- ACE/ace/config-sunos5.10.h
- TAO/orbsvcs/tests/CosEvent/Basic/Random.cpp
- TAO/orbsvcs/tests/CosEvent/Basic/Random.h
- TAO/tests/IDL_Test/union.idl
These changes were necessary to get a complete successful build with the Oracle's developerstudio12.5 on Solaris 11.3 including examples and tests. 
I'm not sure whether the tests are also run, or merely compiled with a plain "make" within each of ACE_ROOT and TAO_ROOT.
I can't test it on any other platform, but I am positive that these changes would fix more than break.
Having someone test it e.g. with DeveloperStudio12.5 on Linux (just to be safe) wouldn't hurt, though.
> Fixing build for Oracle DeveloperStudio12.5 (C++ 5.14)

- ACE/ace/OS_NS_sys_utsname.cpp
- ACE/ace/Object_Manager_Base.cpp
- ACE/tests/tests.mpc
* ACE/ace/OS_NS_sys_utsname.cpp:
* ACE/ace/Object_Manager_Base.cpp:
> Disable deprecated warnings when using clang

- ACE/ace/OS_NS_Thread.h
- TAO/examples/Quoter/Factory_Finder.cpp
- TAO/examples/Quoter/client.cpp
- TAO/orbsvcs/LifeCycle_Service/LifeCycle_Service.cpp
- TAO/tao/PortableServer/Servant_var.h
* ACE/ace/OS_NS_Thread.h:
* TAO/examples/Quoter/Factory_Finder.cpp:
* TAO/examples/Quoter/client.cpp:
* TAO/orbsvcs/LifeCycle_Service/LifeCycle_Service.cpp:
* TAO/tao/PortableServer/Servant_var.h:
> Fix gcc7 warnings and remove commented out throws

- TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_EVP_PKEY.cpp
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_EVP_PKEY.cpp:
> Fixed compile error with older SSL versions

- ACE/ace/config-macros.h
- ACE/bin/MakeProjectCreator/modules/GNUACEWorkspaceCreator.pm
- ACE/bin/MakeProjectCreator/templates/gnu.mpd
- ACE/include/makeinclude/platform_hpux_aCC.GNU
- ACE/include/makeinclude/platform_linux.GNU
- Set ACE_HAS_DYNAMIC_LINKING=0 when not linking to libdl on linux
- rpath: move HP-UX settings to its own config file; support newer Apple macOS
> gnuace build improvements

- TAO/tao/Unbounded_Octet_Sequence_T.h
* TAO/tao/Unbounded_Octet_Sequence_T.h:
> Const fix to resolve C++ core guideline warning

- ACE/NEWS
- ACE/bin/diff-builds-and-group-fixed-tests-only.sh
- ACE/debian/debian.control
- ACE/docs/Download.html
- ACE/docs/bczar/bczar.html
- ACE/etc/index.html
- TAO/NEWS
* ACE/NEWS:
* ACE/debian/debian.control:
* TAO/NEWS:
> Make ACE 6.4.6 and TAO 2.4.6 public

- ACE/tests/.gitignore
- ACE/tests/Singleton_Restart_Test.cpp
- ACE/tests/run_test.lst
- ACE/tests/tests.mpc
Some lock types work, others don't, due to different logic per lock type
in ACE_Object_Manager::get_singleton_lock and how ACE_Singleton uses it.
> New ACE test: check if ACE_Singleton works after ACE::fini, ACE::init

- TAO/orbsvcs/orbsvcs/CosEvent/CEC_TypedEventChannel.h
- TAO/orbsvcs/orbsvcs/Naming/Hash_Naming_Context.h
- TAO/orbsvcs/orbsvcs/Naming/Naming_Context_Interface.h
- TAO/orbsvcs/orbsvcs/Naming/Storable_Naming_Context.h
- TAO/tests/Bug_2953_Regression/client.cpp
- TAO/tests/Bug_2953_Regression/server.cpp
- TAO/tests/Smart_Proxies/Benchmark/client.cpp
- TAO/tests/Smart_Proxies/Policy/client.cpp
- TAO/tests/Smart_Proxies/client.cpp
* TAO/orbsvcs/orbsvcs/CosEvent/CEC_TypedEventChannel.h:
* TAO/orbsvcs/orbsvcs/Naming/Hash_Naming_Context.h:
* TAO/orbsvcs/orbsvcs/Naming/Naming_Context_Interface.h:
* TAO/orbsvcs/orbsvcs/Naming/Storable_Naming_Context.h:
* TAO/tests/Bug_2953_Regression/client.cpp:
* TAO/tests/Bug_2953_Regression/server.cpp:
* TAO/tests/Smart_Proxies/Benchmark/client.cpp:
* TAO/tests/Smart_Proxies/Policy/client.cpp:
* TAO/tests/Smart_Proxies/client.cpp:
> Doxygen fixes and fixed some typos

- ACE/ace/config-win32-borland.h
> Any bcc32 version doesn't support inlined assembly

- ACE/ace/SOCK_Acceptor.cpp
Fixes test-execution problems on Windows
> Remove preproc checks - if ACE_HAS_IPV6 is set, the IPV^ defs should be there too.

- TAO/orbsvcs/ImplRepo_Service/Activator_Options.cpp
Hi,
I have a issue on installing the ImRActivator on Windows 2012 Server. My settings was not read by service when it was started. Because ImR Locator worked fine, I've compared Locator_Options.cpp and Activator_Options.cpp and saw some differences at the code that read "ORBInitOptions" key data, for example. I've copied the same solution to Activator_Options.cpp and the service is working fine now.
Kind Regards,
Reinaldo Guedes
> Fix Unicode issue on load registry data

- ACE/ace/CDR_Base.cpp
- ACE/ace/config-win32-borland.h
> Disable intel assembly when using the Embarcadero clang compilers

- ACE/ace/XML_Utils/XML_Helper.h
- ACE/ace/XML_Utils/XSCRT/Elements.hpp
* ACE/ace/XML_Utils/XML_Helper.h:
* ACE/ace/XML_Utils/XSCRT/Elements.hpp:
> Make use of std::unique_ptr when C++11 is used

- TAO/orbsvcs/tests/Bug_3215_Regression/client.cpp
- TAO/orbsvcs/tests/FT_Naming/stress_storable/client.cpp
- TAO/orbsvcs/tests/Notify/Bug_1884_Regression/consumer.cpp
- TAO/orbsvcs/tests/Notify/Bug_1884_Regression/filter.cpp
- TAO/orbsvcs/tests/Notify/Bug_1884_Regression/supplier.cpp
- TAO/orbsvcs/tests/Notify/Bug_3688_Regression/consumer.cpp
- TAO/orbsvcs/tests/Notify/Bug_3688_Regression/supplier.cpp
- TAO/tests/Bug_2241_Regression/Client_Task.cpp
- TAO/tests/Collocated_ThruP_Sp/Client_Task.cpp
- TAO/tests/Collocated_ThruP_Sp_Gd/Client_Task.cpp
- TAO/tests/UNKNOWN_Exception/client.cpp
* TAO/orbsvcs/tests/Bug_3215_Regression/client.cpp:
* TAO/orbsvcs/tests/FT_Naming/stress_storable/client.cpp:
* TAO/orbsvcs/tests/Notify/Bug_1884_Regression/consumer.cpp:
* TAO/orbsvcs/tests/Notify/Bug_1884_Regression/filter.cpp:
* TAO/orbsvcs/tests/Notify/Bug_1884_Regression/supplier.cpp:
* TAO/orbsvcs/tests/Notify/Bug_3688_Regression/consumer.cpp:
* TAO/orbsvcs/tests/Notify/Bug_3688_Regression/supplier.cpp:
* TAO/tests/Bug_2241_Regression/Client_Task.cpp:
* TAO/tests/Collocated_ThruP_Sp/Client_Task.cpp:
* TAO/tests/Collocated_ThruP_Sp_Gd/Client_Task.cpp:
* TAO/tests/UNKNOWN_Exception/client.cpp:
> Catch exceptions by reference, not by value

- ACE/ace/CDR_Stream.h
> added explicit include of <string> to fix older MSVC compile errors

- TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_cs.cpp
* TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_cs.cpp:
> Make use of std::unique_ptr when we have C++11 or newer

- TAO/orbsvcs/ImplRepo_Service/ImR_Activator_i.cpp
* TAO/orbsvcs/ImplRepo_Service/ImR_Activator_i.cpp:
> Fixed incorrect order of arguments to logging macro

- TAO/tao/AnyTypeCode/Any_Array_Impl_T.cpp
* TAO/tao/AnyTypeCode/Any_Array_Impl_T.cpp:
> Make use of std::unique_ptr when C++11 or newer is enabled

- ACE/ace/SSL/SSL_Context.cpp
when compiling ACE by MinGW, it reports
``` 
SSL_Context.cpp:175:22: warning: ‘void RAND_screen()’ is deprecated (declared at openssl/rand.h:66) [-Wdeprecated-declarations]
```
See also: https://www.openssl.org/docs/man1.1.0/crypto/RAND_screen.html
> Use RAND_poll instead of RAND_screen that is deprecated in OpenSSL 1.1

- ACE/include/makeinclude/platform_aix_g++.GNU
- ACE/include/makeinclude/platform_sunos5_g++.GNU
In AIX and Solaris, linking rpath is `-Wl,-R` rather than `-Wl,--rpath`.
> Fix AIX and Solaris linking rpath errors.

- .gitignore
- ACE/ACE-INSTALL.html
- ACE/ace/config-android.h
- ACE/ace/os_include/sys/os_sem.h
- ACE/include/makeinclude/platform_android.GNU
- ACE/include/makeinclude/platform_clang_common.GNU
- TAO/TAO-INSTALL.html
This PR addresses #676 by allowing ACE and TAO to compile against Android NDK r18+, which uses Clang instead of GCC. This is still a work in progress as support for older NDKs is spotty. In addition these changes intentionally break builds using NDKs older than r16 because these are missing  `ndk_version.h` which is needed to determine what macros for ACE are needed. This can to fixed by supplying the correct values `__NDK_MAJOR__` and `__NDK_MINOR__` in `platform_macros.GNU`. In exchange for this, assuming `config-android.h` is written correctly, ACE should be backwards compatible with NDKs from now on.
> Support for Clang based Android NDKs

- ACE/ace/config-android.h
- ACE/include/makeinclude/platform_android.GNU
Giving an error is not user friendly, we just not set ACE_HAS_SEMUN when it is not usable
This is a change related to PR #726
> Only define ACE_HAS_SEMUN when we have API >= 12 and at least NDK 15

- ACE/ace/config-android.h
- ACE/ace/os_include/sys/os_sem.h
> Revert "Android NDK13 does ship a senum type, isn't usable, but ACE shouldn't…"

- ACE/ace/Vector_T.h
- ACE/ace/Vector_T.inl
- ACE/tests/.gitignore
- ACE/tests/Vector_Test.cpp
It was based on the the base array, not the actual elements in the array.
This is an example program that would fail:
```C++
#include <ace/Vector_T.h>
typedef ACE_Vector<int> Vector;
int main() {
Vector v;
for (Vector::iterator i = v.begin(); i != v.end(); ++i) {
return 1;
}
return 0;
}
```
> Fix end() on ACE_Vector

- TAO/TAO_IDL/include/idl_version.h
* TAO/TAO_IDL/include/idl_version.h:
> Removed unnecessary export macro, triggers a lot of warnings with mingw

- TAO/TAO_IDL/driver/drv_args.cpp
Long options were added in #723 but unknown options were not being passed to the backend to give it a chance to process them.
To fix a problem with CIAO passing an undocumented long option to opendds_idl.
> tao_idl: pass unknown options to backend to process

- ACE/NEWS
- TAO/MPC/config/taobaseidldefaults.mpb
- TAO/NEWS
- TAO/orbsvcs/orbsvcs/HTIOP.mpc
- TAO/orbsvcs/orbsvcs/SSLIOP.mpc
Using `output_follows_input = 0`, set IDL output location to be the current directory when using `IDL_Files` in MPC.
> Support IDL output in places other than the IDL file location

- TAO/TAO_IDL/ast/ast_decl.cpp
* TAO/TAO_IDL/ast/ast_decl.cpp:
> Fixed memory leak of annotation_appls_

- ACE/ace/MEM_Addr.inl
The comment of ACE_Mem_Addr::get_host_addr definition:
https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/ace/MEM_Addr.h#L108
> Fix ACE_Mem_Addr::get_host_addr by getting external address.

- ACE/ace/DLL_Manager.cpp
Fix ACE_DLL_Manager without error info when loading a shared object with undefined symbol.
> Fix ACE_DLL_Manager error info

- ACE/ace/MEM_Connector.cpp
- ACE/ace/MEM_Connector.h
To keep consistent with ACE_SOCK_Connector similar member functions.
> Let ACE_MEM_Connector timeout parameters const.

- ACE/ace/Global_Macros.h
- ACE/ace/Log_Msg.cpp
- ACE/ace/OS_NS_Thread.cpp
- ACE/ace/Service_Gestalt.cpp
* ACE/ace/Global_Macros.h:
* ACE/ace/Log_Msg.cpp:
* ACE/ace/Service_Gestalt.cpp:
> Removed ACE_NO_HEAP_CHECK macro because it is broken, see issue #733

- ACE/ace/Arg_Shifter.cpp
- ACE/ace/Arg_Shifter.h
- ACE/tests/Arg_Shifter_Test.cpp
Also cleaned up some comments and style guidelines violations.
> Support instantiating ACE_Arg_Shifter_T<char> in wchar builds.

- ACE/ace/OS_NS_sys_socket.h
- ACE/ace/SOCK_Dgram.cpp
- ACE/ace/SOCK_Dgram.h
- ACE/tests/SOCK_Dgram_Test.cpp
Sometimes, like when implementing an ICE agent, it is necessary to know which IP address was used when receiving a packet when listening on INADDR_ANY.
> Provide option for local address for SOCK_Dgram recvmsg

- ACE/ace/Log_Record.cpp
To reduce memory usage, free buffer before allocating new one.
> Free log record buffer before allocating new buffer.

- ACE/ace/ACE.cpp
- ACE/ace/Sbrk_Memory_Pool.cpp
char `strnew` and `strdup` have code of ACE_HAS_ALLOC_HOOKS, but wchar_t versions haven't.
> Fix wchar_t strnew and strdup.

- ACE/ace/OS_NS_unistd.cpp
- ACE/netsvcs/lib/Client_Logging_Handler.cpp
- ACE/netsvcs/lib/Name_Handler.cpp
- ACE/netsvcs/lib/Server_Logging_Handler_T.cpp
- ACE/netsvcs/lib/TS_Clerk_Handler.cpp
- ACE/netsvcs/lib/TS_Server_Handler.cpp
* ACE/netsvcs/lib/Client_Logging_Handler.cpp:
* ACE/netsvcs/lib/Name_Handler.cpp:
* ACE/netsvcs/lib/Server_Logging_Handler_T.cpp:
* ACE/netsvcs/lib/TS_Clerk_Handler.cpp:
* ACE/netsvcs/lib/TS_Server_Handler.cpp:
> Fix C++11 related warnings given by newer gcc versions

- ACE/tests/SOCK_Dgram_Test.cpp
Problem: SOCK_Dgram_Test fails on safety profile
Solution: Fall back to normal receive when testing with safety profile.
> Fix SOCK_Dgram_Test on safety profile

- ACE/ACE-INSTALL.html
- ACE/NEWS
- ACE/ace/config-android.h
- ACE/include/makeinclude/platform_android.GNU
- ACE/include/makeinclude/platform_linux.GNU
- ACE/include/makeinclude/platform_linux_common.GNU
In a regular Android app, the system has preloaded the system SSL library (which can be any version of OpenSSL or BoringSSL) for use in the Android API. Even if OpenSSL is statically linked, the symbols that have already been loaded will take precedence and will be used instead. This change to `ace_openssl` on Android requires that OpenSSL symbols be kept hidden from the global linking, causing the symbols to be fixed to the OpenSSL library being included.
> Try to Prevent Usage of System SSL on Android

- ACE/tests/SOCK_Dgram_Test.cpp
> SOCK_Dgram_Test: remove hardcoded buffer length

- ACE/ace/config-android.h
Fixes linking errors caused by enabling hidden visibility in #858 which I unfortunately must have done without testing. This does build on NDK 19 and I'm [testing it OpenDDS-Android as well](https://travis-ci.org/iguessthislldo/OpenDDS-Android/builds/506532752).
I changed it to match `config-linux.h` below and let `config-g++-common.h` do its job. For me this confirms the fact that there should be a `config-linux-common.h` like there is a `platform_linux_common.GNU`. I would like to do that in the future but I need to sort out what's necessary to keep for Android and what is leftover from the `config-linux.h` when they diverged.
> Fix Android Linking Errors

- ACE/ace/Log_Msg_Android_Logcat.cpp
* ACE/ace/Log_Msg_Android_Logcat.cpp:
> Fixed unused parameter warning when compiling for Android

- TAO/orbsvcs/examples/ImR/Advanced/Advanced.mpc
- TAO/orbsvcs/tests/FT_App/FT_App.mpc
VS2017 and VS2019 require each file to be listed in a single section, no overlaps
> orbsvcs tests/examples: removed MPC and Perl files from Documentation_Files, they are already elsewhere in the project

- TAO/TAO_IDL/docs/annotations.md
On compiling the `union Grade` example, tao_idl complains about the missing keyword *switch*.
Further, tao_idl complains `identifier spellings differ only in case: "grade" and "Grade"` but I didn't fix that one, assuming use of the tao_idl switch *-Cw* to soften the error into a warning.
> TAO/TAO_IDL/docs/annotations.md : typo fixes

- TAO/TAO_IDL/ast/ast_annotation_decl.cpp
- TAO/TAO_IDL/ast/ast_decl.cpp
- TAO/TAO_IDL/docs/annotations.md
- TAO/TAO_IDL/fe/fe_lookup.cpp
- TAO/TAO_IDL/fe/idl.tab.cpp
- TAO/TAO_IDL/fe/idl.ypp
- TAO/tests/IDLv4/annotations/be_init.cpp
- In `annotations.md`, Fix links broken by #897, Also address "identifier spellings differ only in case" warning on an example and some other small things.
- Fix segfault caused by #822 when dumping the AST in `tao_idl` using `--dump` and friends.
- At least one OMG standard annotation,`@mutable`, just happens to also be a C++ keyword. C++ keywords are prefixed with `_cxx_` to allow them to be used. Annotations identifiers *(should)* never be used in the result, C++ or otherwise, and this might mess up backend processing of those annotations so reverse the prefixing (which occurs in lexing) in the grammar file for annotation identifiers and annotation member identifiers. Constants and such should be okay... I think.
- Added test case to `annotest_idl`. As the commit says, the original …
> TAO_IDL: Minor Annotation Fixes

- ACE/NEWS
- ACE/ace/Log_Msg.cpp
- ACE/ace/OS_NS_Thread.cpp
- ACE/ace/OS_NS_Thread.h
- ACE/ace/OS_NS_Thread.inl
- ACE/ace/config-android.h
- ACE/ace/config-linux-common.h
- ACE/ace/config-linux.h
On Linux systems that support it, use `gettid()` to get a much smaller number for the thread id.
The main motivator for this PR, besides slightly smaller logs for OpenDDS, is the fact that gdb on linux has two identifiers for threads beside the simple thread index; One is LWP (Light Weight Process), which is another name for the TID that `gettid()` returns, and other is the pthread_t value in hex.
Also refactored `config-android.h` and `config-linux.h`, pulling out the common parts into a `config-linux-common.h` so that the check for gettid could go into the common file.
> Linux: Refactor config-linux.h and use gettid() for %t for Log_Msg

- ACE/ace/config-linux-common.h
Recent glibc v2.30 dropped XSI STREAMS declarations,
which causing below build failure.
poky/build/tmp/work/corei7-64-poky-linux/ace/6.5.6-r0/ACE_wrappers/ace/os_include/os_stropts.h:56:17: fatal error: stropts.h: No such file or directory
56 | #  include /**/ <stropts.h>
|                 ^~~~~~~~~~~
compilation terminated.
Added GLIBC checks for affected versions.
For more information about glibc v2.30 change, please check:
https://sourceware.org/git/?p=glibc.git;a=commit;h=a0a0dc83173ce11ff45105fd32e5d14356cdfb9c
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
> config-linux-common.h: fix glibc build failure

- ACE/ace/Service_Repository.cpp
This method was performing two iterations: the first using an index, and
the second in the call to this->service_array_.find, which uses an
iterator over the Array_Map looking for the element with that index.
This simplifies and optimizes this method by iterating for the element
once using directly the map iterator.
> Optimization: avoid nested iteration in ACE_Service_Repository::find_i

- TAO/orbsvcs/orbsvcs/PortableGroup/Fragments_Cleanup_Strategy.cpp
Constants can be moved outside the loop so delay is calculated just one, and
gettimeofday is only called once for each invocation to cleanup (it is
assumed that the difference in time for each loop cycle is irrelevant for
the cleanup strategy).
Callgrind reports of my application showed an unexpected high cost in this function. This alleviates the problem.
> Optimization: avoid invoking gettimeofday in each loop cycle

- ACE/bin/auto_run_tests.pl
Minor fix for scoreboard saying the `run_test.pl` for an OpenDDS test returned 256 when it actually returned 1.
> Get Correct Program Return Code in auto_run_tests.pl

- ACE/tests/Compiler_Features_32_Test.cpp
* ACE/tests/Compiler_Features_32_Test.cpp:
> Workaround is still necessary with clang9

- ACE/ace/Stack_Trace.cpp
(cherry picked from commit f2e5a03abba643eb6da996c5db23ad51bc49b9df)
> Extend Stack_Trace to support ARM/ARM64 on Windows

- ACE/include/makeinclude/rules.local.GNU
I wanted to use `make --touch` on OpenDDS, which worked but it created all these `makefile_name.local` files everywhere. To stop that, `makefile_name.local` has to be declared as phony because it's not a real file. Props to @mitza-oci for making this more clear to me.
> gnuace: declare makefile_name.local to be phony

- ACE/bin/fuzz.pl
I mentioned this in [#967](https://github.com/DOCGroup/ACE_TAO/pull/967#issuecomment-539148218):
> So the fuzz has a check for #include <...>. I want to know if I can disable this check, because I don't think this convention is right since it forces the compiler to check the current directory for the header is definitely not there. fuzz.pl just says:
>
> > This check is suggested by Don Hinton to force user to use # " " instead of <> to avoid confict with Doxygen.
>
> What kind of conflict was it and will it still happen? Regardless this sounds like Doxygen was/is being configured incorrectly to me.
I know this check isn't necessarily harmful, but it's a restriction that seems to be arbitrary to me, especially since Doxygen should be just be documenting what the code, not dictating how we …
> fuzz.pl: Disable check_include by Default

- ACE/bin/MakeProjectCreator/templates/gnu.mpd
Same idea as #975, except for targets for warning why a project won't be built.
> gnuace: declare various warnings to be phony

- ACE/ace/OS_NS_sys_stat.inl
The original `ACE_OS::filesize` opens file with `O_RDONLY`, which would
fail to open CACHE.DATA of [InterSystems Caché ](https://en.wikipedia.org/wiki/InterSystems_Cach%C3%A9) in AIX.
To open it successfully, it requires `O_CIO` additionally which is not
portable even for AIX.
> Use ACE_OS::stat for ACE_OS::filesize.

- TAO/TAO_IDL/ast/ast_annotation_appls.cpp
Discovered that if there are no scopes, then bottom() will return nullptr. This was discovered in my own tests where the AST was constructed programatically and not by the frontend.
> Prevent crash

- ACE/ace/XML_Utils/XML_Schema_Resolver.cpp
- ACE/protocols/ace/INet/INet_Log.cpp
- ACE/tests/Env_Value_Test.cpp
Inline conversion of character pointer types can leave pointers to temporary buffers in value_ and cause subsequent read access violations.
See #999
> Avoid the use of unmanaged strings in ACE_Env_Helper

- ACE/ace/config-posix.h
> Fixed typo in config-posix.h

- TAO/TAO_IDL/fe/idl.tab.cpp
- TAO/TAO_IDL/fe/idl.tab.hpp
- TAO/TAO_IDL/fe/idl.ypp
- TAO/TAO_IDL/include/ast_field.h
- TAO/TAO_IDL/include/utl_stack.h
- TAO/TAO_IDL/util/utl_stack.cpp
- TAO/tests/IDLv4/annotations/Annotation_Test.cpp
- TAO/tests/IDLv4/annotations/Annotation_Test.h
- TAO/tests/IDLv4/annotations/annotation_tests.cpp
Fix for #997
When the original annotation work (#723) was done it was assumed that when annotations didn't define the symbol being used, the lookup for the parameters would go up the scope stack from the current scope. This turned out not the case, so this functionality was implemented just for annotation parameters.
> Fix for Annotation Param Scope Issue

- ACE/ace/Synch_Options.cpp
- TAO/TAO_IDL/ast/ast_interface.cpp
- TAO/TAO_IDL/ast/ast_interface_fwd.cpp
- TAO/TAO_IDL/be/be_visitor_context.cpp
- TAO/TAO_IDL/include/ast_interface_fwd.h
- TAO/TAO_IDL/include/utl_scope_T.cpp
- TAO/TAO_IDL/util/utl_scope.cpp
Various fixes for tao_idl built using clang with `-fsanitize=undefined,address` passed.
- Work around static init ub in `ACE_Sync_Options`.
- Fix a memory leak in `UTL_Scope` and a possible null dereference in tao_idl be.
- Fixed a hard to track down memory leak involving `AST_InterfaceFwd` not handling ownership of its placeholder `AST_Interface` correctly under a case when a forward declaration of an interface is made after the interface was already declared.
> Various fixes for tao_idl built using clang with -fsanitize=undefined,address passed.

- ACE/tests/Compiler_Features_38_Test.cpp
- TAO/tao/Unbounded_Object_Reference_Sequence_T.h
- TAO/tests/Policies/Manipulation.cpp
Removed from compiler test 38 the operator*& as it triggers ambiguity errors with 32bit
> Minor layout, doxygen changes. 

- ACE/ace/Process.h
Decorate `ACE_Process_Options::command_line` and `ACE_Process_Options::setenv` by `ACE_GCC_FORMAT_ATTRIBUTE` for GCC warning incorrect `printf` format.
Without `ACE_GCC_FORMAT_ATTRIBUTE`, the following snippet would neither be effective in run time nor warning in compile time.
```cpp
unsigned v = 1;
...
opts.set_env("KEY", "%s", v);
```
> Add ACE_GCC_FORMAT_ATTRIBUTE to ACE_Process_Options

- ACE/bin/auto_run_tests.pl
I've been wanting to do this since at least #943, because I remember being confused by some of this stuff then.
- Help message:
- It said test list options, like `-l` or `-a`, "only" do the tests from that option. That isn't true, they include the tests in the run in addition to other ones.
- Removed reference to non-existent `-c` option which is supposed to be an alias to `-Config`.
- Removed outdated synopsis and try to give a slightly more detailed explanation of the script.
- Documented `-Exclude`
- Moved configuration listing to its own option and made it do it for all test list files that would ran otherwise.
- Argument Parsing:
- Switched to using `GetOpt::Long` and added long options.
- Fixed dry run `-z` option which wasn't being parsed.
- Fixed that when using `-l` to specify …
> Rewrote auto_run_tests.pl Arg Parsing

- ACE/bin/make_release.py
Add a Latest_ACETAO tag to MPC for micro/minor/major in order to simplify our CI builds, they can just pull :atest ACE+TAO and latest Latest_ACETAO on MPC
> Add Latest_ACETAO tag to MPC

- ACE/ace/OS_NS_Thread.cpp
Need to avoid calling cond_destroy on a garbage struct.
Problem was seen on Windows when process doesn't have permissions to create named kernel objects.
Also ACE's emulated condition variables (USYNC_THREAD) shouldn't be creating named kernel objects -- not fixed in this PR.
> ACE_OS::rwlock_init - fixed bug when RW Lock is emulated and creating a condition variable fails

- TAO/TAO_IDL/tao_idl.mpc
When `DESTDIR` is specified, this `ln` command with a shell expansion doesn't work because the libraries don't exist in the `INSTALL_PREFIX` yet.
> Fix Make Install With DESTDIR

- ACE/tests/Compiler_Features_32_Test.cpp
Make it work with Apple Xcode-11.3.1 Clang compiler. Closes #1042
> Update Compiler_Features_32_Test.cpp for Apple Xcode-11.3.1

- ACE/ace/ACE.cpp
Value stored to 'n' is never read
> Fix build warnings.

- ACE/ace/DLL.cpp
- ACE/ace/DLL_Manager.cpp
- ACE/ace/DLL_Manager.h
At the moment ACE_OS::dlopen fails we directly log and put the error message into the error stack. We don't check for ENOENT, an unresolved symbol is also causing ENOENT and that error message has certain value. Side effect is that when multiple DLL names are tried (prefix/postfix changes) there could be multiple error messages into the error stack but the real error message is also there.
Because ACE_DLL_Handle::open_i does now the logging and pushing into the error stack the calling code is much simpler.
> Log all dlopen errors into the error stack coming from ACE_OS::dlopen

- ACE/rpmbuild/ace-tao.spec
- TAO/orbsvcs/IFR_Service/IFR_Service.mpc
These are the updates I need to do to build after a new version of ACE-TAO is released:
- BuildRequires: has a dependency on sendmail. Not sure why, but I don't have a mail server on my build machine and this makes it impossible to run `rpmbuild -tb ACE-TAO-src.tar.gz`
- We have legacy code that uses combat-tcl for CORBA. To compile idl into tcl, it uses both `tao_ifr` and `tao_ifr_service`.
> Additions related to rpmbuild

- ACE/ace/ACE_export.h
- ACE/ace/Basic_Types.h
- ACE/ace/config-macros.h
- ACE/ace/os_include/sys/os_types.h
- TAO/orbsvcs/orbsvcs/Shutdown_Utilities.cpp
* ACE/ace/ACE_export.h:
* ACE/ace/Basic_Types.h:
* ACE/ace/config-macros.h:
* ACE/ace/os_include/sys/os_types.h:
* TAO/orbsvcs/orbsvcs/Shutdown_Utilities.cpp:
> Cleanup some last leftovers from old and deprecated tandem support

- ACE/include/makeinclude/platform_clang_common.GNU
This part was changed in PR #1022 caused a lot of extra output using clang on macOS.
This commit redirects stderr from make's $(shell).
Extra output was:
```
@(#)PROGRAM:ld  PROJECT:ld64-530
BUILD 18:57:17 Dec 13 2019
configured to support archs: armv6 armv7 armv7s arm64 arm64e arm64_32 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
LTO support using: LLVM version 11.0.0, (clang-1100.0.33.17) (static support for 23, runtime is 23)
TAPI support using: Apple TAPI version 11.0.0 (tapi-1100.0.11)
```
> platform_clang_common.GNU: redirect stderr for version checks

- TAO/TAO_IDL/fe/idl.ll
- TAO/TAO_IDL/fe/idl.yy.cpp
* TAO/TAO_IDL/fe/idl.ll:
* TAO/TAO_IDL/fe/idl.yy.cpp:
> Removed left over ACE_CDR_LONGLONG_INITIALIZER, related to #1090

- TAO/orbsvcs/tests/Concurrency/CC_command.tab.cpp
- TAO/orbsvcs/tests/Concurrency/lex.CC_command.cpp
* TAO/orbsvcs/tests/Concurrency/CC_command.tab.cpp:
* TAO/orbsvcs/tests/Concurrency/lex.CC_command.cpp:
> Remove register keyword, illegal with C++17.

- ACE/bin/ace-install
- On running `find` for copying TAO libs and for copying ACE libs, prune directories `debian` and `tests`.
- On copying ACE executables change `ACE_PROGS` to `apps/gperf/src/ace_gperf`.
> Fixes for ACE/bin/ace-install

- ACE/include/makeinclude/platform_android.GNU
Modify the Android link step on Windows hosts to avoid a 'command line too long' error when linking a large number of object files.
> Modify Android link on Windows hosts to avoid error

- ACE/NEWS
- ACE/ace/Auto_Ptr.h
- ACE/ace/Compression/rle/RLECompressor.cpp
- ACE/ace/OS_NS_Thread.cpp
- ACE/ace/config-win32-borland.h
- ACE/ace/os_include/net/os_if.h
- TAO/orbsvcs/orbsvcs/IFRService/IFR_Service_Utils_T.cpp
- TAO/orbsvcs/orbsvcs/Notify/MonitorControlExt/MC_Default_Factory.h
- TAO/orbsvcs/orbsvcs/Notify/RT_Factory.h
- TAO/orbsvcs/tests/Concurrency/CC_command.tab.cpp
- TAO/orbsvcs/tests/Notify/Bug_3252_Regression/server.cpp
- TAO/tests/Bug_3574_Regression/test.cpp
* ACE/NEWS:
* ACE/ace/os_include/net/os_if.h:
* TAO/orbsvcs/orbsvcs/IFRService/IFR_Service_Utils_T.cpp:
* TAO/orbsvcs/orbsvcs/Notify/MonitorControlExt/MC_Default_Factory.h:
* TAO/orbsvcs/orbsvcs/Notify/RT_Factory.h:
* TAO/orbsvcs/tests/Notify/Bug_3252_Regression/server.cpp:
* TAO/tests/Bug_3574_Regression/test.cpp:
> Add support for Embarcadero C++ Builder 10.4 Sydney

- TAO/NEWS
- TAO/TAO_IDL/ast/ast_decl.cpp
- TAO/TAO_IDL/docs/annotations.md
- TAO/TAO_IDL/fe/idl.tab.cpp
- TAO/TAO_IDL/fe/idl.tab.hpp
- TAO/TAO_IDL/fe/idl.ypp
- TAO/TAO_IDL/fe/idl.yy.cpp
- TAO/TAO_IDL/include/utl_err.h
- TAO/TAO_IDL/util/utl_err.cpp
- TAO/tests/IDLv4/annotations/Annotation_Test.cpp
- TAO/tests/IDLv4/annotations/Annotation_Test.h
- TAO/tests/IDLv4/annotations/README.md
- TAO/tests/IDLv4/annotations/annotation_tests.cpp
Annotation support extended to on the following types and their
contents:
- Interfaces
- Porttypes
- Eventtypes
- Components
Annotations on Valuetypes and most of their possible contents are also
supported. The exceptions to this are these types of valuetype
statements:
- import: not supported by TAO
- typeid: not supported by TAO on valuetypes
- typeprefix: No corresponding AST Node to attach annotations to
> Extend Annotation Support

- TAO/TAO_IDL/fe/idl.tab.cpp
- TAO/TAO_IDL/fe/idl.ypp
- TAO/tests/IDLv4/annotations/Annotation_Test.cpp
- TAO/tests/IDLv4/annotations/Annotation_Test.h
Fixes for https://github.com/DOCGroup/ACE_TAO/pull/1125
- `TAO_IDL/fe.ypp`
- Fixed using wrong pointer in grammar.
- Other minor tweaks.
- `tests/IDLv4/annotations`
- Fixed preprocessor usage that some compilers don't like.
- Fixed passing `std::string` as a `const char*`.
- Rewrote IDL output function to try to be more flexible.
> Fixes for #1125

- TAO/TAO_IDL/fe/idl.tab.cpp
- TAO/TAO_IDL/fe/idl.ypp
Fixed using wrong pointer for add to scope in https://github.com/DOCGroup/ACE_TAO/pull/1132 for `interfaces`, now doing that for `eventtype` and `component`. See: https://github.com/DOCGroup/ACE_TAO/pull/1125#discussion_r434675138
> More Fixes for #1125

- ACE/ace/SSL/SSL_SOCK_Acceptor.cpp
- ACE/ace/SSL/SSL_SOCK_Connector.cpp
Replacing use of ::select() with ::poll() in SSL_SOCK_Connector and SSL_SOCK_Acceptor - on systems that support ::poll(). This is primarily to allow for more than 1024 connections.
> Replacing use of ::select in favor of ::poll

- ACE/debian/config-hurd.h
> debian hurd doesn't seem to have sys/sysctl.h

- TAO/TAO_IDL/util/utl_global.cpp
I discovered that with the version introducing the OldState helper class there is a problem with seems to be double delete. This was discovered in our code base that does something similar to store/restore state of IDL_GlobalData before invoking eval().
The easiest way for me to reproduce the error in plain ACE/TAO was to instanciate OldState twice which can seem to be a
little far fetched and shouldn't be there in the final code. So I temporarily did this to make the tests fail, and then fixed the bug before removing the temp code.
Please have a look at the code and let me know it there is a better way to do this.
Before merging to master I'd like to to a final check on the code so we're sure the result is correct.
> TAO_IDL: Memory management for eval

- ACE/ace/SOCK_Dgram.cpp
- ACE/tests/.gitignore
- ACE/tests/Multicast_Interfaces_Test.cpp
- ACE/tests/run_test.lst
- ACE/tests/tests.mpc
Currently on windows, joining multicast by interface name doesn't work for IPV4 addresses (a bug) and it only worked for the name accepted by if_nametoindex() for IPV6 addresses, which aren't particularly user-friendly. A better way to handle this is to make use of GetAdaptersAddresses() and compare the provided interface name against either the adapter name or the friendly name, similarly to how the non-if_nametoindex windows version of the code handles things.
For IPV4, I've added a block to do this. For IPV6, I've pulled the existing ifdef'd code up to run before attempting to match via if_nametoindex, when either are applicable.
> Improve Multicast Join by Interface Name on Windows

- ACE/tests/Multicast_Interfaces_Test.cpp
Avoids platform-specific struct definition in favor of generic typedef. Avoids "named" flag bits in favor of flags & mask.
> Fix Test Portability Issue For Older Windows Platforms Introduced By PR 1170

- ACE/tests/run_test.lst
Since ioctl calls are prohibited by FACE, this test won't work as expected on a safety profile build.
> Remove Multicast_Interfaces_Test from FACE safety builds

- ACE/ace/OS_NS_string.cpp
- ACE/ace/OS_NS_string.h
- ACE/ace/OS_NS_string.inl
* ACE/ace/OS_NS_string.cpp:
* ACE/ace/OS_NS_string.h:
* ACE/ace/OS_NS_string.inl:
> Removed memchr emulation, not used anymore by any platform config file

- ACE/bin/make_release.py
- ACE/docs/bczar/bczar.html
Part of Fix for #940
Assume `Latest_Major`, `Latest_Minor`, and `Latest_Micro`/`Latest_Beta` and the MPC equivalents are branches instead of tags.
The other part of the fix is actually changing the tags into branches.
Also updated the script to work with Python 3 (it still should work with Python 2.7 though), and tried to do some future proofing, mostly by wrapping the argument parser, because `optparse` is deprecated.
Also did some clean up. Simplifying some code, and using more normal Python patterns.
Use of non read-only global variables should be eliminated, because it's unusual to use them in Python, at least nowadays. I started to do this, but back tracked, because it was taking longer to do so than I would've liked to spend on it.
> make_release.py: Use Branches for Latest 

- ACE/ace/OS_NS_stdlib.h
- ACE/ace/OS_NS_stdlib.inl
- ACE/ace/config-g++-common.h
- ACE/ace/config-macros.h
To fix fallthrough warning in ACE.cpp. Also added to `ACE_OS::abort`.
> Create ACE_GCC_NO_RETURN, Add to ACE_OS::_exit

- ACE/ace/DLL_Manager.cpp
```shell
DLL_Manager.cpp: In member function 'int ACE_DLL_Handle::open(const ACE_TCHAR*, int, void*, ACE_DLL_Handle::ERROR_STACK*)':
DLL_Manager.cpp:160:60: error: no matching function for call to 'ACE_DLL_Handle::open_i(ACE_TCHAR [1025], int&)'
DLL_Manager.h:171:8: note: candidate is: bool ACE_DLL_Handle::open_i(const ACE_TCHAR*, int, ACE_DLL_Handle::ERROR_STACK*)
```
> Fix building DLL_Manager.cpp on AIX

- ACE/ace/Thread_Manager.cpp
* Fix `ACE_Thread_Descriptor_Base` object leak when failing to join thread.
* Fix deadlock in `ACE_Thread_Manager::exit` when thread is exiting and being join on the same time.
> Fix ACE_Thread_Manager::join memory leak and deadlock.

- ACE/ace/Refcounted_Auto_Ptr.h
- ACE/ace/Refcounted_Auto_Ptr.inl
Reverts DOCGroup/ACE_TAO#995
Failed to compile with vc7.1
```
WIN32_Proactor.cpp
..\ace\Refcounted_Auto_Ptr.inl(131) : error C2833: 'operator unspecified_bool_type' is not a recognized operator or type
..\ace\Refcounted_Auto_Ptr.inl(134) : fatal error C1903: unable to recover from previous error(s); stopping compilation
```
> Revert "Use unspecified_bool_type instead of bool."

- ACE/bin/MakeProjectCreator/config/MPC.cfg
* ACE/bin/MakeProjectCreator/config/MPC.cfg:
> No need for adding XSC_ROOT/MPC to dynamic_types

- ACE/rpmbuild/ace-tao.spec
> Removed setting of cidl, not used anymore for ACE/TAO

- ACE/bin/MakeProjectCreator/modules/GNUACEProjectCreator.pm
- ACE/bin/MakeProjectCreator/templates/gnu.mpd
- TAO/MPC/config/tao_rules.mpb
- TAO/MPC/config/taodefaults.mpb
- TAO/TAO_IDL/tao_idl.mpc
- TAO/TAO_IDL/tao_idl_be.mpc
- TAO/TAO_IDL/tao_idl_fe.mpc
* TAO/MPC/config/tao_rules.mpb:
Added.
* ACE/bin/MakeProjectCreator/templates/gnu.mpd:
Add precious files support leveraging MPC change providing extended "contains" template function
* ACE/bin/MakeProjectCreator/modules/GNUACEProjectCreator.pm:
* TAO/MPC/config/taodefaults.mpb:
* TAO/TAO_IDL/tao_idl.mpc:
* TAO/TAO_IDL/tao_idl_be.mpc:
* TAO/TAO_IDL/tao_idl_fe.mpc:
> Add precious files support and template cleanup

- ACE/bin/MakeProjectCreator/docs/templates/gnu.txt
- ACE/bin/MakeProjectCreator/templates/gnu.mpd
Related to https://github.com/DOCGroup/MPC/pull/116
> Removed xsc specific code, can be done through the verbatim mpc support

- ACE/ace/CDR_Base.h
std::iterator was deprecated in C++17.
This replaces inheritance by instead defining the typedefs earlier provided by std::iterator
> Remove deprecated std::iterator

- TAO/orbsvcs/orbsvcs/PortableGroup/PG_Properties_Encoder.h
* TAO/orbsvcs/orbsvcs/PortableGroup/PG_Properties_Encoder.h:
> Layout change

- TAO/tests/IDL_Test/IDL_Test.mpc
- TAO/tests/IDL_Test/array.idl
- TAO/tests/IDL_Test/array_anonymous.idl
- TAO/tests/IDL_Test/sequence.idl
- TAO/tests/IDL_Test/sequence_anonymous.idl
- TAO/tests/IDL_Test/union.idl
- TAO/tests/IDL_Test/union_anonymous.idl
* TAO/tests/IDL_Test/array_anonymous.idl:
* TAO/tests/IDL_Test/sequence_anonymous.idl:
* TAO/tests/IDL_Test/union_anonymous.idl:
Added.
* TAO/tests/IDL_Test/IDL_Test.mpc:
* TAO/tests/IDL_Test/array.idl:
* TAO/tests/IDL_Test/sequence.idl:
* TAO/tests/IDL_Test/union.idl:
> Moved anonymous IDL constructs to their own files

- TAO/bin/tao_orb_tests.lst
- TAO/tests/CORBA_is_nil/.gitignore
- TAO/tests/CORBA_is_nil/CORBA_is_nil.mpc
- TAO/tests/CORBA_is_nil/Hello.cpp
- TAO/tests/CORBA_is_nil/Hello.h
- TAO/tests/CORBA_is_nil/README.md
- TAO/tests/CORBA_is_nil/Test.idl
- TAO/tests/CORBA_is_nil/client.cpp
- TAO/tests/CORBA_is_nil/run_test.pl
- TAO/tests/CORBA_is_nil/server.cpp
- TAO/tests/CORBA_is_nil/svc.conf
TAO only specializes Object_ptr, but not pointers derived from
Object, relying on narrowed nil object references having been
converted to NULL pointers. This test confirms that this works
even if the lazy resource mode is used.
This is related to issue #1203
> Added test to confirm CORBA::is_nil works

- ACE/ace/Refcounted_Auto_Ptr.h
- ACE/ace/Refcounted_Auto_Ptr.inl
Reverts DOCGroup/ACE_TAO#1227 
Should now not be a problem now Visual Studio 7.1 is not supported anymore for ACE 7
> Revert "Revert "Use unspecified_bool_type instead of bool.""

- ACE/ACE-INSTALL.html
- ACE/ace/config-android.h
- ACE/bin/MakeProjectCreator/config/acedefaults.mpb
- ACE/include/makeinclude/platform_android.GNU
- ACE/include/makeinclude/platform_clang_common.GNU
- ACE/include/makeinclude/platform_g++_common.GNU
- ACE/include/makeinclude/rules.lib.GNU
- ACE/include/makeinclude/wrapper_macros.GNU
- ACE/tests/Compiler_Features_32_Test.cpp
Changes in https://github.com/DOCGroup/ACE_TAO/pull/1318 modified for capability's sake for ACE6.
- Made it easier to use `gnuace`-built libraries in as imported libraries in CMake-based Android Studio native projects.
- Replaced `ANDROID_ABI` with `android_abi`, but kept the former as an alias of the later for compatibility.
- Remove need to pass a macro to compiler about `android/ndk-version.h` unless the NDK is old
> [ACE6] Support Building with Android NDK Directly

- ACE/ace/CORBA_macros.h
- ACE/ace/Log_Msg.cpp
- ACE/ace/README
- ACE/ace/config-kfreebsd.h
- ACE/tests/Network_Adapters_Test.cpp
- ACE/tests/New_Fail_Test.cpp
* ACE/ace/Log_Msg.cpp:
* ACE/ace/config-kfreebsd.h:
* ACE/tests/Network_Adapters_Test.cpp:
* ACE/tests/New_Fail_Test.cpp:
> Removed ACE_HAS_EXCEPTIONS checks, that define is always set

- ACE/ace/OS_NS_stdio.inl
- ACE/ace/README
- ACE/ace/os_include/os_time.h
Resolves #1400 
* ACE/ace/OS_NS_stdio.inl:
* ACE/ace/os_include/os_time.h:
> Cleanup usage of ACE_HAS_DINKUM_STL, not set anymore in any config file

- ACE/ace/Dev_Poll_Reactor.cpp
It occurred on not only Solaris but also platforms with `ACE_HAS_DEV_POLL`.
> Fix unused variable reactor_resumes_eh on platforms which don't define ACE_HAS_DEV_POLL

- ACE/include/makeinclude/platform_g++_common.GNU
Older GNU ar may not have this option and this just suppresses an extra log output, so we can remove it.
Not doing this for master, as I'm assuming we're dropping support for the older toolchains that are missing this option.
> [ACE6] platform_g++_common.GNU: Remove ARFLAGS += -c

- ACE/include/makeinclude/wrapper_macros.GNU
* ACE/include/makeinclude/wrapper_macros.GNU:
> Only check valgrind_keep_debuginfo when valgrind is 1

- ACE/ACEXML/common/Attributes_Def_Builder.h
- ACE/ACEXML/common/Element_Def_Builder.h
- ACE/examples/Bounded_Packet_Relay/Thread_Bounded_Packet_Relay.cpp
- ACE/examples/Bounded_Packet_Relay/bpr_thread.cpp
- ACE/examples/C++NPv2/TP_Reactor_Logging_Server.cpp
- ACE/examples/Reactor/TP_Reactor/AcceptHandler.cpp
- ACE/examples/Shared_Malloc/test_multiple_mallocs.cpp
- ACE/examples/Shared_Malloc/test_position_independent_malloc.cpp
- ACE/examples/Timer_Queue/main_async.cpp
- ACE/examples/Timer_Queue/main_reactor.cpp
- ACE/examples/Timer_Queue/main_thread.cpp
- ACE/examples/Timer_Queue/main_thread_custom_handler.cpp
- ACE/protocols/ace/TMCast/Group.cpp
- ACE/protocols/ace/TMCast/Group.hpp
- ACE/protocols/ace/TMCast/MTQueue.hpp
* ACE/ACEXML/common/Attributes_Def_Builder.h:
* ACE/ACEXML/common/Element_Def_Builder.h:
* ACE/examples/Bounded_Packet_Relay/Thread_Bounded_Packet_Relay.cpp:
* ACE/examples/Bounded_Packet_Relay/bpr_thread.cpp:
* ACE/examples/C++NPv2/TP_Reactor_Logging_Server.cpp:
* ACE/examples/Reactor/TP_Reactor/AcceptHandler.cpp:
* ACE/examples/Shared_Malloc/test_multiple_mallocs.cpp:
* ACE/examples/Shared_Malloc/test_position_independent_malloc.cpp:
* ACE/examples/Timer_Queue/main_async.cpp:
* ACE/examples/Timer_Queue/main_reactor.cpp:
* ACE/examples/Timer_Queue/main_thread.cpp:
* ACE/examples/Timer_Queue/main_thread_custom_handler.cpp:
* ACE/protocols/ace/TMCast/Group.cpp:
* ACE/protocols/ace/TMCast/Group.hpp:
* ACE/protocols/ace/TMCast/MTQueue.hpp:
> Make use of std::unique_ptr instead of auto_ptr

- ACE/bin/MakeProjectCreator/templates/gnu.mpd
- TAO/MPC/config/tao_rules.mpb
Alternative fix for https://github.com/objectcomputing/OpenDDS/pull/2559. See there for details.
https://github.com/DOCGroup/ACE_TAO/pull/1296 changed the order of includes of rules make files to effectively being how the base projects that set them are included. This can lead to the order of `GNUACE_PROJECT_VERSION ?=` being set differently than what the case was in ACE6/TAO2. The result in OpenDDS is that so library files get TAO's version number.
This tires to fix that by including `tao.rules.GNU` at a marker after the `extension` marker.
> Defer Including rules.tao.GNU for gnuace

- TAO/TAO_IDL/fe/idl.tab.cpp
- TAO/TAO_IDL/fe/idl.ypp
This updates the wstring case, which has a leak, to behave more like the string case, which does not have a leak.
> [ACE6] Fix wstring coerce leak in tao_idl

- ACE/ace/Sock_Connect.cpp
Problems:
On Windows, SocketConnect::ip_check() will attempt to get the list of IP addresses associated with local network interfaces in order to determine if IPv6 or IPv4 is enabled, and then it will set a global flag in order to cache the result of this expensive check. Unfortunately, the global flag is toggled back and forth during this check, which is not thread safe. In addition, it appears as though this check can be done "too early" within a windows process (particularly if done as part of a static initialization) which will cause & cache a false negative, since no interfaces addresses are found.
Solutions:
1) Protect the global flag from modification until a real answer is available, and protect against recursive calls using a static initialized behind the existing mutex.
2) …
> [ACE6] Fix SocketConnect::ip_check() Concurrency and Too-Early Request Issues for Windows

- ACE/ace/SSL/SSL_Context.cpp
- ACE/ace/SSL/SSL_Context.h
ACE SSL lacked possibility to handle intermediate certificate CA's.
> Implemented ::SSL_CTX_use_certificate_chain_file function

- ACE/ace/TTY_IO.cpp
- ACE/ace/TTY_IO.h
This PR contains fixes and improvements to ACE TTY_IO on systems using POSIX termios API.
- Disable character conversions CR->NL, NL->CR
- Disable ISTRIP when databits == 8
- Added a new option to disable input parity checking
Tested on Linux (kernel 5.11.22)
> TTY_IO enhancements

- TAO/tests/Bug_3251_Regression/DllOrb.cpp
- TAO/tests/Bug_3542_Regression/DllOrb.cpp
- TAO/tests/Oneway_Send_Timeouts/Client_Task.h
- TAO/tests/Oneway_Send_Timeouts/main.cpp
* TAO/tests/Bug_3251_Regression/DllOrb.cpp:
* TAO/tests/Bug_3542_Regression/DllOrb.cpp:
* TAO/tests/Oneway_Send_Timeouts/Client_Task.h:
* TAO/tests/Oneway_Send_Timeouts/main.cpp:
> Fixed compile errors due to auto_ptr to unqiue_ptr changes

- TAO/tests/Oneway_Send_Timeouts/Server_Task.h
- TAO/tests/Oneway_Send_Timeouts/main.cpp
* TAO/tests/Oneway_Send_Timeouts/Server_Task.h:
* TAO/tests/Oneway_Send_Timeouts/main.cpp:
> Fixed compile errors with C++11

- TAO/orbsvcs/performance-tests/RTEvent/lib/Control.cpp
- TAO/orbsvcs/performance-tests/RTEvent/lib/RTClient_Setup.cpp
- TAO/orbsvcs/performance-tests/RTEvent/lib/RTClient_Setup.h
- TAO/orbsvcs/performance-tests/RTEvent/lib/RTEC_Initializer.cpp
- TAO/orbsvcs/performance-tests/RTEvent/lib/RTServer_Setup.cpp
- TAO/orbsvcs/performance-tests/RTEvent/lib/RTServer_Setup.h
- TAO/orbsvcs/tests/FtRtEvent/consumer.cpp
- TAO/orbsvcs/tests/FtRtEvent/supplier.cpp
- TAO/orbsvcs/tests/Trading/colocated_test.cpp
* TAO/orbsvcs/performance-tests/RTEvent/lib/Control.cpp:
* TAO/orbsvcs/performance-tests/RTEvent/lib/RTClient_Setup.cpp:
* TAO/orbsvcs/performance-tests/RTEvent/lib/RTClient_Setup.h:
* TAO/orbsvcs/performance-tests/RTEvent/lib/RTEC_Initializer.cpp:
* TAO/orbsvcs/performance-tests/RTEvent/lib/RTServer_Setup.cpp:
* TAO/orbsvcs/performance-tests/RTEvent/lib/RTServer_Setup.h:
* TAO/orbsvcs/tests/FtRtEvent/consumer.cpp:
* TAO/orbsvcs/tests/FtRtEvent/supplier.cpp:
* TAO/orbsvcs/tests/Trading/colocated_test.cpp:
> Replace auto_ptr with std::unique_ptr and fixed missing break

- TAO/TAO_IDL/ast/ast_union_branch.cpp
- TAO/tests/IDLv4/annotations/annotation_tests.cpp
see issue #1550 for detailed description of the issue. 
Briefly, the IDL compiler incorrectly fails to evaluate union branch labels that serve as aliases of default cases.
> Fix for issue #1550 - empty case evaluation on unions with enum discriminators 

- ACE/ACEXML/common/ZipCharStream.cpp
- ACE/ace/OS_NS_signal.h
- ACE/ace/OS_NS_stdio.cpp
- ACE/ace/OS_TLI.h
- ACE/ace/SStringfwd.h
- ACE/ace/Stack_Trace.cpp
- ACE/tests/Bug_3709_Regression_Test.cpp
- ACE/tests/Compiler_Features_12_Test.cpp
- TAO/orbsvcs/orbsvcs/Security/SL2_SecurityManager.cpp
* ACE/ACEXML/common/ZipCharStream.cpp:
* ACE/ace/OS_NS_signal.h:
* ACE/ace/OS_NS_stdio.cpp:
* ACE/ace/OS_TLI.h:
* ACE/ace/SStringfwd.h:
* ACE/ace/Stack_Trace.cpp:
* ACE/tests/Bug_3709_Regression_Test.cpp:
* ACE/tests/Compiler_Features_12_Test.cpp:
* TAO/orbsvcs/orbsvcs/Security/SL2_SecurityManager.cpp:
> Removed workarounds for very old broken HP compilers

- ACE/tests/DLL_Test_Parent.h
* ACE/tests/DLL_Test_Parent.h:
> Fixed unused parameter warning

- ACE/include/makeinclude/platform_aix_g++.GNU
Build ACE by GCC on AIX 5.1 :
```bash
make optimize=1 inline=1 debug=0
```
**No debug info** is produced because `DCCFLAGS` is not set to `-g` , e.g.
```bash
g++ -maix64 -Wnon-virtual-dtor  -pthread -DACE_AIX_VERS=501 -maix64 -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -DACE_HAS_CUSTOM_EXPORT_MACROS=0   -I/home/like/src/dbackup3/feature/aix-xcoff/debug/rpm/build/ACE_TAO-build-ppc64-dbg -DACE_NO_INLINE -I.. -DACE_BUILD_DLL  -c  -o .shobj/ACE.o ACE.cpp
......
```
> Fix AIX g++ DCCFLAGS.

- ACE/include/makeinclude/platform_hpux_gcc.GNU
Build ACE by GCC on HP-UX 11.31 IA64 :
```bash
make optimize=0 inline=0 debug=1
```
**No debug info** is produced because `DCCFLAGS` is not set to `-g`
> Fix HP-UX g++ DCCFLAGS.

- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Server.cpp
- TAO/orbsvcs/orbsvcs/Naming/Naming_Server.cpp
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Server.cpp:
* TAO/orbsvcs/orbsvcs/Naming/Naming_Server.cpp:
> Fixed fallthrough warnings

- ACE/ace/config-macros.h
> Borland C++ is now always using clang based compilers

- TAO/tests/Bug_3940_Regression/README
- TAO/tests/Bug_3940_Regression/test.idl
* TAO/tests/Bug_3940_Regression/README:
* TAO/tests/Bug_3940_Regression/test.idl:
> Embarcadero C++ Builder can now handle this IDL file

- ACE/ace/Refcounted_Auto_Ptr.h
- ACE/ace/XML_Utils/XercesString.h
- TAO/orbsvcs/orbsvcs/AV/RTCP_Channel.cpp
- TAO/orbsvcs/orbsvcs/AV/RTCP_Packet.cpp
- TAO/utils/nslist/nslist.cpp
- TAO/utils/wxNamingViewer/wxNamingViewer.cpp
* ACE/ace/Refcounted_Auto_Ptr.h:
* ACE/ace/XML_Utils/XercesString.h:
* TAO/orbsvcs/orbsvcs/AV/RTCP_Channel.cpp:
* TAO/orbsvcs/orbsvcs/AV/RTCP_Packet.cpp:
* TAO/utils/nslist/nslist.cpp:
* TAO/utils/wxNamingViewer/wxNamingViewer.cpp:
> Removed old workarounds for bcc32

- TAO/NEWS
- TAO/TAO_IDL/driver/drv_preproc.cpp
- TAO/TAO_IDL/include/idl_defines.h
- TAO/TAO_IDL/include/idl_version.h
- TAO/TAO_IDL/util/idl_version.cpp
- TAO/tao/idl_features.h
- TAO/tao/orbconf.h
- TAO/tao/tao.mpc
- TAO/tests/IDLv4/anonymous_types/test.idl
- TAO/tests/IDLv4/explicit_ints/main.cpp
- TAO/tests/IDLv4/explicit_ints/test.idl
Get information about what the IDL compiler is capable of, similarly to the "version" standard header in C++.
In C++ it can be used like this if you want to be compatible with older versions of TAO:
```c++
#include "tao/orbconf.h"
#if defined TAO_HAS_IDL_FEATURES && TAO_HAS_IDL_FEATURES
// Use this macro if you are using something that's not the max possible
// version.
#endif
```
In IDL it can be used like this if you want to be compatible with older versions of TAO:
```c++
#if defined __TAO_IDL_FEATURES
#endif
```
> Header File for TAO_IDL Supported IDL Features

- TAO/NEWS
- TAO/TAO_IDL/driver/drv_preproc.cpp
- TAO/TAO_IDL/include/idl_defines.h
- TAO/TAO_IDL/include/idl_version.h
- TAO/TAO_IDL/util/idl_version.cpp
- TAO/tao/idl_features.h
- TAO/tao/orbconf.h
- TAO/tao/tao.mpc
- TAO/tests/IDLv4/anonymous_types/test.idl
- TAO/tests/IDLv4/explicit_ints/main.cpp
- TAO/tests/IDLv4/explicit_ints/test.idl
Backport of https://github.com/DOCGroup/ACE_TAO/pull/1621
Get information about what the IDL compiler is capable of, similarly to the "version" standard header in C++.
In C++ it can be used like this if you want to be compatible with older versions of TAO:
```c++
#include "tao/orbconf.h"
#if defined TAO_HAS_IDL_FEATURES && TAO_HAS_IDL_FEATURES
// Use this macro if you are using something that's not the max possible
// version.
#endif
```
In IDL it can be used like this if you want to be compatible with older
versions of TAO:
```c++
#if defined __TAO_IDL_FEATURES
#endif
```
> [ACE6] Header File for TAO_IDL Supported IDL Features

- TAO/TAO_IDL/driver/drv_preproc.cpp
This is a backport of https://github.com/DOCGroup/ACE_TAO/pull/1627
> [ACE6] Escape Double Quotes in tao_idl PP Args on Windows

- TAO/MPC/config/tao_idl_fe.mpb
Projects that use tao_idl_fe need TAO_ROOT on preprocessor include
path, due to the recent change to idl_defines.h including
idl_features.h from tao.
> Updated tao_idl_fe base project.

- TAO/MPC/config/tao_idl_fe.mpb
Projects that use tao_idl_fe need TAO_ROOT on preprocessor include
path, due to the recent change to idl_defines.h including
idl_features.h from tao.
> [ACE6] Updated tao_idl_fe base project

- .github/workflows/face.yml
- .github/workflows/linux.yml
- .github/workflows/macosx.yml
- .github/workflows/windows.yml
Problem:
When a single matrix build fails (say, for example, due to vcpkg errors), it cancels all other parallel matrix builds in the same job. This is unhelpful in most situations, as we'd still usually like to see the other test results.
Solution:
Disable the default 'fail fast' strategy for github actions to allow other matrix jobs to continue.
> [GitHub Actions] Disable fail-fast strategy for matrix builds

- ACE/ace/SOCK_Dgram.cpp
fixes #1637
also removed a preprocessor conditional that was redundant
> make_multicast_ifaddr: prevent buffer overrun from net_if

- ACE/ace/SOCK_Dgram.cpp
fixes #1637
also removed a preprocessor conditional that was redundant
(cherry picked from commit 06e2a14d2d98b2a18b50615f4c048cffd49b3bfd)
> [ACE 6] make_multicast_ifaddr: prevent buffer overrun from net_if

- ACE/ace/OS_NS_stdlib.h
- ACE/ace/OS_NS_stdlib.inl
- ACE/ace/config-win32-borland.h
* ACE/ace/OS_NS_stdlib.h:
* ACE/ace/OS_NS_stdlib.inl:
> Don't check for ACE_LACKS_STRTOD, not set by any config file

- ACE/ace/Compression/rle/RLECompressor.cpp
- ACE/ace/post.h
- ACE/ace/pre.h
- TAO/orbsvcs/orbsvcs/Notify/MonitorControlExt/MC_Default_Factory.h
- TAO/orbsvcs/orbsvcs/Notify/RT_Factory.h
- TAO/orbsvcs/tests/Notify/Bug_3252_Regression/server.cpp
- TAO/tests/Bug_3574_Regression/test.cpp
* TAO/orbsvcs/orbsvcs/Notify/MonitorControlExt/MC_Default_Factory.h:
* TAO/orbsvcs/orbsvcs/Notify/RT_Factory.h:
* TAO/orbsvcs/tests/Notify/Bug_3252_Regression/server.cpp:
* TAO/tests/Bug_3574_Regression/test.cpp:
> Cleanup old Embarcadero compiler checks

- .github/workflows/macosx.yml
- ACE/include/makeinclude/platform_macosx.GNU
- ACE/include/makeinclude/platform_macosx_bigsur.GNU
- ACE/include/makeinclude/platform_macosx_catalina.GNU
Problem
-------
ACE 6 doesn't compile for macOS Big Sur.
Solution
--------
Update platform_macosx.GNU and related files to support Catalina and
Big Sur.
> ACE 6 doesn't support Big Sur

- ACE/ace/Atomic_Op_GCC_T.inl
Problem: ACE_Atomic_Op_GCC_T currently only uses the older __sync style atomic operations, which don't allow for memory ordering, meaning that they often enforce stricter-than-necessary memory barriers in order to achieve synchronization. The `__sync_synchronize()` builtin also isn't supported by clang and GCC's ThreadSanitizer feature, meaning that newer compilers will get false-positive reports of data races when using -fsanitize. ACE_Atomic_Op_GCC_T also appears to be missing load-side synchronization (via `__sync_synchronize()`).
Solution: Update ACE_Atomic_Op_GCC_T's load-side synchronization to use `__sync_synchronize()` and add support for __atomic builtins for GCC versions new enough to support them.
> [ACE6] Update ACE_Atomic_Op_GCC to support newer __atomic operations when available

- ACE/ace/Atomic_Op_GCC_T.inl
See PR #1664 . Same thing, but without CPP11 qualifications due to ACE7.
> Update ACE_Atomic_Op_GCC to use newer __atomic operations

- TAO/orbsvcs/DevGuideExamples/NotifyService/EventSequence/Messenger_i.h
- TAO/orbsvcs/DevGuideExamples/NotifyService/EventSequence/README
- TAO/orbsvcs/examples/FaultTolerance/RolyPoly/ReplicaController.cpp
- TAO/orbsvcs/examples/FaultTolerance/RolyPoly/ReplicaController.h
- TAO/orbsvcs/examples/FaultTolerance/RolyPoly/RolyPoly_i.cpp
- TAO/orbsvcs/examples/FaultTolerance/RolyPoly/RolyPoly_i.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Server.cpp
- TAO/orbsvcs/orbsvcs/Property/CosPropertyService_i.cpp
- TAO/orbsvcs/performance-tests/RTEvent/lib/Low_Priority_Setup.h
* TAO/orbsvcs/DevGuideExamples/NotifyService/EventSequence/Messenger_i.h:
* TAO/orbsvcs/DevGuideExamples/NotifyService/EventSequence/README:
* TAO/orbsvcs/examples/FaultTolerance/RolyPoly/ReplicaController.cpp:
* TAO/orbsvcs/examples/FaultTolerance/RolyPoly/ReplicaController.h:
* TAO/orbsvcs/examples/FaultTolerance/RolyPoly/RolyPoly_i.cpp:
* TAO/orbsvcs/examples/FaultTolerance/RolyPoly/RolyPoly_i.h:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Server.cpp:
* TAO/orbsvcs/orbsvcs/Property/CosPropertyService_i.cpp:
* TAO/orbsvcs/performance-tests/RTEvent/lib/Low_Priority_Setup.h:
> Fix auto_ptr and fallthrough warnings

- TAO/tests/Bug_1676_Regression/Test.idl
- TAO/tests/Bug_3524_Regression/README
- TAO/tests/Bug_3524_Regression/test.idl
* TAO/tests/Bug_1676_Regression/Test.idl:
* TAO/tests/Bug_3524_Regression/README:
* TAO/tests/Bug_3524_Regression/test.idl:
> Include tao/StringSeq.pidl to fix duplicate symbols with msvc

- ACE/ace/Handle_Set.h
- ACE/ace/Handle_Set.inl
GCC 11:
```
ace/Select_Reactor_T.cpp:1496:18: warning: implicitly-declared 'constexpr ACE_Handle_Set::ACE_Handle_Set(const ACE_Handle_Set&)' is deprecated [-Wdeprecated-copy]
ace/Handle_Set.inl:31:1: note: because 'ACE_Handle_Set' has user-provided 'ACE_Handle_Set& ACE_Handle_Set::operator=(const ACE_Handle_Set&)'
```
Not a problem for ACE 7
> [ACE 6] Fixed warnings related to Handle_Set's copy constructor

- TAO/tao/SystemException.h
All classes defined in libTAO should use the same export macro.
This avoids MSVC creating import libs for all executables that use
libTAO -- see https://github.com/DOCGroup/MPC/issues/130 and
https://github.com/microsoft/vcpkg/issues/16551
> SystemExceptions shouldn't use a different export

- TAO/orbsvcs/orbsvcs/Notify/Property_T.cpp
The "make install" tree doesn't have two orbsvcs directories
> Notify svc: Fixed include

- TAO/tao/SystemException.h
All classes defined in libTAO should use the same export macro.
This avoids MSVC creating import libs for all executables that use
libTAO -- see https://github.com/DOCGroup/MPC/issues/130 and
https://github.com/microsoft/vcpkg/issues/16551
(cherry picked from commit 0f879fd3f8a6e4d0b1762bd6c1424af735813ccc)
> [TAO 2] SystemExceptions shouldn't use a different export

- TAO/orbsvcs/orbsvcs/Notify/Property_T.cpp
The "make install" tree doesn't have two orbsvcs directories
(cherry picked from commit 026a87c8d9d1ce03c09d77e8c1fb99eb7d6af666)
> [TAO 2] Notify svc: Fixed include

- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Manager.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Server.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Group_Factory.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Group_Factory.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Object_Group_Storable.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Object_Group_Storable.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Persistent_Naming_Context.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Persistent_Naming_Context.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Persistent_Naming_Context_Factory.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Persistent_Naming_Context_Factory.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Random.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Random.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Round_Robin.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Round_Robin.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context_Factory.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context_Factory.h
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/nsgroup_svc.cpp
- TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/nsgroup_svc.h
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Manager.h:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Naming_Server.h:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Group_Factory.cpp:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Group_Factory.h:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Object_Group_Storable.cpp:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_PG_Object_Group_Storable.h:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Persistent_Naming_Context.cpp:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Persistent_Naming_Context.h:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Persistent_Naming_Context_Factory.cpp:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Persistent_Naming_Context_Factory.h:
* TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Random.cpp:
* …
> Fixed g++ warning, use override/default

- ACE/include/makeinclude/platform_macosx.GNU
- ACE/include/makeinclude/platform_macosx_monterey.GNU
Added support for compiling on MacOS Monterey, Intel architecture using clang.
> Support for MacOS 10.12 Monterey - Intel build.

- ACE/bin/DependencyGenerator/GNUIDLObjectGenerator.pm
tao_idl dir/file.idl doesn't put its output in dir by default
The ObjectGenerator perl module doesn't know about the -o option to tao_idl
The base filename may work anyway due to VPATH
> depgen for IDL: remove assumption about IDL files in subdirs

- ACE/bin/DependencyGenerator/GNUIDLObjectGenerator.pm
tao_idl dir/file.idl doesn't put its output in dir by default
The ObjectGenerator perl module doesn't know about the -o option to tao_idl
The base filename may work anyway due to VPATH
(cherry picked from commit 5edb3f8c49de9b98900bcc03ba5e0500fcc020db)
> [TAO 2] depgen for IDL: remove assumption about IDL files in subdirs

- TAO/tao/Cleanup_Func_Registry.h
- TAO/tao/Cleanup_Func_Registry.inl
- TAO/tao/Client_Strategy_Factory.h
- TAO/tao/Codeset/Codeset.h
- TAO/tao/Codeset/Codeset_Manager_i.cpp
- TAO/tao/Codeset/Codeset_Manager_i.h
- TAO/tao/Codeset/Codeset_Service_Context_Handler.h
- TAO/tao/Codeset/Codeset_Translator_Factory.cpp
- TAO/tao/Codeset/Codeset_Translator_Factory.h
- TAO/tao/Codeset/Codeset_Translator_Factory_T.cpp
- TAO/tao/Codeset/Codeset_Translator_Factory_T.h
- TAO/tao/Codeset/UTF16_BOM_Factory.cpp
- TAO/tao/Codeset/UTF16_BOM_Factory.h
- TAO/tao/Codeset/UTF16_BOM_Translator.cpp
- TAO/tao/Codeset/UTF16_BOM_Translator.h
- TAO/tao/Codeset/UTF8_Latin1_Factory.cpp
- TAO/tao/Codeset/UTF8_Latin1_Factory.h
- TAO/tao/Codeset/UTF8_Latin1_Translator.cpp
- TAO/tao/Codeset/UTF8_Latin1_Translator.h
- TAO/tao/Codeset_Manager.h
- TAO/tao/Codeset_Manager_Factory_Base.cpp
- TAO/tao/Codeset_Manager_Factory_Base.h
* TAO/tao/Codeset/Codeset_Manager_i.cpp:
* TAO/tao/Codeset/Codeset_Manager_i.h:
* TAO/tao/Codeset/Codeset_Service_Context_Handler.h:
* TAO/tao/Codeset/Codeset_Translator_Factory.cpp:
* TAO/tao/Codeset/Codeset_Translator_Factory.h:
* TAO/tao/Codeset/Codeset_Translator_Factory_T.cpp:
* TAO/tao/Codeset/Codeset_Translator_Factory_T.h:
* TAO/tao/Codeset/UTF16_BOM_Factory.cpp:
* TAO/tao/Codeset/UTF16_BOM_Factory.h:
* TAO/tao/Codeset/UTF16_BOM_Translator.cpp:
* TAO/tao/Codeset/UTF16_BOM_Translator.h:
* TAO/tao/Codeset/UTF8_Latin1_Factory.cpp:
* TAO/tao/Codeset/UTF8_Latin1_Factory.h:
* TAO/tao/Codeset/UTF8_Latin1_Translator.cpp:
* TAO/tao/Codeset/UTF8_Latin1_Translator.h:
> Make use of C++11 default and override

- TAO/TAO_IDL/driver/drv_args.cpp
- TAO/TAO_IDL/driver/drv_preproc.cpp
There is a problem with handling spaces in paths for TAO_IDL on Win32 systems.  This is due to the places where quotes are added leading to the elseif  in `DRV_cpp_putarg` which incorrectly escapes the quotes. This causes any spaces to not be properly handled.
> TAO_IDL: Fix Space In Path Handling

- TAO/TAO_IDL/driver/drv_preproc.cpp
This is a followup to the PR #1772 . 
The `first_quote` variable was unused outside of the `#ifdef ACE_WIN32`, so it was giving a warning on other systems. This PR resolves that by moving its declaration into the ifdef.
> TAO_IDL: Fix Space In Path Handling: Unused Variable Followup

- ACE/debian/changelog
- ACE/debian/control
- ACE/debian/copyright
- ACE/debian/libace-dev.install.in
Sync debian/* files for ACE as of Debian package 7.0.6+dfsg-2.
> Sync debian/* files for ACE

- TAO/NEWS
- TAO/TAO_IDL/driver/drv_preproc.cpp
1. The error message for failing to open an IDL file didn't have the filename in it. This was because the `ACE_ERROR` for it was using a `%m` when it looks like it used to use a `%p`. It looks like https://github.com/DOCGroup/ACE_TAO/pull/1420/commits/faab6830cf4ecf67b452183dba712caae7996be4 went one change too far.
2. First brought up here: https://github.com/objectcomputing/OpenDDS/issues/3308. Inputting a directory to tao_idl results in an empty file that causes a weird error latter. Changed it to ensure the file is a regular file using `fstat`.
> Fix tao_idl File Error Messages

- TAO/NEWS
- TAO/TAO_IDL/driver/drv_preproc.cpp
Backport of https://github.com/DOCGroup/ACE_TAO/pull/1783
1. The error message for failing to open an IDL file didn't have the filename in it. This was because the `ACE_ERROR` for it was using a `%m` when it should have been using a `%p`. It looks like https://github.com/DOCGroup/ACE_TAO/commit/faab6830cf4ecf67b452183dba712caae7996be4 went one change too far.
2. First brought up here: https://github.com/objectcomputing/OpenDDS/issues/3308 Inputting a directory to tao_idl results in an empty file that causes a weird error latter. Changed it to ensure the file is a regular file using `stat`.
> [TAO 2] Fix tao_idl File Error Messages

- ACE/ace/OS_NS_Thread.cpp
Fixes build error when ACE_LACKS_AUTO_PTR is defined. Auto_Ptr.h is also not longer required here.
Ref #1301
> Add missing memory include

- ACE/ace/Task_T.h
Note: this call should not be on a hot path
> make ACE_Task::flush virtual

- ACE/ace/SSL/SSL_Asynch_BIO.cpp
Fix the following build failure with libressl:
```
/home/autobuild/autobuild/instance-10/output-1/build/ace-7.0.6/ace/SSL/SSL_Asynch_BIO.cpp:174:7: error: 'BIO_get_init' was not declared in this scope; did you mean 'BIO_set_init'?
174 |   if (BIO_get_init(pBIO) == 0 || p_stream == 0 || buf == 0 || len <= 0)
|       ^~~~~~~~~~~~
|       BIO_set_init
```
Fixes:
- http://autobuild.buildroot.org/results/386afa88ac9e5e3bb65dddeabf610bb1e9bc4285
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> ACE/ace/SSL/SSL_Asynch_BIO.cpp: fix build with libressl

- ACE/ace/SSL/SSL_SOCK_Connector.h
support modifying the SSL connection context before ssl_connect() is called with it. Allows implementing support for e.g. TLS SNI.
> make ssl_connect() virtual

- ACE/ace/Atomic_Op.h
- ACE/ace/Atomic_Op.inl
- ACE/tests/Naming_Test.cpp
Resolves compile warning resulting from PR #1812
> Restore getpid() result cast to int.

- .github/workflows/face.yml
- .github/workflows/fuzz.yml
- .github/workflows/linux.yml
- .github/workflows/macosx.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- ACE/bin/MakeProjectCreator/templates/gnu.mpd
To prevent it from being created as a file when `make --touch` is used.
> gnuace: Mark `__postbuild__` Target as PHONY

- ACE/ace/Select_Reactor.h
This addresses issue in [ACE-TAO Issue #1889](https://github.com/DOCGroup/ACE_TAO/issues/1889)
> Fix syntax error when compiling without threads.

- ACE/tests/Enum_Interfaces_Test.cpp
- TAO/orbsvcs/DevGuideExamples/Security/SecurityUnawareApp/README
- TAO/orbsvcs/tests/Security/ssliop_corbaloc/client.cpp
- TAO/orbsvcs/tests/Security/ssliop_corbaloc/test_object.idl
* ACE/tests/Enum_Interfaces_Test.cpp:
* TAO/orbsvcs/DevGuideExamples/Security/SecurityUnawareApp/README:
* TAO/orbsvcs/tests/Security/ssliop_corbaloc/client.cpp:
* TAO/orbsvcs/tests/Security/ssliop_corbaloc/test_object.idl:
> Use override, remove redundant whitespacing, fixed typo

- ACE/ace/config-g++-common.h
GCC compiler prior to GCC7 don't understand `[[gnu::fallthrough]]` statement.
> Fix ACE_FALLTHROUGH definition for old GCC compilers.

- TAO/TAO_IDL/include/ast_annotation_appls.h
- interprocess mutexes are not needed
- support threads=0 builds of tao_idl
> Use ACE's Sync(h) traits in AST_Annotation_Appls

- ACE/bin/PerlACE/Process_Unix.pm
Commit e401f02ed7c5 broke compilation with Perl 5.8.8. This pull request fixes that to allow tests to run on scoreboard builds e.g.: https://tao.microfocus.com/scoreboard/rhel5_x86_noinline/index.html
> Fix a small part of commit e401f02ed7c5 which broke compilation

- ACE/include/makeinclude/platform_vxworks7.0.GNU
Added $(ACE_SHLIBS) to the link line for shared libraries.  This allows dlopen() to load in other dependency libraries.
Removed the -soname option from the link line so that shared libraries do not have a hard-coded path built into them.
> VxWorks Shared Libraries

- ACE/examples/OS/Process/imore.cpp
- ACE/examples/OS/Process/process.cpp
This fixes some build issues in the ACE examples after the merge of #1907
> Fix -Wformat-security issues in examples

- .github/workflows/macosx.yml
- ACE/ace/config-macosx-leopard.h
Problem: Build issues on macOS for setting standard to C++17 (and presumably c++20) due to lack of `std::auto_ptr`.
Solution: Be sure to set ACE_LACKS_AUTO_PTR when C++ standard 17 or greater is detected.
> C++17 or greater implies lack of std::auto_ptr

- ACE/ace/OS_NS_arpa_inet.inl
- ACE/ace/OS_NS_netdb.inl
- ACE/ace/os_include/os_unistd.h
* ACE/ace/OS_NS_arpa_inet.inl:
* ACE/ace/OS_NS_netdb.inl:
* ACE/ace/os_include/os_unistd.h:
> With VxWorks 7 the gethostbyname() API is not always reentrent

- ACE/ace/Pipe.cpp
Re-merged this one, since a 1-character change to Pipe.cpp was missed:
```
VxWorks 7 also has the support for a non-reentrant version of gethostbyaddr
(cherry picked from commit 1e84155d462e09d583a472c9fc70a06fa5d3054e)
```
> [ACE6] Merge pull request #1956 from jwillemsen/jwi-vxworksgethostbyaddr

- ACE/ace/Configuration.cpp
After pulling 0c2228f586a6c8fda87b707fcdaf2e861e118eff into ACE 6, the wide-character builds of OpenDDS built against ACE 6 began failing tests due to configuration errors.
After debugging, I found that the division by sizeof(ACE_TCHAR) was causing the substring calculation to be incorrect due to the fact that pointer arithmetic already accounts for the size of the indivdiual elements.  I have made the same change for ACE 6.
https://github.com/DOCGroup/ACE_TAO/pull/1991
> Correction for wide-char builds

- ACE/ace/Dirent.inl
- ACE/ace/OS_NS_dirent.cpp
- ACE/ace/OS_NS_dirent.h
- ACE/ace/OS_NS_dirent.inl
Only use `readdir` internally since `readdir_r` is deprecated.
This change will not apply to ACE 7, since readdir_r was removed.
> [ace6tao2] Allow disabling of ACE_OS::readdir_r

- TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_obv_ch.cpp
Based on https://github.com/DOCGroup/ACE_TAO/pull/2001
> Only emit the require_truncation_ boolean if CDR support is enabled.

- ACE/NEWS
- ACE/bin/copy-local-script.sh
- ACE/bin/diff-builds-and-group-fixed-tests-only.sh
- ACE/docs/Download.html
- ACE/etc/index.html
- TAO/NEWS
> Make ACE 7.0.11 and TAO 3.0.11 public available

- ACE/rpmbuild/ace-tao.spec
This includes stubs and skeletons for IDL interfaces and files required to extend interfaces. This is a superset of files which are known to be required to build external packages.
The current scheme for building the RPM uses dependencies from (some) built objects to deduce which files were required to be installed. But many other files are not in the core product but are required for external projects to use these components.
> Add headers and other source files to the list of files to be installed.

- ACE/ace/Shared_Memory_Pool.cpp
- ACE/ace/Shared_Memory_Pool.h
shm_addr_table_ needs to be initialized after max_segments_ is known
See #2077
> Shared_Memory_Pool: fixed construction with non-default max_segments_

- ACE/ace/INET_Addr.cpp
- ACE/tests/INET_Addr_Test.cpp
Problem
-------
Calling `set("1.2.3.4")` on an ACE_INET_Addr eventually tries to part it as a port name.  When `ACE_LACKS_GETSERVBYNAME`, this succeeds returning port number 0 with the reset address.
When port names are not expected, this breaks a useful idiom of parsing addresses that may or may not contain port numbers:
ACE_INET_Addr addr;
if (addr.set(x) == 0) {
// Success, address contained a port number
} else if (addr.set(u_short(0), x) == 0) {
// Success, address did not contain a port number.
} else {
// Fail
}
Solution
--------
Return -1 for the port number when `ACE_LACKS_GETSERVBYNAME`.
> `ACE_INET_Addr::set` errantly succeeds when ACE_LACKS_GETSERVBYNAME

- ACE/ace/INET_Addr.cpp
- ACE/tests/INET_Addr_Test.cpp
Merged #2080 to ace6tao2:
`ACE_INET_Addr::set` errantly succeeds when ACE_LACKS_GETSERVBYNAME
(cherry picked from commit a65d91cdc463e7cf6cf509138956b2d38c5e5727)
> [ACE 6] ACE_INET_Addr::set errantly succeeds when ACE_LACKS_GETSERVBYNAME

- ACE/ace/Auto_Ptr.h
- ACE/tests/Reactor_Remove_Resume_Test_Dev_Poll.cpp
- TAO/orbsvcs/orbsvcs/Event/ECG_CDR_Message_Receiver.cpp
- TAO/orbsvcs/orbsvcs/Notify/Refcountable.cpp
- TAO/tests/Any/Recursive/client.cpp
- TAO/tests/Bug_2804_Regression/client.cpp
- TAO/tests/Bug_2844_Regression/client.cpp
- TAO/tests/Bug_2918_Regression/client.cpp
- TAO/tests/Bug_3919_Regression/client.cpp
(deprecated in C++11) and removed in C++17
> Replace std::unary_function<> with std::function<>

- ACE/include/makeinclude/platform_g++_common.GNU
- ACE/include/makeinclude/platform_gcc_clang_common.GNU
- ACE/include/makeinclude/platform_linux_clang.GNU
- ACE/include/makeinclude/platform_linux_icc.GNU
- ACE/include/makeinclude/platform_qnx_gcc.GNU
* ACE/include/makeinclude/platform_g++_common.GNU:
> Removed gcc 4 workaround for C++11, we require C++14 as minimum

- .github/workflows/linux.yml
- ACE/NEWS
- ACE/include/makeinclude/platform_gcc_clang_common.GNU
* ACE/NEWS:
* ACE/include/makeinclude/platform_gcc_clang_common.GNU:
> Add support for c++std in platform_macros.GNU

- ACE/include/makeinclude/platform_linux_common.GNU
Scoreboard scripts parse these as errors
.: cannot open /usr/lib/tkConfig.sh: No such file
> platform_linux: avoid errors when tcl/tk packages are not installed

- ACE/include/makeinclude/platform_linux_common.GNU
platform_linux: avoid errors when tcl/tk packages are not installed
(cherry picked from commit 854bfeeb364bdad54ac3c600437392ca823274ce)
> [ACE6] platform_linux: avoid errors when tcl/tk packages are not installed

- ACE/ace/config-macosx-leopard.h
- ACE/ace/config-macosx-tiger.h
https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Handle-data-types-and-data-alignment-properly
> macOS: sizeof long double is different on ARM64

- ACE/ace/config-macosx-leopard.h
- ACE/ace/config-macosx-tiger.h
macOS: sizeof long double is different on ARM64
(cherry picked from commit 1affc2bd31c38b55cd0b11a5665055821890c541)
> [ACE6] macOS: sizeof long double is different on ARM64

- ACE/include/makeinclude/platform_gcc_clang_common.GNU
- ACE/include/makeinclude/platform_linux.GNU
* ACE/include/makeinclude/platform_linux.GNU:
> Removed work arounds for ancient compilers

- TAO/TAO_IDL/be/be_visitor_map/cdr_op_cs.cpp
- TAO/TAO_IDL/be/be_visitor_map/map_ch.cpp
- TAO/TAO_IDL/be/be_visitor_map/map_cs.cpp
- TAO/TAO_IDL/be_include/be_visitor_map/cdr_op_cs.h
- TAO/TAO_IDL/be_include/be_visitor_map/map_ch.h
- TAO/TAO_IDL/be_include/be_visitor_map/map_cs.h
I'm not sure how to fix these errors as they're generated by another visitor, https://tao.microfocus.com/scoreboard/rhel7_x64_dev/2023_10_26_20_43_Full.html#error_1
> More maps fixes

- ACE/ACE-INSTALL.html
- ACE/bin/install_proj.mk
- ACE/bin/install_proj.sh
Added a script install_proj.sh that can be used to run make install
(cherry picked from commit 58ea863f3a2e50b6a3045b59c7f1f060a8b7b5ae)
> [ACE 6] Added a script install_proj.sh that can be used to run make install

- ACE/ace/Barrier.cpp
- ACE/ace/Future.cpp
- ACE/ace/Future.h
- ACE/ace/Future_Set.cpp
- ACE/tests/Future_Stress_Test.cpp
- ACE/tests/run_test.lst
- ACE/tests/tests.mpc
Fixed a race condition caused by the double checked locking pattern by using an std::atomic that ensures correct and deterministic create and assignment logic.
Issue #2163
> Fixed a race condition caused by the double checked locking pattern

- ACE/ace/OS_NS_stdio.inl
> #2180 don't use invalid references of temporary objects - scan-build report

- ACE/ace/CDR_Base.cpp
Found this bug during development of OpenDDS/OpenDDS#4466
Existing test cases cover it, but need valgrind/asan to report the error
> [ACE 6] Avoid potential out-of-bounds read in ACE_CDR::Fixed::from_string

- ACE/ace/Configuration.h
- ACE/protocols/tests/HTBP/Reactor_Tests/test_config.h
- ACE/tests/Test_Output.cpp
- TAO/orbsvcs/tests/HTIOP/AMI/Test_Output.cpp
- TAO/orbsvcs/tests/HTIOP/BiDirectional/Test_Output.cpp
- TAO/orbsvcs/tests/HTIOP/Hello/Test_Output.cpp
- TAO/tao/PI/PICurrent_Impl.cpp
- TAO/tests/POA/FindPOA/FindPOA.cpp
* ACE/ace/Configuration.h:
* ACE/protocols/tests/HTBP/Reactor_Tests/test_config.h:
* ACE/tests/Test_Output.cpp:
* TAO/orbsvcs/tests/HTIOP/AMI/Test_Output.cpp:
* TAO/orbsvcs/tests/HTIOP/BiDirectional/Test_Output.cpp:
* TAO/orbsvcs/tests/HTIOP/Hello/Test_Output.cpp:
* TAO/tao/PI/PICurrent_Impl.cpp:
* TAO/tests/POA/FindPOA/FindPOA.cpp:
> Fixed typos

- ACE/protocols/ace/INet/URLBase.cpp
* ACE/protocols/ace/INet/URLBase.cpp:
> Use a variable on the stack to not have a temporary in the call

- ACE/include/makeinclude/platform_g++_common.GNU
* ACE/include/makeinclude/platform_g++_common.GNU:
> Check for full match with major version

- ACE/protocols/ace/INet/URLBase.cpp
> Revert "Use a variable on the stack to not have a temporary in the call"

- .github/workflows/cmake.yml
- .github/workflows/linux.yml
- ACE/NEWS
- ACE/ace/Global_Macros.h
- ACE/ace/checked_iterator.h
- ACE/bin/MakeProjectCreator/config/acedefaults.mpb
- ACE/bin/MakeProjectCreator/config/vc_warnings.mpb
- ACE/bin/MakeProjectCreator/config/vs2017nmake.mpb
- ACE/bin/MakeProjectCreator/config/vs2019nmake.mpb
- ACE/bin/MakeProjectCreator/config/vs2022nmake.mpb
- ACE/include/makeinclude/platform_gcc_clang_common.GNU
- ACE/include/makeinclude/platform_linux_clang.GNU
- ACE/include/makeinclude/platform_macosx_common.GNU
- TAO/NEWS
- TAO/tests/Oneway_Send_Timeouts/Server_Task.h
- TAO/tests/Oneway_Send_Timeouts/main.cpp
Includes changes to set the C++ compiler default for Visual Studio 2017/2019/2022 to C++17
> C++17 is the minimum required C++ level to compile ACE/TAO after this PR

- ACE/bin/MakeProjectCreator/config/acedefaults.mpb
Don't add iphlpapi to lit_libs for any compiler on windows, with bmake we don't need that
> Introduce platform_libs which is used for bmake

- ACE/ace/config-g++-common.h
- ACE/ace/config-macros.h
* ACE/ace/config-g++-common.h:
* ACE/ace/config-macros.h:
> Define ACE_DEPRECATED as [[deprecated]]

- TAO/TAO-INSTALL.html
In section `Building and Installing TAO from git`, if I execute the given command for
`Build ACE+TAO together in one shot`, I get
```
ERROR: There is no longer a default project type.
Please specify one in MPC.cfg or use the -type option.
```
Adding the missing `-type gnuace` solves the problem.
> TAO/TAO-INSTALL.html : Fix "Building and Installing TAO from git"

- ACE/ace/config-macosx.h
Building ACE 8.0.0 on Mac OS X 10.6 fails:
```
../ace/config-macosx.h:32:2: error: Cannot detect MacOSX version
#error Cannot detect MacOSX version
^
```
because you are using the wrong `__MAC_OS_X_VERSION_MAX_ALLOWED` values for SDK versions earlier than 10.10. This PR fixes it. It also clarifies the error message: `__MAC_OS_X_VERSION_MAX_ALLOWED` represents the version of the SDK, not the version of macOS currently being used on the build machine nor the minimum version of macOS that will be required to run the compiled program. (The latter would be the deployment target.)
> Fix detection of MacOSX SDKs older than 10.10

- ACE/bin/MakeProjectCreator/config/acedefaults.mpb
…FIER is now set by MPC
* ACE/bin/MakeProjectCreator/config/acedefaults.mpb:
> [ace6tao2] MPC_LIB_MODIFIER is now set by MPC for bmake

- ACE/protocols/ace/INet/HTTPS_Context.h
- ACE/protocols/ace/INet/HTTP_Status.h
- ACE/protocols/ace/INet/URLBase.cpp
- ACE/protocols/ace/INet/URLBase.h
- TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/Dynamic_Bitset.h
* ACE/protocols/ace/INet/HTTPS_Context.h:
* ACE/protocols/ace/INet/HTTP_Status.h:
* ACE/protocols/ace/INet/URLBase.cpp:
* ACE/protocols/ace/INet/URLBase.h:
* TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/Dynamic_Bitset.h:
> Mark operator bool as explicit

- ACE/ace/CDR_Size.h
- ACE/ace/CDR_Size.inl
- ACE/ace/CDR_Stream.h
- ACE/ace/CDR_Stream.inl
- ACE/tests/CDR_Test.cpp
- TAO/tao/CDR.h
- TAO/tao/CDR.inl
* ACE/ace/CDR_Size.h:
* ACE/ace/CDR_Size.inl:
* ACE/ace/CDR_Stream.h:
* ACE/ace/CDR_Stream.inl:
* ACE/tests/CDR_Test.cpp:
* TAO/tao/CDR.h:
* TAO/tao/CDR.inl:
> Extended output CDR classes to serialize a std::string_view directly

- ACE/ace/config-g++-common.h
- ACE/ace/config-win32-borland.h
- ACE/ace/config-win32-msvc-142.h
* ACE/ace/config-g++-common.h:
* ACE/ace/config-win32-msvc-142.h:
> Define ACE_HAS_CPP23 when we have C++23 support

- .github/workflows/linux-container.yml
- ACE/ace/Dev_Poll_Reactor.cpp
- ACE/ace/config-linux.h
- ACE/ace/os_include/sys/os_types.h
Based on #1072 from @drandreas with help from the patch attached to #914
> Port to Linux platforms that use musl-libc instead of glibc

- .github/workflows/linux-container.yml
- ACE/ace/Dev_Poll_Reactor.cpp
- ACE/ace/config-linux.h
- ACE/ace/os_include/sys/os_types.h
Port to Linux platforms that use musl-libc instead of glibc
(cherry picked from commit caeb54519f2a0017cb10a96b0855c8c974ff14b6)
Conflicts:
ACE/ace/os_include/sys/os_types.h
> [ACE 6] Port to Linux platforms that use musl-libc instead of glibc

- ACE/rpmbuild/ace-tao.spec
Adding -std=c++17 to avoid header compilation failure which removes them from the list of headers.
Fixing #2286 - tested on openSUSE15.6 with gcc 7.5 compiler which is not c++17 or newer by default.
The explanation for working with g++ 14.2 (on openSUSE Tumbleweed) is that the compiler is by default c++17 while g++ 7.5 is c++14 even if the compiler is capable of handling c++17 specs - which is actually used in compilation.
> fix for #2286 - avoid header compilation failure in %install phase

- TAO/ChangeLogs/ChangeLog-2012a
- TAO/examples/OBV/Typed_Events/Event_Types_impl.cpp
- TAO/orbsvcs/orbsvcs/LoadBalancing/LB_ObjectReferenceFactory.cpp
- TAO/tao/DynamicAny/DynValue_i.h
- TAO/tao/Valuetype/ValueBase.cpp
It was a warning when running lintian when making an OpenDDS deb file.
I: opendds: spelling-error-in-binary usr/lib/libTAO_IDL_FE.so.2.5.21 explictly explicitly
I: opendds: spelling-error-in-binary usr/lib/libTAO_Valuetype.so.2.5.21 implimented implemented
> spelling: changed implImented to implEmented

- TAO/ChangeLogs/ChangeLog-2004a
- TAO/TAO_IDL/util/utl_err.cpp
It was a warning when running lintian when making an OpenDDS deb file.
I: opendds: spelling-error-in-binary usr/lib/libTAO_IDL_FE.so.2.5.21 explictly explicitly
@jwillemsen It's probably better to rebase this with the previous commit
> spelling: changed 'explictly' to 'explicitly'

- ACE/ace/ace.mpc
- ACE/ace/ace_for_tao.mpc
On release version Log_Msg_Backend.h and Log_Msg_Callback.h missed after building.
> fix missed headers in linux build

- TAO/TAO_IDL/be/be_interface.cpp
- TAO/TAO_IDL/be/be_visitor_interface/amh_ss.cpp
- TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp
- TAO/tao/Bounded_Array_Sequence_T.h
- TAO/tao/Unbounded_Array_Sequence_T.h
These warnings impact downstream projects since they're in headers and generated code.
> Fixed some warnings

- TAO/TAO_IDL/be/be_interface.cpp
- TAO/TAO_IDL/be/be_visitor_interface/interface_ih.cpp
- TAO/TAO_IDL/be/be_visitor_interface/interface_is.cpp
- TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp
- TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp
- TAO/TAO_IDL/be_include/be_interface.h
- TAO/TAO_IDL/be_include/be_visitor_interface/interface_ss.h
Fixes additional warnings introduced in #2306
> Use =default for skeleton copy constructor

- TAO/TAO_IDL/be/be_interface.cpp
- TAO/TAO_IDL/be/be_visitor_interface/amh_ss.cpp
- TAO/TAO_IDL/be/be_visitor_interface/interface_ih.cpp
- TAO/TAO_IDL/be/be_visitor_interface/interface_is.cpp
- TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp
- TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp
- TAO/tao/Bounded_Array_Sequence_T.h
- TAO/tao/Unbounded_Array_Sequence_T.h
Fixed some warnings (backported #2306)
(cherry picked from commit 59970076e15259aa0dd180297343f8a24298894a)
> [ACE6_TAO2] Fixed some warnings

- TAO/orbsvcs/orbsvcs/CosEvent/CEC_TypedEventChannel.cpp
* TAO/orbsvcs/orbsvcs/CosEvent/CEC_TypedEventChannel.cpp:
> ACE_DEBUG uses %C for ascii strings, not %s

- ACE/NEWS
- ACE/ace/OS_NS_Thread.cpp
- ACE/ace/OS_NS_Thread.h
- ACE/ace/OS_NS_Thread.inl
- ACE/ace/Sock_Connect.cpp
- ACE/ace/Stack_Trace.cpp
- ACE/ace/Thread.cpp
- ACE/ace/Thread.h
- ACE/ace/Thread.inl
- ACE/ace/Thread_Manager.cpp
- ACE/ace/Thread_Manager.h
- TAO/NEWS
- TAO/tao/Acceptor_Impl.cpp
- TAO/tao/GIOP_Message_Base.cpp
- TAO/tao/ORB_Core.cpp
- TAO/tao/Stub.inl
- TAO/tao/Thread_Per_Connection_Handler.cpp
- TAO/tao/Thread_Per_Connection_Handler.h
- TAO/tao/Transport.cpp
```
Support thread names on Windows; name the threads that TAO creates
Fixed some other warnings / code cleanup along the way
(cherry picked from commit e3b027b753b21daf35682d34a1f0f1f4c7af40ff)
#	ACE/NEWS
#	ACE/ace/OS_NS_Thread.cpp
#	ACE/ace/OS_NS_Thread.inl
#	ACE/ace/Sock_Connect.cpp
#	ACE/ace/config-integrity-common.h
#	TAO/NEWS
#	TAO/tao/ORB_Core.cpp
#	TAO/tao/Thread_Per_Connection_Handler.cpp
```
> [ACE6-TAO2] Support thread names on Windows; name the threads that TAO creates

- TAO/tests/DynValue_Test/Analyzer.cpp
* TAO/tests/DynValue_Test/Analyzer.cpp:
> Fixed compiler warning about misleading indent

- .github/workflows/windows.yml
- ACE/tests/Bug_2540_Regression_Test.cpp
- ACE/tests/Bug_2820_Regression_Test.cpp
- TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Endpoint.cpp
Updates for Visual C++ CI and C++20 compatibility
> [ACE 6 - TAO 2] Updates for Visual C++ CI and C++20 compatibility

- ACE/NEWS
- ACE/ace/Log_Msg_Android_Logcat.cpp
Backport of https://github.com/DOCGroup/ACE_TAO/pull/2416
> [ace6tao2] Fixed building ACE for Android with `uses_wchar=1`
