ACE/NEWS, ACE/ace/INET_Addr.cpp, ACE/ace/INET_Addr.h, ACE/ace/INET_Addr.inl, ACE/ace/Multihomed_INET_Addr.cpp, ACE/tests/INET_Addr_Test.cpp
Fixed problems detected after previous pull for this branch.
=> Add ability for ACE_INET_Addr to hold all the addresses assigned to a name

.travis.yml
=> Enable IPv6 by default for travis-ci build

TAO/MPC/config/taobaseidldefaults.mpb
* TAO/MPC/config/taobaseidldefaults.mpb:
=> Reverted last change regarding the source_outputext.

TAO/tao/IIOP_Endpoint.cpp
both IPv4 and IPv6 with prefer IPv6 set and trouble reaching the
server.
=> Fix for evaluating profiles that have multiple endpoints including

ACE/tests/Chrono_Test.cpp
=> Added missing include for Truncate

CIAO/NEWS
=> Mention Shapes interop fixes

TAO/tao/AnyTypeCode/Recursive_Type_TypeCode.cpp
* TAO/tao/AnyTypeCode/Recursive_Type_TypeCode.cpp:
=> Don't use global CORBA scope

TAO/utils/logWalker/GIOP_Buffer.cpp, TAO/utils/logWalker/GIOP_Buffer.h, TAO/utils/logWalker/Log.cpp, TAO/utils/logWalker/Log.h, TAO/utils/logWalker/PeerProcess.cpp, TAO/utils/logWalker/Session.cpp, TAO/utils/logWalker/Thread.cpp
Improve processing of old TAO logs.fix output errors, fix parsing heavily threaded, RW strategy based logs.
=> log walker updates

ACE/NEWS, ACE/bin/make_release.py
=> Package vc12 and vc14 solutions

ACE/bin/MakeProjectCreator/config/vc14nmake.mpb, ACE/bin/MakeProjectCreator/config/vc9nmake.mpb
* ACE/bin/MakeProjectCreator/config/vc14nmake.mpb:
* ACE/bin/MakeProjectCreator/config/vc9nmake.mpb:
=> Use add_compile instead of addcompile

ACE/ace/Task.cpp, ACE/tests/Task_Group_Test.cpp, ACE/tests/run_test.lst, ACE/tests/tests.mpc
=> Changes for more consistent grp_id handling in ACE tasks

ACE/apps/gperf/src/List_Node.cpp
* ACE/apps/gperf/src/List_Node.cpp:
=> Fixed missing include

ACE/ace/OS_NS_sys_utsname.cpp, ACE/ace/Object_Manager_Base.cpp
* ACE/ace/OS_NS_sys_utsname.cpp:
* ACE/ace/Object_Manager_Base.cpp:
=> Fix incorrect MSVC pragma warning format.

TAO/tao/Dynamic_TP/DTP_Task.cpp
* TAO/tao/Dynamic_TP/DTP_Task.cpp:
=> Fix integer signedness comparison warning.

ACE/NEWS
=> Updated news file

CIAO/NEWS
=> Added mention of NDDSSCRIPTDIR

CIAO/MPC/config/ndds_idltocpp_ts_defaults.mpb
* CIAO/MPC/config/ndds_idltocpp_ts_defaults.mpb:
=> Removed verbatim section, that is already done in the ndds base projects

ACE/tests/Compiler_Features_27_Test.cpp
* ACE/tests/Compiler_Features_27_Test.cpp:
=> Removed workaround for msvc14 RC

.travis.yml
=> Use modern way of installing the additinal packages we need

TAO/tao/Compression/Compressor_Factory.h, TAO/tao/DynamicInterface/DII_Reply_Handler.h, TAO/tao/TransportCurrent/Current_ORBInitializer_Base.h
* TAO/tao/Compression/Compressor_Factory.h:
* TAO/tao/DynamicInterface/DII_Reply_Handler.h:
* TAO/tao/TransportCurrent/Current_ORBInitializer_Base.h:
=> Updated comment

TAO/orbsvcs/ImplRepo_Service/AsyncAccessManager.cpp, TAO/orbsvcs/ImplRepo_Service/Forwarder.cpp, TAO/orbsvcs/ImplRepo_Service/ImR_Activator_i.cpp, TAO/orbsvcs/ImplRepo_Service/ImR_Locator.cpp, TAO/orbsvcs/ImplRepo_Service/ImR_Locator.idl, TAO/orbsvcs/ImplRepo_Service/ImR_Locator_i.cpp, TAO/orbsvcs/ImplRepo_Service/ImR_Locator_i.h, TAO/orbsvcs/ImplRepo_Service/ImplRepo_Service.mpc, TAO/orbsvcs/ImplRepo_Service/Locator_Options.cpp, TAO/orbsvcs/ImplRepo_Service/Locator_Options.h, TAO/orbsvcs/ImplRepo_Service/Locator_Repository.cpp, TAO/orbsvcs/ImplRepo_Service/Locator_Repository.h, TAO/orbsvcs/ImplRepo_Service/Replicator.cpp, TAO/orbsvcs/ImplRepo_Service/Replicator.h, TAO/orbsvcs/ImplRepo_Service/Shared_Backing_Store.cpp, TAO/orbsvcs/ImplRepo_Service/Shared_Backing_Store.h, TAO/orbsvcs/ImplRepo_Service/UpdateableServerInfo.cpp, TAO/orbsvcs/ImplRepo_Service/UpdateableServerInfo.h, TAO/orbsvcs/ImplRepo_Service/XML_Backing_Store.cpp, TAO/orbsvcs/ImplRepo_Service/tao_imr_i.cpp, TAO/orbsvcs/ImplRepo_Service/tao_imr_i.h, TAO/orbsvcs/tests/ImplRepo/MT_stress/MT_stress.mpc, TAO/orbsvcs/tests/ImplRepo/MT_stress/client.conf, TAO/orbsvcs/tests/ImplRepo/MT_stress/client.cpp, TAO/orbsvcs/tests/ImplRepo/MT_stress/run_test_ft.pl, TAO/orbsvcs/tests/ImplRepo/MT_stress/server.cpp, TAO/orbsvcs/tests/ImplRepo/MT_stress/server_i.cpp, TAO/orbsvcs/tests/ImplRepo/MT_stress/server_i.h, TAO/orbsvcs/tests/ImplRepo/MT_stress/test.idl
addresses the case where a heavy load of 100s of requests cause the ft peer updating to fall behind, leading to problems.
=> multithreaded FT ImR improving heavy load performance

ACE/bin/fuzz.pl
We are using GIT for opendds, but still on SVN for ACE/TAO so I made the script work for both.  A quick modification later can remove SVN once we move ACE/TAO to git.
=> make fuzz.pl -m work for GIT repos also

ACE/ace/Cached_Connect_Strategy_T.cpp, ACE/tests/Cached_Conn_Strategy_Fail_Test.cpp, ACE/tests/run_test.lst, ACE/tests/tests.mpc
ACE_Cached_Connect_Strategy_T::cached_connect timeout but still return 0.
=> Fix connecting timeout without returning -1 in ACE_Cached_Connect_Strategy_T

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, CIAO/NEWS, DAnCE/NEWS, TAO/NEWS
* ACE/NEWS:
* CIAO/NEWS:
* DAnCE/NEWS:
* TAO/NEWS:
=> Make x.3.3 public available and prepare for the next release

ACE/bin/make_release.py, ACE/debian/README.source, ACE/debian/watch, ACE/rpmbuild/README, ACE/rpmbuild/ace-tao.spec
This package contains only ACE and TAO.
=> Removed references to CIAO and DAnCE.

ACE/ace/INET_Addr.cpp, ACE/ace/Message_Queue_T.cpp, ACE/ace/OS_NS_stdio.cpp, ACE/ace/Sock_Connect.cpp, ACE/tests/Sigset_Ops_Test.cpp
Follow-on work from pull request #159
=> Fixed compiler warnings on multiple platforms

appveyor.yml
=> Upgrade to msvc14

TAO/tao/DynamicInterface/DII_Reply_Dispatcher.cpp, TAO/tao/Messaging/Asynch_Reply_Dispatcher.cpp, TAO/tao/Synch_Reply_Dispatcher.cpp
* TAO/tao/DynamicInterface/DII_Reply_Dispatcher.cpp:
* TAO/tao/Messaging/Asynch_Reply_Dispatcher.cpp:
* TAO/tao/Synch_Reply_Dispatcher.cpp:
=> Fixed typo

ACE/COPYING, CIAO/COPYING, DAnCE/COPYING, TAO/COPYING
* ACE/COPYING:
* CIAO/COPYING:
* DAnCE/COPYING:
* TAO/COPYING:
=> Updated copyright year

ACE/ace/Dev_Poll_Reactor.cpp, ACE/ace/Select_Reactor_Base.cpp, ACE/ace/config-face-safety.h
* ACE/ace/Dev_Poll_Reactor.cpp:
* ACE/ace/Select_Reactor_Base.cpp:
* ACE/ace/config-face-safety.h:
=> Tweaked code to not call unsupported methods

ACE/ace/TLI.cpp
=> Removed not necessary return

ACE/bin/fuzz.pl
=> Extend $Id check

TAO/orbsvcs/ImplRepo_Service/ImR_Activator_i.cpp
* TAO/orbsvcs/ImplRepo_Service/ImR_Activator_i.cpp:
=> Fixed incorrect logging formatter

TAO/orbsvcs/ImplRepo_Service/README, TAO/orbsvcs/tests/ImplRepo/run_test.pl
* TAO/orbsvcs/ImplRepo_Service/README:
Removed commented out code
* TAO/orbsvcs/tests/ImplRepo/run_test.pl:
=> Documentation updates

TAO/utils/nslist/nslist.cpp
* TAO/utils/nslist/nslist.cpp:
=> Fixed comparison warnings

ACE/debian/ace.dsc
=> Just ACE+TAO

README.md
=> Another ATCD change

ACE/ACE-INSTALL.html, ACE/bin/make_release.py, ACE/docs/ACE-bug-process.html, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, README.md, TAO/TAO-INSTALL.html, TAO/tao/Transport.h, TAO/tao/Transport_Selection_Guard.h
* ACE/ACE-INSTALL.html:
* ACE/docs/ACE-bug-process.html:
* README.md:
* TAO/TAO-INSTALL.html:
* TAO/tao/Transport.h:
* TAO/tao/Transport_Selection_Guard.h:
=> Updates for change of ATCD to ACE_TAO

README.md
=> Correct link to appveyor badge

ACE/README
=> Update old link

ACE/NEWS
=> Extended for next release

ACE/debian/debian.control
=> Fixed some package versions

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/bin/make_release.py, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make x.3.4 public and prepare for x.3.5

ACE/ace/OS_NS_netdb.cpp
=> Fixed may be used uninitialized warning

ACE/ace/config-kfreebsd.h
=> In kfreebasd atop is a macro which we need to undefine

ACE/ACE-INSTALL.html
=> Improved documentation

ACE/NEWS, TAO/NEWS
=> Updated for next release

ACE/NEWS
=> Added reduced include of ace/Auto_Ptr.h

TAO/tao/Dynamic_TP/DTP_POA_Strategy.cpp
* TAO/tao/Dynamic_TP/DTP_POA_Strategy.cpp:
=> Indent changes to fix gcc 6.1 warnings

README.md
=> Rework to mention that occasional contributors should use pull requests

README.md
=> Further cleanup of bugzilla mentining

ACE/bin/generate_compile_stats.sh
Fix issues when using generate_compile_stats.sh for non-ACE/TAO/CIAO/DAnCE builds.
=> Topic footprint fixes

ACE/ace/OS_NS_stdlib.h, ACE/ace/OS_NS_stdlib.inl, ACE/ace/OS_NS_time.cpp, ACE/ace/OS_NS_time.h, ACE/ace/OS_NS_time.inl
=> Revert "Handle system functions that may be defined as macros on some platforms"

ACE/ace/OS_NS_sys_stat.h
=> Use stati64 with MinGW

ACE/ace/Time_Value.cpp
=> Use std::abs instead of abs

ACE/ace/config-android.h
=> Disable newer features because they lead to runtime problems on Android

ACE/ace/Time_Value.inl
=> Revert "ACE Core Typo Bug"

ACE/include/makeinclude/platform_android.GNU
* ACE/include/makeinclude/platform_android.GNU:
=> Set ACE_PLATFORM_CONFIG to config-android.h

ACE/NEWS, TAO/orbsvcs/tests/FT_Naming/FaultTolerant/FaultTolerant.mpc
=> Fixed parallel build error

ACE/bin/diff-builds.pl
=> Make this script work again with newer perl versions

ACE/NEWS, TAO/NEWS
=> Extended list of user visible changes

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make x.4.1 public and make initial changes for x.4.2

ACE/bin/make_release.py, ACE/docs/bczar/bczar.html
=> Simplify release script

ACE/bin/make_release.py, ACE/docs/bczar/bczar.html
=> Talk about micro instead of a beta release

TAO/TAO_IDL/be/be_visitor_array/array_ci.cpp
* TAO/TAO_IDL/be/be_visitor_array/array_ci.cpp:
=> Changed indentation of generated array code to reduce its size

ACE/ace/Asynch_IO.h, ACE/ace/CDR_Stream.h, ACE/ace/Hash_Map_Manager_T.h, ACE/ace/Hash_Multi_Map_Manager_T.h, ACE/ace/Malloc_T.cpp, ACE/ace/Map_Manager.h, ACE/ace/POSIX_Asynch_IO.h, ACE/ace/SSL/SSL_Context.h, ACE/websvcs/lib/URL_Addr.h, TAO/orbsvcs/orbsvcs/FtRtEvent/Utils/Safe_InputCDR.h, TAO/orbsvcs/tests/AVStreams/Pluggable/ftp.h, TAO/orbsvcs/tests/Notify/Basic/Events.h, TAO/orbsvcs/tests/Notify/Basic/Simple.h, TAO/orbsvcs/tests/Notify/Basic/Updates.h, TAO/orbsvcs/tests/Notify/performance-tests/Throughput/Throughput.h, TAO/tao/CDR.h
* ACE/ace/Asynch_IO.h:
* ACE/ace/CDR_Stream.h:
* ACE/ace/Hash_Map_Manager_T.h:
* ACE/ace/Hash_Multi_Map_Manager_T.h:
* ACE/ace/Malloc_T.cpp:
* ACE/ace/Map_Manager.h:
* ACE/ace/POSIX_Asynch_IO.h:
* ACE/ace/SSL/SSL_Context.h:
* ACE/websvcs/lib/URL_Addr.h:
* TAO/orbsvcs/orbsvcs/FtRtEvent/Utils/Safe_InputCDR.h:
* TAO/orbsvcs/tests/AVStreams/Pluggable/ftp.h:
* TAO/orbsvcs/tests/Notify/Basic/Events.h:
* TAO/orbsvcs/tests/Notify/Basic/Simple.h:
* TAO/orbsvcs/tests/Notify/Basic/Updates.h:
* TAO/orbsvcs/tests/Notify/performance-tests/Throughput/Throughput.h:
* TAO/tao/CDR.h:
=> Fixed typos in comment

.travis.yml
=> Attempt to test FACE configuration

ACE/ace/config-win32-common.h, TAO/orbsvcs/orbsvcs/IFRService/Container_i.h, TAO/tests/Bug_1551_Regression/client.cpp, TAO/tests/Bug_2595_Regression/Hello.h, TAO/tests/Portable_Interceptors/Collocated/Dynamic/interceptors.h, TAO/tests/Portable_Interceptors/Dynamic/client_interceptor.h, TAO/tests/Portable_Interceptors/Dynamic/server_interceptor.h, TAO/tests/Portable_Interceptors/Processing_Mode_Policy/Collocated/interceptors.h, TAO/tests/Portable_Interceptors/Processing_Mode_Policy/Remote/client_interceptor.h, TAO/tests/Portable_Interceptors/Processing_Mode_Policy/Remote/server_interceptor.h
* ACE/ace/config-win32-common.h:
* TAO/orbsvcs/orbsvcs/IFRService/Container_i.h:
* TAO/tests/Bug_1551_Regression/client.cpp:
* TAO/tests/Bug_2595_Regression/Hello.h:
* TAO/tests/Portable_Interceptors/Collocated/Dynamic/interceptors.h:
* TAO/tests/Portable_Interceptors/Dynamic/client_interceptor.h:
* TAO/tests/Portable_Interceptors/Dynamic/server_interceptor.h:
* TAO/tests/Portable_Interceptors/Processing_Mode_Policy/Collocated/interceptors.h:
* TAO/tests/Portable_Interceptors/Processing_Mode_Policy/Remote/client_interceptor.h:
* TAO/tests/Portable_Interceptors/Processing_Mode_Policy/Remote/server_interceptor.h:
=> Layout changes and fixed some typos

TAO/TAO_IDL/be/be_visitor_exception/any_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_exception/cdr_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_exception/exception_cs.cpp, TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp, TAO/TAO_IDL/be/be_visitor_operation/ami_handler_reply_stub_operation_cs.cpp, TAO/TAO_IDL/be/be_visitor_sequence/any_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_structure/any_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_union/any_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuebox/any_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuebox/cdr_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/any_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/cdr_op_cs.cpp
* TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:
=> Removed not necessary c-style cast and reduce size of generated code

TAO/TAO_IDL/be/be_visitor_sequence/sequence_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuebox/valuebox_ch.cpp
* TAO/TAO_IDL/be/be_visitor_sequence/sequence_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_valuebox/valuebox_ch.cpp:
=> Small changes to the generated code

TAO/NEWS
=> List versioned namespace changes

ACE/ace/CDR_Size.h, ACE/ace/CDR_Stream.h, ACE/ace/Codecs.h, ACE/tests/Upgradable_RW_Test.cpp, TAO/DevGuideExamples/PortableInterceptors/Auth/ClientInitializer.cpp, TAO/orbsvcs/orbsvcs/RtecEventChannelAdmin.idl, TAO/performance-tests/Cubit/TAO/DII_Cubit/client.cpp, TAO/performance-tests/Cubit/TAO/IDL_Cubit/Cubit_Client.cpp, TAO/performance-tests/POA/Object_Creation_And_Registration/registration.cpp, TAO/tests/POA/Generic_Servant/client.cpp, TAO/tests/POA/TIE/client.cpp
* ACE/ace/CDR_Size.h:
* ACE/ace/CDR_Stream.h:
* ACE/ace/Codecs.h:
* ACE/tests/Upgradable_RW_Test.cpp:
* TAO/DevGuideExamples/PortableInterceptors/Auth/ClientInitializer.cpp:
* TAO/orbsvcs/orbsvcs/RtecEventChannelAdmin.idl:
* TAO/performance-tests/Cubit/TAO/DII_Cubit/client.cpp:
* TAO/performance-tests/Cubit/TAO/IDL_Cubit/Cubit_Client.cpp:
* TAO/performance-tests/POA/Object_Creation_And_Registration/registration.cpp:
* TAO/tests/POA/Generic_Servant/client.cpp:
* TAO/tests/POA/TIE/client.cpp:
=> Doxygen changes and some typos

ACE/docs/Download.html
=> Added CIAO and DAnCE micro releases

ACE/COPYING, TAO/COPYING
=> Updated copyright to 2017

ACE/ace/Global_Macros.h, ACE/ace/Message_Block.cpp, TAO/tao/Asynch_Queued_Message.cpp, TAO/tao/Synch_Queued_Message.cpp
* ACE/ace/Global_Macros.h:
* ACE/ace/Message_Block.cpp:
* TAO/tao/Asynch_Queued_Message.cpp:
* TAO/tao/Synch_Queued_Message.cpp:
=> No need to pass this to ACE_DES_FREE_THIS

TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/FTEC_Event_Channel_Impl.cpp, TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/Request_Context_Repository.cpp, TAO/orbsvcs/tests/FtRtEvent/PushConsumer.cpp
Fixed three new memory leaks which got introduced by the any extraction cleanup
=> Fixed memory leaks

TAO/tao/Strategies/SCIOP_Connector.cpp
* TAO/tao/Strategies/SCIOP_Connector.cpp:
=> Fixed compile error

TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/FTEC_Event_Channel_Impl.cpp
* TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/FTEC_Event_Channel_Impl.cpp:
=> Make usage of var/ptr as it was

TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/Request_Context_Repository.cpp
* TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/Request_Context_Repository.cpp:
=> Make var/ptr usage as it was

ACE/ace/Global_Macros.h
=> Only check for ACE_HAS_CPP11 for ACE_NOEXCEPT_FALSE

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make x.4.2 public and prepare for next release

.travis.yml, TAO/examples/Callback_Quoter/Consumer.idl, TAO/examples/Callback_Quoter/Consumer_Input_Handler.cpp
=> Enable clang support

README.md
=> Different icon

README.md
=> Reduced header

ACE/docs/Download.html
=> Remove link to orbzone

TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context_Factory.cpp
I missed making this change in my previous PR
=> Fixing the preamble for a .cpp file

ACE/tests/INET_Addr_Test_IPV6.cpp
* ACE/tests/INET_Addr_Test_IPV6.cpp:
=> Fixed compile warning at the moment ACE_HAS_IPV6 is not defined

TAO/orbsvcs/tests/FT_Naming/Replication/client.cpp
* TAO/orbsvcs/tests/FT_Naming/Replication/client.cpp:
=> Fixed warnings about unreference local variable

appveyor.yml
=> Use Visual Studio 2017

ACE/ace/INET_Addr.cpp, ACE/tests/INET_Addr_Test.cpp
This revert commits 020cfd8d8ffa71ec6169287dc2e98cc0d4f7e815 db516618eee937974d9e902864ad0165320d85d8 76dcc3fed2faf5c2148df8adb09ef3bc7b11b440 6dd56850da60fde290f39d313397d11cbae47df2 8eb07a10571eb342755f4036424b0724f9eb407c f5c4d13041422d8f713c150d480e09fadccecf70
=> Revert PR #394 #385 #382 #397

ACE/NEWS, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make ACE/TAO 6.4.3/2.4.3 public available

ACE/docs/Download.html, appveyor.yml
=> Add Visual Studio 2017 as available in the full package

ACE/ace/INET_Addr.cpp, ACE/tests/INET_Addr_Test.cpp
A new attempt to fix inet_addr::set() with workaround for AIX.
=> Inet addr fix

ACE/examples/ASX/UPIPE_Event_Server/event_server.cpp, TAO/tests/DII_AMI_Forward/server.cpp, TAO/tests/ForwardOnceUponException/client.cpp, TAO/tests/ForwardUponObjectNotExist/client.cpp
* ACE/examples/ASX/UPIPE_Event_Server/event_server.cpp:
* TAO/tests/DII_AMI_Forward/server.cpp:
* TAO/tests/ForwardOnceUponException/client.cpp:
* TAO/tests/ForwardUponObjectNotExist/client.cpp:
=> Fixed gcc warnings

ACE/docs/Download.html
=> Updated header for latest micro release to include version numbers

ACE/tests/INET_Addr_Test.cpp
An attempt to find problem for INET_Addr_Test on AIX
=> Added more detailed debug message

ACE/ace/config-macosx-highsierra.h, ACE/ace/config-macosx.h, ACE/include/makeinclude/platform_macosx.GNU, ACE/include/makeinclude/platform_macosx_highsierra.GNU, ACE/include/makeinclude/platform_macosx_sierra.GNU
* ACE/ace/config-macosx-highsierra.h:
* ACE/include/makeinclude/platform_macosx_highsierra.GNU:
Added.
* ACE/ace/config-macosx.h:
* ACE/include/makeinclude/platform_macosx.GNU:
* ACE/include/makeinclude/platform_macosx_sierra.GNU:
=> Updated macosx version files

ACE/protocols/ace/INet/SSLSock_IOStream.cpp
* ACE/protocols/ace/INet/SSLSock_IOStream.cpp:
=> Fix gcc7.1 compile errors

ACE/ace/config-android.h
=> Move versioned checks lower down in the file

ACE/ace/config-android.h
=> Changed android version check

ACE/ace/config-android.h
=> Corrected fdmask check

ACE/ace/Name_Proxy.cpp, TAO/TAO_IDL/be/be_visitor_module/module.cpp
* ACE/ace/Name_Proxy.cpp:
* TAO/TAO_IDL/be/be_visitor_module/module.cpp:
=> Fix gcc7.1 warnings

ACE/ace/config-win32-borland.h
=> Improve support for Embarcadero C++ Builder

ACE/ace/Object_Manager.cpp
=> Fixed warning with Embarcadero C++ Builder

ACE/ace/Process.cpp
=> Directly assign result to status

ACE/tests/Compiler_Features_37_Test.cpp, ACE/tests/run_test.lst, ACE/tests/tests.mpc
* ACE/tests/Compiler_Features_37_Test.cpp:
Added.
* ACE/tests/run_test.lst:
* ACE/tests/tests.mpc:
=> New compiler test for a compiler bug found some time ago

ACE/ace/ACE_export.h, ACE/ace/config-win32-common.h, TAO/docs/exceptions.html
=> Don't use dllexport/dllimport with inline methods

ACE/ace/Array_Map.cpp, ACE/ace/Array_Map.h, ACE/ace/Compression/rle/RLECompressor.cpp, ACE/ace/post.h, ACE/ace/pre.h, TAO/orbsvcs/orbsvcs/IFRService/IFR_Service_Utils_T.cpp, TAO/orbsvcs/orbsvcs/Naming/FaultTolerant/FT_Storable_Naming_Context.cpp, TAO/orbsvcs/orbsvcs/PortableGroup/PG_Utils.cpp, TAO/orbsvcs/tests/Notify/Bug_3252_Regression/server.cpp
* ACE/ace/Array_Map.cpp:
* ACE/ace/Array_Map.h:
=> Add workaround for broken bcc32, see RSP-15011

ACE/tests/Compiler_Features_37_Test.cpp
* ACE/tests/Compiler_Features_37_Test.cpp:
=> Fix compiler warning

ACE/ace/ACE_export.h
=> Simplify ACE_NAMESPACE_INLINE_FUNCTION

TAO/tests/Bug_3574_Regression/test.cpp
* TAO/tests/Bug_3574_Regression/test.cpp:
=> Updated bcc32 version checks

TAO/orbsvcs/orbsvcs/PortableGroup/PG_Utils.cpp, TAO/orbsvcs/orbsvcs/PortableGroup/PG_Utils.h
* TAO/orbsvcs/orbsvcs/PortableGroup/PG_Utils.cpp:
* TAO/orbsvcs/orbsvcs/PortableGroup/PG_Utils.h:
=> Fix problem with bcc32

ACE/ACE-INSTALL.html
=> Extend Embarcadero documentation

TAO/orbsvcs/orbsvcs/CosNotification.mpc
* TAO/orbsvcs/orbsvcs/CosNotification.mpc:
=> Remove bcc32 flags from here

TAO/orbsvcs/orbsvcs/Notify/RT_Factory.h
* TAO/orbsvcs/orbsvcs/Notify/RT_Factory.h:
=> Suppress warning 8022 with bcc32

ACE/ACE.mwc, TAO/tests/TransportCurrent/IIOP/IIOP.mpc
* ACE/ACE.mwc:
* TAO/tests/TransportCurrent/IIOP/IIOP.mpc:
=> Cleanup old automake support

ACE/tests/Malloc_Test.cpp
=> Corrected placing pragma pop for bcc32c

ACE/bin/msvc_static_order.lst, ACE/tests/run_test.lst, TAO/TAO_IDL/fe/idl.ypp, TAO/bin/tao_orb_tests.lst, TAO/bin/tao_other_tests.lst, TAO/tests/Bug_3755_Ext_Regression/all.lst, TAO/tests/COIOP/COIOP.lst
* ACE/bin/msvc_static_order.lst:
* ACE/tests/run_test.lst:
* TAO/TAO_IDL/fe/idl.ypp:
* TAO/bin/tao_orb_tests.lst:
* TAO/bin/tao_other_tests.lst:
* TAO/tests/Bug_3755_Ext_Regression/all.lst:
* TAO/tests/COIOP/COIOP.lst:
=> Remove left over $Id tags

ACE/NEWS
=> Listed major changes

.travis.yml, TAO/TAO_IDL/be/be_codegen.cpp, TAO/TAO_IDL/be/be_visitor_array/array_ch.cpp, TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp, TAO/TAO_IDL/be/be_visitor_root/root_ch.cpp, TAO/tao/AnyTypeCode/AnyTypeCode_methods.h, TAO/tao/AnyTypeCode/TypeCode.h, TAO/tao/AnyTypeCode/WrongTransactionA.h, TAO/tao/CORBA_methods.h, TAO/tao/DynamicInterface/Context.h, TAO/tao/DynamicInterface/DII_CORBA_methods.h, TAO/tao/DynamicInterface/ExceptionList.h, TAO/tao/DynamicInterface/Request.h, TAO/tao/DynamicInterface/Server_Request.h, TAO/tao/DynamicInterface/Unknown_User_Exception.h, TAO/tao/Object_KeyC.h, TAO/tao/PI/PolicyFactoryC.h, TAO/tao/PI_Server/ServerRequestInterceptorC.h, TAO/tao/PortableServer/PS_ForwardC.h, TAO/tao/PortableServer/PortableServer_Functions.h, TAO/tao/PortableServer/PortableServer_WFunctions.h, TAO/tao/RTCORBA/RT_ProtocolPropertiesC.h, TAO/tao/Typecode_typesC.h, TAO/tao/Valuetype/AbstractBase.h, TAO/tao/Valuetype/ValueBase.h, TAO/tao/Valuetype/Value_CORBA_methods.h, TAO/tao/WrongTransactionC.h
* TAO/TAO_IDL/be/be_codegen.cpp:
* TAO/TAO_IDL/be/be_visitor_constant/constant_ch.cpp:
* TAO/TAO_IDL/be/be_visitor_root/root_ch.cpp:
=> Remove TAO_EXPORT_MACRO usage

ACE/docs/bczar/bczar.html, ACE/docs/bczar/privileges.html
* ACE/docs/bczar/privileges.html:
=> Fixed typos and remove references to manually maintained changelog

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html, TAO/NEWS
=> Make ACE 6.4.4 and TAO 2.4.4 available

ACE/docs/Download.html
=> Incremented TAO version

ACE/apps/Gateway/Gateway/Concrete_Connection_Handlers.cpp, ACE/apps/Gateway/Peer/Peer.cpp, ACE/tests/Based_Pointer_Test_Lib.cpp, TAO/tao/DynamicAny/DynAny_i.cpp
* ACE/tests/Based_Pointer_Test_Lib.cpp:
* TAO/tao/DynamicAny/DynAny_i.cpp:
=> Fix gcc7 warning

ACE/apps/JAWS2/JAWS/Cache_Hash_T.cpp, ACE/apps/JAWS2/JAWS/Cache_Hash_T.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Acceptor.cpp, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Factory.cpp
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Acceptor.cpp:
=> Fixed size_t to int conversion

ACE/docs/Download.html
=> Remove google tracking code

ACE/tests/run_test.lst
=> TSS_Leak_Test is known to fail at this moment

ACE/bin/MakeProjectCreator/config/global.features
* ACE/bin/MakeProjectCreator/config/global.features:
=> Added openssl11 as default to 0, has to be manually enabled

ACE/docs/bczar/bczar.html
=> Added two places where ACE has to be updated after a release

TAO/NEWS
=> List change

TAO/orbsvcs/orbsvcs/Notify/Any/CosEC_ProxyPushSupplier.h, TAO/orbsvcs/orbsvcs/Notify/Any/ProxyPushSupplier.h, TAO/orbsvcs/tests/Notify/Reconnecting/Supplier.cpp
* TAO/orbsvcs/orbsvcs/Notify/Any/CosEC_ProxyPushSupplier.h:
* TAO/orbsvcs/orbsvcs/Notify/Any/ProxyPushSupplier.h:
* TAO/orbsvcs/tests/Notify/Reconnecting/Supplier.cpp:
=> Layout changes

TAO/orbsvcs/orbsvcs/Notify/Any/AnyEvent.h, TAO/orbsvcs/orbsvcs/Notify/Any/ProxyPushConsumer.h, TAO/orbsvcs/orbsvcs/Notify/Any/PushConsumer.h, TAO/orbsvcs/orbsvcs/Notify/Any/PushSupplier.h
* TAO/orbsvcs/orbsvcs/Notify/Any/AnyEvent.h:
* TAO/orbsvcs/orbsvcs/Notify/Any/ProxyPushConsumer.h:
* TAO/orbsvcs/orbsvcs/Notify/Any/PushConsumer.h:
* TAO/orbsvcs/orbsvcs/Notify/Any/PushSupplier.h:
=> Minor cleanup to documentation and removed commented out code

TAO/orbsvcs/tests/FT_Naming/FaultTolerant/client.cpp
* TAO/orbsvcs/tests/FT_Naming/FaultTolerant/client.cpp:
=> Fixed compile errors

TAO/orbsvcs/tests/CosEvent/Basic/Random.h
* TAO/orbsvcs/tests/CosEvent/Basic/Random.h:
=> Removed RND_Timer, it is not used

TAO/tao/PortableServer/Operation_Table_Binary_Search.h, TAO/tao/PortableServer/Operation_Table_Perfect_Hash.cpp, TAO/tao/PortableServer/Operation_Table_Perfect_Hash.h
* TAO/tao/PortableServer/Operation_Table_Binary_Search.h:
* TAO/tao/PortableServer/Operation_Table_Perfect_Hash.cpp:
* TAO/tao/PortableServer/Operation_Table_Perfect_Hash.h:
=> Documentation typo fixes

TAO/orbsvcs/tests/Notify/Structured_Multi_Filter/run_test.pl
* TAO/orbsvcs/tests/Notify/Structured_Multi_Filter/run_test.pl:
=> Kill running processes when the consumer fails

ACE/ACEXML/common/Mem_Map_Stream.cpp, ACE/ACEXML/parser/parser/Parser.cpp, ACE/ace/Timer_Queue_T.cpp, TAO/orbsvcs/tests/Bug_3216_Regression/client.cpp
* ACE/ACEXML/parser/parser/Parser.cpp:
=> Fixed exception throwing

TAO/tao/PortableServer/Servant_Base.cpp, TAO/tao/PortableServer/Servant_Base.h
* Guard assignment operator for self assignment
* Extend constructor to allow passing the operation table
=> TAO_ServantBase changes

ACE/rpmbuild/ace-tao.spec
Add missing ESF header files to allow extending features in application code.
=> Add missing ESF header files

TAO/NEWS, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Acceptor.cpp, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Transport.cpp
...also fixed an issue with BiDir GIOP over SSL with IPv4-mapped IPv6 addresses
=> Bug 1220 fix applied to SSLIOP (fixed for IIOP long ago)

ACE/NEWS
=> List changes

.travis.yml
=> Added usage of travis_latest

TAO/TAO_IDL/ast/ast_expression.cpp
* TAO/TAO_IDL/ast/ast_expression.cpp:
=> Fixed memory leak when we have a wstrval

ACE/examples/Reactor/WFMO_Reactor/Exceptions.cpp, ACE/examples/Reactor/WFMO_Reactor/Suspended_Removals.cpp
* ACE/examples/Reactor/WFMO_Reactor/Exceptions.cpp:
* ACE/examples/Reactor/WFMO_Reactor/Suspended_Removals.cpp:
=> Fixed errors with versioned namespace builds

ACE/NEWS
=> List major changes

ACE/bin/MakeProjectCreator/config/bmake.features
* ACE/bin/MakeProjectCreator/config/bmake.features:
=> Remove old left over version commit message

TAO/bin/tao_orb_tests.lst, TAO/tao/Strategies/SHMIOP_Acceptor.cpp, TAO/tao/Strategies/SHMIOP_Connector.cpp, TAO/tao/Synch_Invocation.cpp, TAO/tests/SHMIOP/SHMIOP_Test.mpc, TAO/tests/SHMIOP/Test.idl, TAO/tests/SHMIOP/run_test.pl, TAO/tests/SHMIOP/run_test_collocated.pl, TAO/tests/SHMIOP/shmiop_test.cpp, TAO/tests/SHMIOP/static_shmiop.conf
Also added a SHMIOP test, IPv6 compatibility, and fixed wrong indent in Synch_Invocation.cpp.
=> Bug 1220 fix applied to SHMIOP (fixed for IIOP long ago).

ACE/tests/Compiler_Features_38_Test.cpp
* ACE/tests/Compiler_Features_38_Test.cpp:
=> Sun Studio 5.13 and older can't handle this

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html
=> ACE/TAO x.4.7 release

ACE/ace/XML_Utils/XMLSchema/Traversal.hpp, ACE/ace/XML_Utils/XMLSchema/Traversal.ipp, ACE/ace/XML_Utils/XMLSchema/TypeInfo.hpp, ACE/ace/XML_Utils/XMLSchema/TypeInfo.ipp, ACE/ace/XML_Utils/XMLSchema/Types.hpp, ACE/ace/XML_Utils/XMLSchema/Types.ipp, ACE/ace/XML_Utils/XMLSchema/Writer.hpp, ACE/ace/XML_Utils/XMLSchema/Writer.ipp
* ACE/ace/XML_Utils/XMLSchema/Traversal.ipp:
* ACE/ace/XML_Utils/XMLSchema/TypeInfo.ipp:
* ACE/ace/XML_Utils/XMLSchema/Types.ipp:
* ACE/ace/XML_Utils/XMLSchema/Writer.ipp:
Deleted.
* ACE/ace/XML_Utils/XMLSchema/Traversal.hpp:
* ACE/ace/XML_Utils/XMLSchema/TypeInfo.hpp:
* ACE/ace/XML_Utils/XMLSchema/Types.hpp:
* ACE/ace/XML_Utils/XMLSchema/Writer.hpp:
=> Remove empty ipp files

ACE/ace/XML_Utils/XMLSchema/Types.hpp, ACE/ace/XML_Utils/XSCRT/Elements.hpp
* ACE/ace/XML_Utils/XMLSchema/Types.hpp:
* ACE/ace/XML_Utils/XSCRT/Elements.hpp:
=> Add get_idref that works wit a string&

ACE/docs/index.html, ACE/docs/msvc_notes.txt
* ACE/docs/index.html:
* ACE/docs/msvc_notes.txt:
=> Documentation improvements and updated links

ACE/ace/UUID.h, ACE/ace/XML_Utils/XMLSchema/id_map.hpp, ACE/ace/XML_Utils/XSCRT/Elements.hpp
* ACE/ace/UUID.h:
* ACE/ace/XML_Utils/XMLSchema/id_map.hpp:
* ACE/ace/XML_Utils/XSCRT/Elements.hpp:
=> Minor improvements to the XML utils classes

ACE/tests/README
change
ACE_ROOT/tests/run_test.pl
to
$ACE_ROOT/tests/run_test.pl
=> Add missing $ prefix to ACE_ROOT

ACE/tests/Compiler_Features_32_Test.cpp
=> Compiler_Features_32_Test for clang 6

TAO/tao/Connector_Registry.cpp
* TAO/tao/Connector_Registry.cpp:
=> Add some more error logic for the cases the create_profile fails

TAO/tao/Object.cpp
=> Combine two logging lines into one

TAO/tao/Storable_File_Guard.cpp
* TAO/tao/Storable_File_Guard.cpp:
=> Catch exception by reference

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> ACE+TAO x.4.8 release

.travis.yml
=> Add clang6 and gcc8 on travis-ci

ACE/bin/valgrind.supp
=> Add valgrind suppression

ACE/NEWS, TAO/NEWS
=> Next release will be minor

ACE/bin/valgrind.supp
=> Removed invalid supp

ACE/ace/config-macosx-mojave.h, ACE/ace/config-macosx.h, ACE/include/makeinclude/platform_macosx.GNU, ACE/include/makeinclude/platform_macosx_mojave.GNU
* ACE/ace/config-macosx-mojave.h:
* ACE/include/makeinclude/platform_macosx_mojave.GNU:
Added.
* ACE/ace/config-macosx.h:
* ACE/include/makeinclude/platform_macosx.GNU:
=> Added starter files for MacOSX Mojave

TAO/tao/DynamicAny/DynamicAny.mpc
* TAO/tao/DynamicAny/DynamicAny.mpc:
=> List empty PIDL_Files section to not generate DynamicAny.pidl twice

TAO/tao/PortableServer/Servant_Base.cpp, TAO/tao/PortableServer/Servant_Base.h
* TAO/tao/PortableServer/Servant_Base.cpp:
* TAO/tao/PortableServer/Servant_Base.h:
=> Revert rename of ref_count_ to refcount_

ACE/ace/Timer_Wheel_T.cpp
=> Removed not used variable

ACE/ace/CDR_Size.h, ACE/ace/CDR_Size.inl, ACE/ace/CDR_Stream.cpp, ACE/ace/CDR_Stream.h, ACE/ace/CDR_Stream.inl, ACE/ace/Codeset_IBM1047.cpp, ACE/ace/Codeset_IBM1047.h, ACE/tests/CDR_Test.cpp, TAO/tao/CDR.h, TAO/tao/CDR.inl, TAO/tao/Codeset/UTF16_BOM_Translator.cpp, TAO/tao/Codeset/UTF16_BOM_Translator.h, TAO/tao/Codeset/UTF8_Latin1_Translator.cpp, TAO/tao/Codeset/UTF8_Latin1_Translator.h
(optimized for C++11 and onwards)
added tests for optimized std::(w)string support
extend character translators with std::(w)string support also
=> add full support for streaming std::(w)string

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make x.5.1 public and prepare for the next release

TAO/docs/rtcorba/omg_issues.html, TAO/docs/rtcorba/status.html, TAO/tests/RTCORBA/README
* TAO/docs/rtcorba/status.html:
* TAO/tests/RTCORBA/README:
=> Fixed links to the OMG website

TAO/orbsvcs/ImplRepo_Service/Shared_Backing_Store.cpp
* TAO/orbsvcs/ImplRepo_Service/Shared_Backing_Store.cpp:
=> Fixed windows runtime issue

TAO/orbsvcs/tests/Security/Bug_2908_Regression/Client_Task.cpp, TAO/orbsvcs/tests/Security/Bug_2908_Regression/Client_Task.h, TAO/tests/ZIOP/client.cpp
* TAO/orbsvcs/tests/Security/Bug_2908_Regression/Client_Task.cpp:
* TAO/orbsvcs/tests/Security/Bug_2908_Regression/Client_Task.h:
* TAO/tests/ZIOP/client.cpp:
=> Catch exceptions by reference

ACE/ace/Future.cpp
=> Check observer pointer before using it

ACE/ace/SSL/SSL_Asynch_BIO.cpp
* ACE/ace/SSL/SSL_Asynch_BIO.cpp:
=> Only define BIO_set_flags when it has not been defined yet

TAO/tao/ImR_Client/ImR_Client.cpp
* TAO/tao/ImR_Client/ImR_Client.cpp:
=> Only log errors when we have a debugging level set

ACE/bin/MakeProjectCreator/config/global.features
To Match [Qt5 Support in MPC](https://github.com/DOCGroup/MPC/pull/69).
=> Disable Qt5 MPC Feature by Default

ACE/debian/default.features, ACE/debian/platform_macros.GNU
* ACE/debian/default.features:
* ACE/debian/platform_macros.GNU:
=> Removed qt settings to 0 for debian packaging, these are disabled by default

README.md
=> Added Azure DevOps badge

azure-pipelines.yml
=> Use powershell to create the config.h file

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make x.5.2 public as new release

azure-pipelines.yml
=> Set maximum job timeout for 90 minutes

azure-pipelines.yml
=> Make use of vs2017/vs2015/linux on azure

azure-pipelines.yml
=> Added MacOSX job

ACE/ace/Time_Value.cpp
=> Const enhancements

TAO/bin/tao_orb_tests.lst, TAO/docs/ORBEndpoint.html, TAO/docs/Options.html, TAO/docs/pluggable_messaging.html, TAO/docs/pluggable_protocols/index.html, TAO/tao/CORBALOC_Parser.cpp, TAO/tao/Strategies/SHMIOP_Profile.cpp, TAO/tao/Strategies/UIOP_Connection_Handler.cpp, TAO/tao/Strategies/UIOP_Connector.cpp, TAO/tests/Bug_4213_Regression/Bug_4213_Regression.mpc, TAO/tests/Bug_4213_Regression/Hello.cpp, TAO/tests/Bug_4213_Regression/Hello.h, TAO/tests/Bug_4213_Regression/Test.idl, TAO/tests/Bug_4213_Regression/client.cpp, TAO/tests/Bug_4213_Regression/run_test.pl, TAO/tests/Bug_4213_Regression/server.cpp, TAO/tests/Connection_Purging/README, TAO/tests/Connection_Purging/test.idl
=> Added new unit test and fix for uiop problem

TAO/bin/tao_orb_tests.lst, TAO/tests/POA/TIE/run_test.pl
http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=4182
=> Fixed running of POA TIE test and add it to our daily test suite

ACE/ace/os_include/sys/os_sem.h
* ACE/ace/os_include/sys/os_sem.h:
=> Removed experiment for using linux/sem.h

ACE/tests/Message_Block_Test.cpp
=> Add a test case exercising user-allocated ACE_Data_Block-derived object controlled by ACE_Message_Block.

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
Added.
* ACE/NEWS:
* ACE/bin/copy-script.sh:
* TAO/NEWS:
=> Make x.5.3 public and prepare for the next release

ACE/bin/MakeProjectCreator/config/vs2017nmake.mpb
* ACE/bin/MakeProjectCreator/config/vs2017nmake.mpb:
=> Should modify compile_flags to remove /Gm

ACE/ace/Dev_Poll_Reactor.h, ACE/ace/Reactor_Impl.h, ACE/ace/Select_Reactor_T.h, ACE/ace/WFMO_Reactor.h
* ACE/ace/Dev_Poll_Reactor.h:
* ACE/ace/Reactor_Impl.h:
* ACE/ace/Select_Reactor_T.h:
* ACE/ace/WFMO_Reactor.h:
=> Doxygen enhancements

README.md
=> Use travis-ci.com badge

TAO/TAO_IDL/be/be_visitor_field/cdr_op_cs.cpp, TAO/tao/Fixed_Array_Argument_T.inl
* TAO/TAO_IDL/be/be_visitor_field/cdr_op_cs.cpp:
* TAO/tao/Fixed_Array_Argument_T.inl:
=> Remove workarounds for ancient IBM compiler

README.md
=> Add badge for latest release

ACE/ace/Connection_Recycling_Strategy.h, ACE/ace/Connector.h
* ACE/ace/Connection_Recycling_Strategy.h:
* ACE/ace/Connector.h:
=> Removed some empty lines

ACE/docs/Download.html
=> Fixed one version update

TAO/TAO_IDL/ast/ast_decl.cpp
=> Revert "Fixed memory leak of annotation_appls_"

ACE/ace/Lib_Find.h, ACE/ace/SOCK_Connector.h, ACE/ace/SOCK_SEQPACK_Connector.h
* ACE/ace/Lib_Find.h:
* ACE/ace/SOCK_Connector.h:
* ACE/ace/SOCK_SEQPACK_Connector.h:
=> Fixed typos in comments

ACE/ace/Process.cpp, ACE/ace/Process.h, ACE/ace/Process.inl, ACE/ace/ace_wchar.h
Create process as user in Windows by specifying user token.
=> Support creating process as user in Windows.

ACE/ace/SSL/SSL_Context.cpp
* ACE/ace/SSL/SSL_Context.cpp:
=> Reduced scope of error variable

ACE/NEWS
=> Add item for broken lists

ACE/ace/Timer_Queue_Adapters.cpp, ACE/ace/Timer_Queue_Adapters.h, ACE/ace/Timer_Queue_T.h
* ACE/ace/Timer_Queue_Adapters.cpp:
* ACE/ace/Timer_Queue_Adapters.h:
* ACE/ace/Timer_Queue_T.h:
=> Fix spurious wakeups due to incomplete timepolicy handling.

ACE/ace/DLL_Manager.cpp, ACE/ace/DLL_Manager.h
* Make dlopen code into `open_i`
* Make logging error into `log_error`
=> Refactor ACE_DLL_Handle::open

ACE/ace/Message_Queue_T.cpp, ACE/examples/APG/Active_Objects/AO.cpp, ACE/examples/APG/Active_Objects/AO2.cpp, ACE/examples/Threads/future1.cpp, ACE/examples/Threads/future2.cpp, ACE/performance-tests/TCP/tcp_test.cpp, ACE/performance-tests/UDP/udp_test.cpp
* ACE/ace/Message_Queue_T.cpp:
* ACE/examples/APG/Active_Objects/AO.cpp:
* ACE/examples/APG/Active_Objects/AO2.cpp:
* ACE/examples/Threads/future1.cpp:
* ACE/examples/Threads/future2.cpp:
* ACE/performance-tests/TCP/tcp_test.cpp:
* ACE/performance-tests/UDP/udp_test.cpp:
=> Fixed c++11 given warnings

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make x.5.5 public available and prepar for next release

ACE/docs/Download.html
=> Latest release also contains Visual Studio 2019 project files

TAO/orbsvcs/ImplRepo_Service/AsyncListManager.cpp
* TAO/orbsvcs/ImplRepo_Service/AsyncListManager.cpp:
=> Logging fix in ImplRepo_Service

azure-pipelines.yml
=> Use MacOSX 10.14

ACE/ace/config-cygwin32.h
I was able to build this using the latest Cygwin as of June 2019, Minor Version 338.
=> Updated config for latest Cygwin

TAO/bin/tao_orb_tests.lst, TAO/tao/DynamicInterface/DII_Reply_Dispatcher.cpp, TAO/tao/DynamicInterface/DII_Reply_Dispatcher.h, TAO/tests/DII_Discard_Deferred/DII_Discard_Deferred.mpc, TAO/tests/DII_Discard_Deferred/Hello.cpp, TAO/tests/DII_Discard_Deferred/Hello.h, TAO/tests/DII_Discard_Deferred/README, TAO/tests/DII_Discard_Deferred/Test.idl, TAO/tests/DII_Discard_Deferred/client.cpp, TAO/tests/DII_Discard_Deferred/run_test.pl, TAO/tests/DII_Discard_Deferred/server.cpp
Fix lifecycle management of Request in DII deferred calls and add regression test.
=> Fix lifecycle management of Request in DII deferred calls

ACE/ace/OS_NS_sys_sendfile.h
* ACE/ace/OS_NS_sys_sendfile.h:
=> Corrected documentation of ACE_OS::sendfile to resolve issue #937

ACE/bin/MakeProjectCreator/templates/gnu.mpd
corrected location of generated header for IDL files in other directories
=> gnuace updates

ACE/NEWS
=> List fix for glibc 2.30 and newer

ACE/ace/Dev_Poll_Reactor.cpp, ACE/ace/Dev_Poll_Reactor.h, ACE/ace/Dev_Poll_Reactor.inl, ACE/ace/TP_Reactor.h
* ACE/ace/Dev_Poll_Reactor.cpp:
* ACE/ace/Dev_Poll_Reactor.h:
* ACE/ace/Dev_Poll_Reactor.inl:
* ACE/ace/TP_Reactor.h:
=> Changed the owner flag of the dev poll reactor from int to bool

ACE/ace/Select_Reactor_Base.h, ACE/ace/Select_Reactor_Base.inl, ACE/ace/Select_Reactor_T.cpp, ACE/ace/TP_Reactor.cpp
* ACE/ace/Select_Reactor_Base.h:
* ACE/ace/Select_Reactor_Base.inl:
* ACE/ace/Select_Reactor_T.cpp:
* ACE/ace/TP_Reactor.cpp:
=> Changed suppress_notify_renew flag from int to bool

TAO/tests/IDLv4/annotations/run_test.pl
Fail the test if process could not be spawned.
=> tao_idl: robustness in run_test.pl

ACE/ace/Service_Gestalt.h, TAO/docs/notification/reliability.html, TAO/orbsvcs/tests/Log/Basic_Log_Test/Basic_Log_Test.cpp, TAO/orbsvcs/tests/Log/Basic_Log_Test/Basic_Log_Test.h, TAO/orbsvcs/tests/Security/mixed_security_test/README
* ACE/ace/Service_Gestalt.h:
* TAO/docs/notification/reliability.html:
* TAO/orbsvcs/tests/Log/Basic_Log_Test/Basic_Log_Test.cpp:
* TAO/orbsvcs/tests/Log/Basic_Log_Test/Basic_Log_Test.h:
* TAO/orbsvcs/tests/Security/mixed_security_test/README:
=> Fixed typos

ACE/ace/os_include/sys/os_socket.h
=> fixed warning on MinGW

.github/workflows/ccpp.yml
=> Add github action to compile ACE/TAO

ACE/ace/OS_NS_sys_socket.cpp, ACE/tests/SOCK_Dgram_Test.cpp
also exclude test from safety profile
=> IPv6 compatibility for recvmsg with control buffer on Windows

ACE/NEWS, ACE/bin/copy-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
* ACE/NEWS:
* ACE/bin/copy-script.sh:
* TAO/NEWS:
=> Make x.5.7 available

ACE/ace/ace.mpc
=> add generate_export_file.pl to installed files

ACE/NEWS, TAO/NEWS
=> List some important changes

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make ACE/TAO 6.5.8/2.5.8 public and prepare for next release

ACE/ace/Dev_Poll_Reactor.h, ACE/ace/MMAP_Memory_Pool.h, ACE/ace/Msg_WFMO_Reactor.h, ACE/ace/QtReactor/QtReactor.cpp, ACE/ace/Sig_Handler.cpp, ACE/ace/Sig_Handler.h
* ACE/ace/Dev_Poll_Reactor.h:
* ACE/ace/MMAP_Memory_Pool.h:
* ACE/ace/Sig_Handler.cpp:
* ACE/ace/Sig_Handler.h:
=> Documentation changes

TAO/tao/ORB.cpp, TAO/tao/ORB.h
* TAO/tao/ORB.cpp:
* TAO/tao/ORB.h:
=> Fixed some typos in comments and removed some empty lines

ACE/ace/Filecache.h, ACE/ace/Framework_Component.h, ACE/ace/Future.h, ACE/ace/Handle_Gobbler.h, ACE/ace/MEM_IO.h
* ACE/ace/Filecache.h:
* ACE/ace/Framework_Component.h:
* ACE/ace/Future.h:
* ACE/ace/Handle_Gobbler.h:
* ACE/ace/MEM_IO.h:
=> Layout and doxygen changes

TAO/orbsvcs/orbsvcs/SSLIOP/IIOP_SSL_Acceptor.h, TAO/orbsvcs/orbsvcs/SSLIOP/IIOP_SSL_Connection_Handler.cpp, TAO/orbsvcs/orbsvcs/SSLIOP/IIOP_SSL_Transport.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Accept_Strategy.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Acceptor.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_ClientCredentials.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Connection_Handler.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Connector.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Credentials.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_CredentialsAcquirer.cpp, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_CredentialsAcquirer.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_CredentialsAcquirerFactory.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Current.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Current_Impl.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Endpoint.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Invocation_Interceptor.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_ORBInitializer.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_OwnCredentials.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Profile.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_TargetCredentials.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Transport.h, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Util.h, TAO/orbsvcs/orbsvcs/Time/TAO_Time_Service_Clerk.h, TAO/orbsvcs/orbsvcs/Time/TAO_Time_Service_Server.h, TAO/orbsvcs/orbsvcs/Time/Timer_Helper.h, TAO/orbsvcs/orbsvcs/Trader/Constraint_Interpreter.h, TAO/orbsvcs/orbsvcs/Trader/Constraint_Nodes.h, TAO/orbsvcs/orbsvcs/Trader/Interpreter.h, TAO/orbsvcs/orbsvcs/Trader/Trader_Interfaces.h
* TAO/orbsvcs/orbsvcs/SSLIOP/IIOP_SSL_Acceptor.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/IIOP_SSL_Connection_Handler.cpp:
* TAO/orbsvcs/orbsvcs/SSLIOP/IIOP_SSL_Transport.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Accept_Strategy.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Acceptor.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_ClientCredentials.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Connection_Handler.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Connector.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Credentials.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_CredentialsAcquirer.cpp:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_CredentialsAcquirer.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_CredentialsAcquirerFactory.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Current.h:
* TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Current_Impl.h:
* …
=> Minor layout/const/doxygen changes

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/copy-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
* ACE/NEWS:
* ACE/bin/copy-script.sh:
* TAO/NEWS:
=> Make x.5.9 public and prepare for next release

ACE/docs/Download.html
=> Upgrade to CIAO 1.3.9 and DAnCE 1.3.9

.github/workflows/ccpp.yml
=> Try gcc10 on github CI

TAO/TAO_IDL/fe/idl.tab.cpp, TAO/TAO_IDL/fe/idl.tab.hpp
* TAO/TAO_IDL/fe/idl.tab.cpp:
* TAO/TAO_IDL/fe/idl.tab.hpp:
=> Regenerated with bison 3.6.2

TAO/orbsvcs/orbsvcs/Trader/Constraint_Tokens.h, TAO/orbsvcs/orbsvcs/Trader/Constraint_y.cpp
* TAO/orbsvcs/orbsvcs/Trader/Constraint_Tokens.h:
* TAO/orbsvcs/orbsvcs/Trader/Constraint_y.cpp:
=> Regenerated with latest byacc

TAO/tests/IDLv4/TestIDLv4.idl
- Hoist constant `dub` from struct Annotated1.
- At Annotated1 member `k` fix value of annotation parameter `n`.
=> Change TAO/tests/IDLv4/TestIDLv4.idl into valid IDLv4

.github/workflows/linux.yml, .github/workflows/macosx.yml, TAO/tao/Invocation_Retry_State.cpp, TAO/tao/Invocation_Retry_State.h
* TAO/tao/Invocation_Retry_State.cpp:
* TAO/tao/Invocation_Retry_State.h:
=> Simplify matrix

ACE/ace/SSL/SSL_SOCK_Acceptor.cpp, ACE/ace/SSL/SSL_SOCK_Connector.cpp
Reverts DOCGroup/ACE_TAO#1044, change is not clean and needs to be improved
=> Revert "Replacing use of ::select in favor of ::poll"

TAO/tao/CDR.h
=> Fixed parameter not used warning

azure-pipelines.yml
=> azure-pipelines: updated xerces-c vcpkg to use xmlch-wchar

ACE/ace/Priority_Reactor.cpp
* ACE/ace/Priority_Reactor.cpp:
=> Prefix increment, fixed typo

TAO/TAO_IDL/be/be_visitor_operation/ami_handler_reply_stub_operation_cs.cpp, TAO/TAO_IDL/be/be_visitor_operation/exceptlist_ss.cpp, TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp
* TAO/TAO_IDL/be/be_visitor_operation/ami_handler_reply_stub_operation_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_operation/exceptlist_ss.cpp:
* TAO/TAO_IDL/be/be_visitor_operation/operation_ss.cpp:
=> Reduce amount of statics generated, just generate the count directly.

ACE/ace/SSL/SSL_Context.cpp, TAO/orbsvcs/orbsvcs/SSLIOP/SSLIOP_Current_Impl.cpp
[Support for OpenSSL 3.0 #1168](https://github.com/DOCGroup/ACE_TAO/issues/1168)
=> Added version check for deprecated function in OpenSSL 3.0

ACE/ace/SOCK_Dgram_Mcast.h
=> Documentation typo fix and layout change

ACE/tests/Bound_Ptr_Test.cpp, ACE/tests/Bound_Ptr_Test.h, ACE/tests/Intrusive_Auto_Ptr_Test.cpp, ACE/tests/Multicast_Test.cpp, ACE/tests/Multicast_Test_IPV6.cpp, ACE/tests/Object_Manager_Flipping_Test.cpp, ACE/tests/Refcounted_Auto_Ptr_Test.cpp, ACE/tests/Sendfile_Test.cpp, ACE/tests/Thread_Attrs_Test.cpp, ACE/tests/Thread_Creation_Threshold_Test.cpp
* ACE/tests/Bound_Ptr_Test.cpp:
* ACE/tests/Bound_Ptr_Test.h:
* ACE/tests/Intrusive_Auto_Ptr_Test.cpp:
* ACE/tests/Multicast_Test.cpp:
* ACE/tests/Multicast_Test_IPV6.cpp:
* ACE/tests/Object_Manager_Flipping_Test.cpp:
* ACE/tests/Refcounted_Auto_Ptr_Test.cpp:
* ACE/tests/Sendfile_Test.cpp:
* ACE/tests/Thread_Attrs_Test.cpp:
* ACE/tests/Thread_Creation_Threshold_Test.cpp:
=> Removed various variables/members which are not used at all

ACE/ASNMP/README, ACE/ASNMP/asnmp-overview.html, ACE/ASNMP/asnmp/gauge.h, ACE/ASNMP/asnmp/integer.h
* ACE/ASNMP/README:
* ACE/ASNMP/asnmp-overview.html:
* ACE/ASNMP/asnmp/gauge.h:
* ACE/ASNMP/asnmp/integer.h:
=> Layout, docu changes and add some missing explicits

ACE/ace/config-win32-msvc-14.h
* ACE/ace/config-win32-msvc-14.h:
=> Visual Studio has strnlen/wcsnlen

.github/workflows/macosx.yml, ACE/ace/config-macosx-lion.h, ACE/tests/Compiler_Features_32_Test.cpp
=> Do not redefine 64-bit formats for MacOS with C++11

TAO/tao/IIOP_Acceptor.cpp, TAO/tao/ORB_Core.cpp, TAO/tao/RTCORBA/RT_ORB_Loader.cpp, TAO/tao/Strategies/SCIOP_Acceptor.cpp, TAO/tao/default_resource.cpp, TAO/tao/default_server.cpp
* TAO/tao/Strategies/SCIOP_Acceptor.cpp:
=> Use bool for found_a_port and removed some unnecessary casts

.github/workflows/linux.yml, .github/workflows/macosx.yml, .github/workflows/windows.yml
* .github/workflows/macosx.yml:
=> Use environment variables for checkout paths

ACE/ace/Intrusive_Auto_Ptr.h, ACE/ace/Intrusive_Auto_Ptr.inl, ACE/ace/Refcounted_Auto_Ptr.h, ACE/ace/Refcounted_Auto_Ptr.inl
Taken #995 and merge with master and some cleanup
=> Use unspecified_bool_type instead of bool

TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp
* TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:
=> Removed unnecessary semicolon after ACE_UNIMPLEMENTED_FUNC

ACE/ace/Service_Config.h, ACE/ace/Service_Gestalt.h
* ACE/ace/Service_Config.h:
* ACE/ace/Service_Gestalt.h:
=> Layout and docu changes

.github/workflows/linux.yml
=> Add CodeQL configuration as test

ACE/ace/SOCK_Dgram_Mcast.h
=> Doxygen change

TAO/TAO_IDL/be/be_visitor_component/component_exh.cpp, TAO/TAO_IDL/be/be_visitor_component/component_exs.cpp, TAO/TAO_IDL/be/be_visitor_component/component_svh.cpp, TAO/TAO_IDL/be/be_visitor_component/component_svs.cpp, TAO/TAO_IDL/be/be_visitor_component/component_svth.cpp, TAO/TAO_IDL/be/be_visitor_component/component_svts.cpp, TAO/TAO_IDL/be/be_visitor_connector/connector_ami_exh.cpp, TAO/TAO_IDL/be/be_visitor_connector/connector_ami_exs.cpp, TAO/TAO_IDL/be/be_visitor_connector/connector_dds_ex_base.cpp, TAO/TAO_IDL/be/be_visitor_home/home_exh.cpp, TAO/TAO_IDL/be/be_visitor_home/home_exs.cpp, TAO/TAO_IDL/be/be_visitor_home/home_svh.cpp, TAO/TAO_IDL/be/be_visitor_home/home_svs.cpp, TAO/TAO_IDL/be_include/be_global.h
* TAO/TAO_IDL/be/be_visitor_component/component_exh.cpp:
* TAO/TAO_IDL/be/be_visitor_component/component_exs.cpp:
* TAO/TAO_IDL/be/be_visitor_component/component_svh.cpp:
* TAO/TAO_IDL/be/be_visitor_component/component_svs.cpp:
* TAO/TAO_IDL/be/be_visitor_component/component_svth.cpp:
* TAO/TAO_IDL/be/be_visitor_component/component_svts.cpp:
* TAO/TAO_IDL/be/be_visitor_connector/connector_ami_exh.cpp:
* TAO/TAO_IDL/be/be_visitor_connector/connector_ami_exs.cpp:
* TAO/TAO_IDL/be/be_visitor_connector/connector_dds_ex_base.cpp:
* TAO/TAO_IDL/be/be_visitor_home/home_exh.cpp:
* TAO/TAO_IDL/be/be_visitor_home/home_exs.cpp:
* TAO/TAO_IDL/be/be_visitor_home/home_svh.cpp:
* TAO/TAO_IDL/be/be_visitor_home/home_svs.cpp:
* TAO/TAO_IDL/be_include/be_global.h:
=> Removed old cidlc comments

ACE/ace/SPIPE_Addr.cpp, ACE/bin/PerlACE/ConfigList.pm, ACE/bin/PerlACE/MSProject.pm, ACE/bin/PerlACE/Process.pm, ACE/bin/PerlACE/ProcessAndroid.pm, ACE/bin/PerlACE/ProcessLVRT.pm, ACE/bin/PerlACE/ProcessVX.pm, ACE/bin/PerlACE/ProcessVX_Unix.pm, ACE/bin/PerlACE/ProcessVX_Win32.pm, ACE/bin/PerlACE/ProcessWinCE.pm, ACE/bin/PerlACE/ProcessWinCE_Unix.pm, ACE/bin/PerlACE/Process_Unix.pm, ACE/bin/PerlACE/Process_VMS.pm, ACE/bin/PerlACE/Process_Win32.pm, ACE/bin/PerlACE/Run_Test.pm, ACE/bin/PerlACE/TestTarget.pm, ACE/bin/PerlACE/TestTarget_Android.pm, ACE/bin/PerlACE/TestTarget_LVRT.pm, ACE/bin/PerlACE/TestTarget_VxWorks.pm, ACE/bin/PerlACE/TestTarget_WinCE.pm, ACE/bin/Uniqueid.pm, ACE/bin/depgen.pl, ACE/bin/generate_export_file.pl, ACE/bin/mpc.pl, ACE/bin/mwc.pl, ACE/bin/split-cpp.pl, ACE/examples/IPC_SAP/SOCK_SAP/summarize.pl, ACE/examples/IPC_SAP/SSL_SAP/summarize.pl
https://stackoverflow.com/questions/10376206/what-is-the-preferred-bash-shebang
=> Use portable perl shebang

TAO/orbsvcs/examples/Notify/MC/TkMonitor/monitor.pl, TAO/orbsvcs/performance-tests/RTEvent/Colocated_Roundtrip/compare_histo.pl, TAO/orbsvcs/performance-tests/RTEvent/Colocated_Roundtrip/generate_gnuplot.pl, TAO/tests/Bug_2702_Regression/fakeserver2.pl
* TAO/orbsvcs/examples/Notify/MC/TkMonitor/monitor.pl:
* TAO/orbsvcs/performance-tests/RTEvent/Colocated_Roundtrip/compare_histo.pl:
* TAO/orbsvcs/performance-tests/RTEvent/Colocated_Roundtrip/generate_gnuplot.pl:
* TAO/tests/Bug_2702_Regression/fakeserver2.pl:
=> Perl shebang changes

ACE/docs/bczar/bczar.html
=> Add link for conda-forge update

TAO/tests/IDL_Test/IDL_Test.mpc, TAO/tests/IDL_Test/README, TAO/tests/IDL_Test/enum_in_struct.idl, TAO/tests/IDL_Test/keywords.idl, TAO/tests/IDL_Test/typecode.idl
* TAO/tests/IDL_Test/keywords.idl:
=> Add keyword escaping example and use that also for private/public

ACE/NEWS
=> Updated news file for x.5.12

.github/workflows/linux.yml
=> Add clang11

ACE/NEWS
=> Extend news file with changes as part of issue #1271

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make x.5.12 public available

.github/workflows/macosx.yml, ACE/include/makeinclude/platform_macosx.GNU, ACE/include/makeinclude/platform_macosx_bigsur.GNU, ACE/tests/Compiler_Features_32_Test.cpp
* .github/workflows/macosx.yml:
=> Add macos-11.0 github action environment and added GNU platform for MacOSX bigsur

.github/workflows/macosx.yml
* .github/workflows/macosx.yml:
=> Remove C++03 from the github macosx actions

ACE/ace/Object_Manager.cpp
=> MinGW doesn't have _set_abort_behavior

.github/workflows/windows.yml
=> Add mingw64 github action

ACE/debian/changelog, ACE/debian/control, ACE/debian/patches/0001-Revert-Perl-shebang-portability-changes.patch, ACE/debian/patches/series
Sync all files till Debian release of ace_6.5.12+dfsg-3.
=> Sync debian/* files for ACE

TAO/examples/RTScheduling/Fixed_Priority_Scheduler/FP_Scheduler.cpp, TAO/examples/RTScheduling/MIF_Scheduler/MIF_Scheduler.cpp
* TAO/examples/RTScheduling/Fixed_Priority_Scheduler/FP_Scheduler.cpp:
* TAO/examples/RTScheduling/MIF_Scheduler/MIF_Scheduler.cpp:
=> Make server_guid_counter a std::atomic

TAO/examples/Kokyu_dsrt_schedulers/FP_Scheduler.cpp, TAO/examples/Kokyu_dsrt_schedulers/MIF_Scheduler.cpp, TAO/examples/Kokyu_dsrt_schedulers/MUF_Scheduler.cpp
* TAO/examples/Kokyu_dsrt_schedulers/FP_Scheduler.cpp:
* TAO/examples/Kokyu_dsrt_schedulers/MIF_Scheduler.cpp:
* TAO/examples/Kokyu_dsrt_schedulers/MUF_Scheduler.cpp:
=> Add std::move now that we are using unique_ptr

TAO/tests/IDL_Test/union.idl
* TAO/tests/IDL_Test/union.idl:
=> Extend union test IDL with more test cases

TAO/tests/IDL_Test/struct.idl, TAO/tests/IDL_Test/union.idl
* TAO/tests/IDL_Test/struct.idl:
* TAO/tests/IDL_Test/union.idl:
=> Add more array test cases

ACE/ace/OS_main.h, ACE/protocols/tests/HTBP/Reactor_Tests/test_config.h
* ACE/ace/OS_main.h:
* ACE/protocols/tests/HTBP/Reactor_Tests/test_config.h:
=> Remove some left over psos comments

ACE/ace/High_Res_Timer.cpp, ACE/ace/config-macros.h
=> Fixed comment

TAO/tests/Crashed_Callback/Crashed_Callback.cpp, TAO/tests/Faults/test_i.cpp
* TAO/tests/Crashed_Callback/Crashed_Callback.cpp:
* TAO/tests/Faults/test_i.cpp:
=> Removed checks for DEC_CXX

ACE/ACE-INSTALL.html, ACE/NEWS, ACE/ace/Basic_Types.h, ACE/ace/High_Res_Timer.cpp, ACE/ace/OS_NS_time.inl, ACE/ace/README, ACE/ace/config-linux-common.h, ACE/tests/Auto_Event_Test.cpp, ACE/tests/Semaphore_Test.cpp, TAO/tests/Time_Policy/main.cpp
* ACE/ACE-INSTALL.html:
* ACE/NEWS:
* ACE/ace/Basic_Types.h:
* ACE/ace/High_Res_Timer.cpp:
* ACE/ace/OS_NS_time.inl:
* ACE/ace/config-linux-common.h:
* ACE/tests/Auto_Event_Test.cpp:
* ACE/tests/Semaphore_Test.cpp:
* TAO/tests/Time_Policy/main.cpp:
=> Remove support for the Alpha CPU

TAO/orbsvcs/orbsvcs/PortableGroup/PG_Group_List_Store.cpp, TAO/tao/Storable_File_Guard.cpp, TAO/tao/Storable_File_Guard.h
* TAO/orbsvcs/orbsvcs/PortableGroup/PG_Group_List_Store.cpp:
* TAO/tao/Storable_File_Guard.cpp:
* TAO/tao/Storable_File_Guard.h:
=> Use noexcept(false) directly in the code

ACE/ace/Numeric_Limits.h, ACE/ace/README, ACE/ace/config-hpux-11.00.h
* ACE/ace/Numeric_Limits.h:
* ACE/ace/config-hpux-11.00.h:
=> Cleanup numeric limits, depend on the standard, part of issue #1377

ACE/ace/OS_NS_Thread.h
=> [ACE6] Add Missing Export to ACE_OS::thr_gettid

ACE/ace/XML_Utils/XML_Error_Handler.cpp, ACE/ace/XML_Utils/XML_Error_Handler.h, ACE/ace/XML_Utils/XML_Helper.h, ACE/ace/XML_Utils/XML_Helper.tpp, ACE/ace/XML_Utils/XML_Schema_Resolver.cpp, ACE/ace/XML_Utils/XML_Schema_Resolver.h, ACE/ace/XML_Utils/XML_Typedefs.h, ACE/ace/XML_Utils/XSCRT/XML.hpp
* ACE/ace/XML_Utils/XML_Error_Handler.cpp:
* ACE/ace/XML_Utils/XML_Error_Handler.h:
* ACE/ace/XML_Utils/XML_Helper.h:
* ACE/ace/XML_Utils/XML_Helper.tpp:
* ACE/ace/XML_Utils/XML_Schema_Resolver.cpp:
* ACE/ace/XML_Utils/XML_Schema_Resolver.h:
* ACE/ace/XML_Utils/XML_Typedefs.h:
=> Use override, make use of default, removed not used static

ACE/bin/make_release.py
=> Make sure we tag Latest_ACE7TAO3_ as indicated in the news file

ACE/bin/MakeProjectCreator/templates/gnu.mpd
=> Revert "Change generation to allow for 'get_output' command helper customizat…"

ACE/include/makeinclude/platform_g++_common.GNU
* ACE/include/makeinclude/platform_g++_common.GNU:
=> Manually apply fix of #1414 for ace6tao2

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make ACE 7.0.0 and TAO 3.0.0 public available

ACE/docs/Download.html
=> Add link to OpenSuSE build services for major versioned builds

.github/workflows/macosx.yml, ACE/include/makeinclude/platform_macosx_common.GNU
* .github/workflows/macosx.yml:
=> Don't force c++11 through the github action, that should be the default

ACE/ace/README, ACE/docs/ACE-guidelines.html
* ACE/docs/ACE-guidelines.html:
=> Remove macros we don't use anymore

TAO/tao/CORBALOC_Parser.cpp, TAO/tao/CORBALOC_Parser.h, TAO/tao/CORBALOC_Parser.inl, TAO/tao/CORBANAME_Parser.cpp, TAO/tao/CORBANAME_Parser.h, TAO/tao/DLL_Parser.cpp, TAO/tao/DLL_Parser.h, TAO/tao/Default_Stub_Factory.cpp, TAO/tao/Default_Stub_Factory.h, TAO/tao/Dynamic_Adapter.h, TAO/tao/Endpoint.cpp, TAO/tao/Endpoint.h, TAO/tao/Endpoint.inl, TAO/tao/Endpoint_Selector_Factory.h, TAO/tao/Environment.cpp, TAO/tao/Environment.h, TAO/tao/Exception.cpp, TAO/tao/Exception.h, TAO/tao/FILE_Parser.cpp, TAO/tao/FILE_Parser.h, TAO/tao/Fault_Tolerance_Service.h, TAO/tao/Fault_Tolerance_Service.inl, TAO/tao/Flushing_Strategy.h, TAO/tao/HTTP_Parser.cpp, TAO/tao/HTTP_Parser.h, TAO/tao/IOR_Parser.h
* TAO/tao/CORBALOC_Parser.cpp:
* TAO/tao/CORBALOC_Parser.h:
* TAO/tao/CORBALOC_Parser.inl:
* TAO/tao/CORBANAME_Parser.cpp:
* TAO/tao/CORBANAME_Parser.h:
* TAO/tao/DLL_Parser.cpp:
* TAO/tao/DLL_Parser.h:
* TAO/tao/Default_Stub_Factory.cpp:
* TAO/tao/Default_Stub_Factory.h:
* TAO/tao/Dynamic_Adapter.h:
* TAO/tao/Endpoint.cpp:
* TAO/tao/Endpoint.h:
* TAO/tao/Endpoint.inl:
* TAO/tao/Endpoint_Selector_Factory.h:
* TAO/tao/Environment.cpp:
* TAO/tao/Environment.h:
* TAO/tao/Exception.cpp:
* TAO/tao/Exception.h:
* TAO/tao/FILE_Parser.cpp:
* TAO/tao/FILE_Parser.h:
* TAO/tao/Fault_Tolerance_Service.h:
* TAO/tao/Fault_Tolerance_Service.inl:
* TAO/tao/Flushing_Strategy.h:
* TAO/tao/HTTP_Parser.cpp:
* TAO/tao/HTTP_Parser.h:
* TAO/tao/IOR_Parser.h:
=> Modernize using default/delete/override

TAO/tao/CDR.inl, TAO/tao/GIOP_Message_State.h, TAO/tao/GIOP_Message_State.inl, TAO/tao/GIOP_Message_Version.h, TAO/tao/GIOP_Message_Version.inl
* TAO/tao/CDR.inl:
* TAO/tao/GIOP_Message_State.h:
* TAO/tao/GIOP_Message_State.inl:
* TAO/tao/GIOP_Message_Version.h:
* TAO/tao/GIOP_Message_Version.inl:
=> Simplify these files using C++11

TAO/orbsvcs/orbsvcs/FtRtEvent/Utils/UUID.h, TAO/orbsvcs/orbsvcs/FtRtEvent/Utils/UUID.inl
* TAO/orbsvcs/orbsvcs/FtRtEvent/Utils/UUID.h:
* TAO/orbsvcs/orbsvcs/FtRtEvent/Utils/UUID.inl:
=> Fixed typo in enum

ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html
=> Make x.0.1 available for download

TAO/tao/Unbounded_Octet_Sequence_T.h
=> Revert "Add include of OS_NS_string.h, seems it was pulled in implicitly in t…"

ACE/NEWS, TAO/NEWS
=> Prepare for next release

.github/workflows/windows.yml
=> Add zlib to the github action on windows

ACE/docs/ACE-guidelines.html
* ACE/docs/ACE-guidelines.html:
=> Replace psos

ACE/protocols/ace/RMCast/Acknowledge.cpp, ACE/protocols/ace/RMCast/Protocol.h, ACE/tests/Memcpy_Test.cpp
* ACE/protocols/ace/RMCast/Acknowledge.cpp:
* ACE/protocols/ace/RMCast/Protocol.h:
* ACE/tests/Memcpy_Test.cpp:
=> Fixed compile warnings

ACE/apps/gperf/src/Key_List.cpp
* ACE/apps/gperf/src/Key_List.cpp:
=> Generate some fallthroughs to silence gcc warnings

ACE/ace/ETCL/ETCL_l.cpp
=> Added fallthrough comment to fix gcc warning

ACE/ace/Log_Record.h
=> Fixed typo in comment

.github/workflows/linux.yml
=> Add clang12

ACE/include/makeinclude/platform_macosx.GNU
* ACE/include/makeinclude/platform_macosx.GNU:
=> MacOSX 11.1/11.2 are both bigsur releases

ACE/bin/envinfo.cpp
=> Cleanup and simplified this small test source

TAO/tao/RTScheduling/Current.cpp, TAO/tao/RTScheduling/Current.h, TAO/tao/RTScheduling/Distributable_Thread.h, TAO/tao/RTScheduling/RTScheduler.cpp, TAO/tao/RTScheduling/RTScheduler.h, TAO/tao/RTScheduling/RTScheduler_Initializer.h, TAO/tao/RTScheduling/RTScheduler_Loader.h, TAO/tao/RTScheduling/RTScheduler_Manager.cpp, TAO/tao/RTScheduling/RTScheduler_Manager.h, TAO/tao/RTScheduling/Request_Interceptor.cpp, TAO/tao/RTScheduling/Request_Interceptor.h
* TAO/tao/RTScheduling/Request_Interceptor.cpp:
=> Fixed misleading indent warning

ACE/ace/TP_Reactor.h, TAO/TAO_IDL/be/be_visitor_interface/tie_sh.cpp, TAO/TAO_IDL/be/be_visitor_interface/tie_ss.cpp, TAO/tao/Collocated_Invocation.h, TAO/tao/DynamicAny/DynAnyFactory.h, TAO/tao/DynamicInterface/Context.cpp, TAO/tao/DynamicInterface/Context.h, TAO/tao/DynamicInterface/Context.inl, TAO/tao/DynamicInterface/DII_Arguments.h, TAO/tao/DynamicInterface/DII_Arguments.inl, TAO/tao/DynamicInterface/DII_Invocation.h, TAO/tao/DynamicInterface/DII_Invocation_Adapter.h, TAO/tao/DynamicInterface/DII_Reply_Dispatcher.cpp, TAO/tao/DynamicInterface/DII_Reply_Dispatcher.h, TAO/tao/DynamicInterface/DII_Reply_Handler.cpp, TAO/tao/DynamicInterface/DII_Reply_Handler.h, TAO/tao/DynamicInterface/Dynamic_Adapter_Impl.h, TAO/tao/DynamicInterface/ExceptionList.h, TAO/tao/Invocation_Adapter.h, TAO/tao/Messaging/Asynch_Invocation_Adapter.h, TAO/tao/Valuetype/AbstractBase_Invocation_Adapter.h
* ACE/ace/TP_Reactor.h:
* TAO/tao/Collocated_Invocation.h:
* TAO/tao/DynamicInterface/DII_Arguments.h:
* TAO/tao/DynamicInterface/DII_Arguments.inl:
* TAO/tao/DynamicInterface/DII_Invocation.h:
* TAO/tao/DynamicInterface/DII_Invocation_Adapter.h:
* TAO/tao/DynamicInterface/DII_Reply_Handler.cpp:
* TAO/tao/DynamicInterface/DII_Reply_Handler.h:
* TAO/tao/DynamicInterface/Dynamic_Adapter_Impl.h:
* TAO/tao/DynamicInterface/ExceptionList.h:
* TAO/tao/Messaging/Asynch_Invocation_Adapter.h:
* TAO/tao/Valuetype/AbstractBase_Invocation_Adapter.h:
=> Make use of delete to make sure an operation can't be called

TAO/TAO_IDL/be/be_interface.cpp
* TAO/TAO_IDL/be/be_interface.cpp:
=> Add override to the generated lookup operation

TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp
* TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp:
=> Generate execute operation with override

ACE/docs/ACE-bug-process.html
* ACE/docs/ACE-bug-process.html:
=> Small documentation bullet fix

ACE/NEWS, TAO/NEWS
Based on [this list](https://github.com/DOCGroup/ACE_TAO/pulls?q=is%3Apr+base%3Aace6tao2+is%3Aclosed) and the NEWS files in master.
=> 6.5.13 News

ACE/bin/make_release.py
This is the same as #1500, except `default_branch` is "master" instead of "ace6tao2".
=> [ACE7] Branch Option for Release Script

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make ACE 7.0.2 and TAO 3.0.2 public available

ACE/bin/make_release.py
=> Update correct MPC branch, fixed #1511

TAO/tests/IDL_Test/IDL_Test.mpc, TAO/tests/ORB_Local_Config/Two_DLL_ORB/Two_DLL_ORB.mpc
* TAO/tests/IDL_Test/IDL_Test.mpc:
* TAO/tests/ORB_Local_Config/Two_DLL_ORB/Two_DLL_ORB.mpc:
=> Removed some extension for VMS which we don't support anymore

ACE/ace/CDR_Stream.cpp, ACE/ace/OS_NS_Thread.cpp, ACE/tests/Bug_2820_Regression_Test.cpp, ACE/tests/Malloc_Test.cpp
* ACE/ace/CDR_Stream.cpp:
* ACE/tests/Bug_2820_Regression_Test.cpp:
* ACE/tests/Malloc_Test.cpp:
=> Use reset instead of ACE_auto_ptr_reset

TAO/orbsvcs/orbsvcs/AV/UDP.cpp, TAO/orbsvcs/orbsvcs/AV/UDP.h
* TAO/orbsvcs/orbsvcs/AV/UDP.cpp:
* TAO/orbsvcs/orbsvcs/AV/UDP.h:
=> Fixed double deletes during AV shutdown

ACE/ace/Sock_Connect.cpp
Testing on ace6tao2 branch shows this to behave well for static and dynamic windows builds.
=> Fix Concurrency and too-early-request Issues for Windows ip_check

ACE/tests/Process_Env_Test.cpp
* ACE/tests/Process_Env_Test.cpp:
=> Log the status returned by wait

TAO/TAO_IDL/ast/ast_union_branch.cpp, TAO/tests/IDLv4/annotations/annotation_tests.cpp
bringing over the same change applied in pr#1551.
=> applying solution to issue 1550 as found in ace6tao2

ACE/ace/config-kfreebsd.h, ACE/ace/config-win32-borland.h
=> Default to no inlining with the Borland compilers

ACE/ace/post.h, ACE/ace/pre.h
=> Updated bcc32 version check

ACE/ace/post.h, ACE/ace/pre.h
=> [ace6] Updated bcc32 version check

ACE/tests/run_test.lst
=> Run DLL_Test and Process_Test also on Windows

ACE/tests/DLL_Test_Impl.cpp, ACE/tests/DLL_Test_Parent.cpp, ACE/tests/DLL_Test_Parent.h
* ACE/tests/DLL_Test_Impl.cpp:
* ACE/tests/DLL_Test_Parent.cpp:
* ACE/tests/DLL_Test_Parent.h:
=> Extend exception tests

TAO/tao/Objref_VarOut_T.cpp, TAO/tao/Objref_VarOut_T.h, TAO/tao/Objref_VarOut_T.inl, TAO/tao/Seq_Out_T.inl, TAO/tao/Seq_Var_T.cpp, TAO/tao/Seq_Var_T.inl
* TAO/tao/Objref_VarOut_T.cpp:
* TAO/tao/Objref_VarOut_T.h:
* TAO/tao/Objref_VarOut_T.inl:
* TAO/tao/Seq_Out_T.inl:
* TAO/tao/Seq_Var_T.cpp:
* TAO/tao/Seq_Var_T.inl:
=> Use nullptr, removed redundant void, layout changes

ACE/NEWS
=> Add news item

ACE/NEWS
=> Removed item from NEWS file

ACE/tests/DLL_Test_Impl.cpp, ACE/tests/DLL_Test_Parent.cpp, ACE/tests/DLL_Test_Parent.h
* ACE/tests/DLL_Test_Impl.cpp:
* ACE/tests/DLL_Test_Parent.cpp:
* ACE/tests/DLL_Test_Parent.h:
=> Further extend DLL test with exceptions

TAO/tao/operation_details.cpp, TAO/tests/Param_Test/except.cpp
* TAO/tao/operation_details.cpp:
* TAO/tests/Param_Test/except.cpp:
=> Use operator! and const change

ACE/NEWS
=> Add cleanup

ACE/ace/Compression/rle/RLECompressor.cpp, ACE/ace/config-win32-borland.h, ACE/ace/post.h, ACE/ace/pre.h, TAO/orbsvcs/orbsvcs/IFRService/IFR_Service_Utils_T.cpp, TAO/orbsvcs/orbsvcs/Notify/MonitorControlExt/MC_Default_Factory.h, TAO/orbsvcs/orbsvcs/Notify/RT_Factory.h, TAO/orbsvcs/tests/Notify/Bug_3252_Regression/server.cpp, TAO/tests/Bug_3574_Regression/test.cpp, TAO/tests/RTCORBA/README
* TAO/orbsvcs/orbsvcs/IFRService/IFR_Service_Utils_T.cpp:
* TAO/orbsvcs/orbsvcs/Notify/MonitorControlExt/MC_Default_Factory.h:
* TAO/orbsvcs/orbsvcs/Notify/RT_Factory.h:
* TAO/orbsvcs/tests/Notify/Bug_3252_Regression/server.cpp:
* TAO/tests/Bug_3574_Regression/test.cpp:
* TAO/tests/RTCORBA/README:
=> Cleanup Embarcadero C++ Builder support

ACE/ace/Bound_Ptr.h, ACE/ace/Bound_Ptr.inl, ACE/ace/Future.h, ACE/ace/High_Res_Timer.cpp
* ACE/ace/Bound_Ptr.h:
* ACE/ace/Bound_Ptr.inl:
* ACE/ace/Future.h:
* ACE/ace/High_Res_Timer.cpp:
=> Cleanup some workarounds for old Embarcadero compilers

ACE/ace/config-macros.h
=> Removed ACE_RM544 check, not set in any config file

ACE/ace/OS_NS_sys_time.inl, ACE/ace/README
=> Removed some old references to SCO

ACE/tests/Bug_2980_Regression_Test.cpp
* ACE/tests/Bug_2980_Regression_Test.cpp:
=> Make use of std::printf with all compilers

ACE/ACEXML/parser/parser/Parser.cpp, ACE/examples/ConfigViewer/ValueListCtrl.cpp, ACE/tests/CDR_Array_Test.cpp, TAO/TAO_IDL/be/be_interface.cpp, TAO/orbsvcs/tests/Notify/lib/Periodic_Consumer.cpp
* ACE/ACEXML/parser/parser/Parser.cpp:
* ACE/examples/ConfigViewer/ValueListCtrl.cpp:
* ACE/tests/CDR_Array_Test.cpp:
* TAO/TAO_IDL/be/be_interface.cpp:
* TAO/orbsvcs/tests/Notify/lib/Periodic_Consumer.cpp:
=> Removed redundant whitespace

TAO/MPC/config/tao_idl_fe.mpb, TAO/TAO_IDL/driver/drv_preproc.cpp
To fix issue with #1621 on the scoreboards.
=> Escape Double Quotes in tao_idl PP Args on Windows

TAO/tests/Param_Test/any.cpp, TAO/tests/Param_Test/bd_str_seq.cpp, TAO/tests/Param_Test/bd_string.cpp, TAO/tests/Param_Test/client.cpp, TAO/tests/Param_Test/complex_any.cpp, TAO/tests/Param_Test/except.cpp, TAO/tests/Param_Test/nested_struct.cpp, TAO/tests/Param_Test/objref.cpp, TAO/tests/Param_Test/objref_struct.cpp, TAO/tests/Param_Test/param_test_i.cpp, TAO/tests/Param_Test/ub_any_seq.cpp, TAO/tests/Param_Test/ub_objref_seq.cpp, TAO/tests/Param_Test/ub_str_seq.cpp, TAO/tests/Param_Test/ub_string.cpp, TAO/tests/Param_Test/ub_struct_seq.cpp, TAO/tests/Param_Test/var_array.cpp, TAO/tests/Param_Test/var_struct.cpp
* TAO/tests/Param_Test/any.cpp:
* TAO/tests/Param_Test/except.cpp:
* TAO/tests/Param_Test/var_struct.cpp:
=> %C is for logging ascii strings

ACE/ace/Handle_Set.cpp, ACE/ace/Handle_Set.inl
* ACE/ace/Handle_Set.cpp:
* ACE/ace/Handle_Set.inl:
=> Doxygen changes, use nullptr instead of a c-style cast of 0

ACE/ace/Compression/Compressor.cpp, ACE/ace/Compression/Compressor.h, ACE/ace/Compression/Compressor.inl, ACE/ace/Compression/rle/RLECompressor.cpp, ACE/ace/Compression/rle/RLECompressor.h
* ACE/ace/Compression/Compressor.cpp:
* ACE/ace/Compression/Compressor.h:
* ACE/ace/Compression/Compressor.inl:
* ACE/ace/Compression/rle/RLECompressor.h:
=> Layout changes, use default and override

ACE/ace/Compression/rle/RLECompressor.cpp, ACE/ace/post.h, ACE/ace/pre.h, TAO/orbsvcs/orbsvcs/IFRService/IFR_Service_Utils_T.cpp, TAO/orbsvcs/orbsvcs/Notify/MonitorControlExt/MC_Default_Factory.h, TAO/orbsvcs/orbsvcs/Notify/RT_Factory.h, TAO/orbsvcs/tests/Notify/Bug_3252_Regression/server.cpp, TAO/tests/Bug_3574_Regression/test.cpp
=> Updated Embarcadero C++ Compiler checks

ACE/ace/pre.h
=> Removed a lot of warning disabling for the Embarcadero compilers

ACE/ace/Future_Set.h, ACE/ace/Service_Gestalt.h
* ACE/ace/Future_Set.h:
* ACE/ace/Service_Gestalt.h:
=> Minor cleanup

ACE/bin/PerlACE/TestTarget.pm
* ACE/bin/PerlACE/TestTarget.pm:
=> Removed not used variable in DeleteFile

ACE/bin/MakeProjectCreator/config/conv_lib.mpb, TAO/TAO_IDL/tao_idl_be.mpc, TAO/TAO_IDL/tao_idl_fe.mpc, TAO/orbsvcs/FT_ReplicationManager/FT_ReplicationManager.mpc, TAO/orbsvcs/IFR_Service/IFR_Service.mpc, TAO/orbsvcs/ImplRepo_Service/ImplRepo_Service.mpc
Replaced uses of it with install_lib
=> [ace6tao2] Removed conv_lib.mpb

ACE/bin/MakeProjectCreator/config/conv_lib.mpb, TAO/TAO_IDL/tao_idl_be.mpc, TAO/TAO_IDL/tao_idl_fe.mpc, TAO/orbsvcs/FT_ReplicationManager/FT_ReplicationManager.mpc, TAO/orbsvcs/IFR_Service/IFR_Service.mpc, TAO/orbsvcs/ImplRepo_Service/ImplRepo_Service.mpc
Replaced uses of it with install_lib
=> Removed conv_lib.mpb

TAO/orbsvcs/tests/Security/BiDirectional/ssl/make-client-keys, TAO/orbsvcs/tests/Security/Bug_2908_Regression/ssl/make-client-keys, TAO/orbsvcs/tests/Security/MT_BiDir_SSL/ssl/make-client-keys
* TAO/orbsvcs/tests/Security/BiDirectional/ssl/make-client-keys:
* TAO/orbsvcs/tests/Security/Bug_2908_Regression/ssl/make-client-keys:
* TAO/orbsvcs/tests/Security/MT_BiDir_SSL/ssl/make-client-keys:
=> Next round create 2048 bit keys

TAO/tao/Queued_Data.cpp, TAO/tao/Queued_Data.h, TAO/tao/Queued_Data.inl
* TAO/tao/Queued_Data.cpp:
* TAO/tao/Queued_Data.h:
* TAO/tao/Queued_Data.inl:
=> Use uniform initialization and fix g++ unitialized warning

TAO/orbsvcs/orbsvcs/HTIOP/HTIOP_Acceptor.cpp, TAO/tao/Strategies/SCIOP_Acceptor.cpp
* TAO/orbsvcs/orbsvcs/HTIOP/HTIOP_Acceptor.cpp:
* TAO/tao/Strategies/SCIOP_Acceptor.cpp:
=> Use is_loopback to check for a loopback address

TAO/tao/Strategies/COIOP_Connection_Handler.h, TAO/tao/Strategies/COIOP_Connector.cpp, TAO/tao/Strategies/COIOP_Connector.h, TAO/tao/Strategies/COIOP_Endpoint.cpp, TAO/tao/Strategies/COIOP_Endpoint.h, TAO/tao/Strategies/COIOP_Factory.cpp, TAO/tao/Strategies/COIOP_Factory.h, TAO/tao/Strategies/COIOP_Transport.cpp, TAO/tao/Strategies/COIOP_Transport.h, TAO/tao/Strategies/DIOP_Connection_Handler.h, TAO/tao/Strategies/DIOP_Connector.cpp, TAO/tao/Strategies/DIOP_Connector.h, TAO/tao/Strategies/DIOP_Endpoint.cpp, TAO/tao/Strategies/DIOP_Endpoint.h, TAO/tao/Strategies/DIOP_Factory.cpp, TAO/tao/Strategies/DIOP_Factory.h, TAO/tao/Strategies/DIOP_Transport.cpp, TAO/tao/Strategies/DIOP_Transport.h, TAO/tao/Strategies/LF_Strategy_Null.cpp, TAO/tao/Strategies/LF_Strategy_Null.h, TAO/tao/Strategies/LF_Strategy_Null.inl
* TAO/tao/Strategies/LF_Strategy_Null.inl:
Deleted.
* TAO/tao/Strategies/COIOP_Connection_Handler.h:
* TAO/tao/Strategies/COIOP_Connector.cpp:
* TAO/tao/Strategies/COIOP_Connector.h:
* TAO/tao/Strategies/COIOP_Endpoint.cpp:
* TAO/tao/Strategies/COIOP_Endpoint.h:
* TAO/tao/Strategies/COIOP_Factory.cpp:
* TAO/tao/Strategies/COIOP_Factory.h:
* TAO/tao/Strategies/COIOP_Transport.cpp:
* TAO/tao/Strategies/COIOP_Transport.h:
* TAO/tao/Strategies/DIOP_Connection_Handler.h:
* TAO/tao/Strategies/DIOP_Connector.cpp:
* TAO/tao/Strategies/DIOP_Connector.h:
* TAO/tao/Strategies/DIOP_Endpoint.cpp:
* TAO/tao/Strategies/DIOP_Endpoint.h:
* TAO/tao/Strategies/DIOP_Factory.cpp:
* TAO/tao/Strategies/DIOP_Factory.h:
* TAO/tao/Strategies/DIOP_Transport.cpp:
* TAO/tao/Strategies/DIOP_Transport.h:
* …
=> Use default/override

TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp, TAO/TAO_IDL/be/be_visitor_sequence/sequence_cs.cpp
* TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:
* TAO/TAO_IDL/be/be_visitor_sequence/sequence_cs.cpp:
=> Generate default constructor and destructor as default

TAO/TAO_IDL/be/be_visitor_arg_traits.cpp, TAO/TAO_IDL/be/be_visitor_interface/amh_rh_sh.cpp, TAO/TAO_IDL/be/be_visitor_interface/amh_rh_ss.cpp, TAO/TAO_IDL/be/be_visitor_interface/amh_sh.cpp, TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp, TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp, TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp, TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp, TAO/TAO_IDL/be/be_visitor_operation/amh_rh_sh.cpp, TAO/TAO_IDL/be/be_visitor_operation/amh_rh_ss.cpp, TAO/TAO_IDL/be/be_visitor_operation/amh_sh.cpp, TAO/TAO_IDL/be/be_visitor_traits.cpp, TAO/tests/MT_Server/README
* TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:
* TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:
* TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_interface/interface_sh.cpp:
* TAO/TAO_IDL/be/be_visitor_interface/interface_ss.cpp:
* TAO/TAO_IDL/be/be_visitor_traits.cpp:
* TAO/tests/MT_Server/README:
=> Make use of default and more condensed code generation

ACE/NEWS, TAO/NEWS
=> Update for next ACE 6.5.x release

.github/workflows/linux.yml
=> Moved clang5 to ubuntu 18.04

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Make x.0.4 public available

TAO/TAO_IDL/be/be_visitor_union/cdr_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_union_branch/cdr_op_cs.cpp
* TAO/TAO_IDL/be/be_visitor_union/cdr_op_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_union_branch/cdr_op_cs.cpp:
=> Reduce amount of empty lines in union generation

ACE/ace/MEM_Addr.h, ACE/ace/SPIPE_Addr.h, ACE/ace/UNIX_Addr.h
* ACE/ace/MEM_Addr.h:
* ACE/ace/SPIPE_Addr.h:
* ACE/ace/UNIX_Addr.h:
=> Fixed argument unused warnings

.github/workflows/windows.yml
(cherry picked from commit d01e357db24fd2659210747a24bd75534cdfde02)
=> [ace6tao2] GitHub Actions: use a newer vcpkg

.github/workflows/windows.yml, ACE/ace/config-win32-msvc-143.h, ACE/ace/config-win32-msvc.h
* ACE/ace/config-win32-msvc-143.h:
Added.
* ACE/ace/config-win32-msvc.h:
=> Add config file for Visual Studio 2022 and add github CI action

TAO/orbsvcs/Notify_Service/Notify_Service.mpc
Fixes https://github.com/DOCGroup/ACE_TAO/issues/1705
=> Removed redundant base project of project TAO_Notify_Service

ACE/NEWS
=> List changes for 7.0.5

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html, TAO/NEWS
=> Prepare for next release and make x.0.5 public

ACE/include/makeinclude/platform_macosx.GNU, TAO/NEWS
* ACE/include/makeinclude/platform_macosx.GNU:
* TAO/NEWS:
=> Fallback to MacOSX 11 latest when we have a not recognized major version

TAO/tao/Exception.h
=> Modernize example code in deep copy documentation

TAO/tao/BiDir_GIOP/BiDirGIOP.cpp, TAO/tao/BiDir_GIOP/BiDirGIOP.h, TAO/tao/BiDir_GIOP/BiDirPolicy_Validator.h, TAO/tao/BiDir_GIOP/BiDir_ORBInitializer.h, TAO/tao/BiDir_GIOP/BiDir_PolicyFactory.h, TAO/tao/BiDir_GIOP/BiDir_Policy_i.h, TAO/tao/BiDir_GIOP/BiDir_Service_Context_Handler.h
* TAO/tao/BiDir_GIOP/BiDirGIOP.cpp:
* TAO/tao/BiDir_GIOP/BiDirGIOP.h:
* TAO/tao/BiDir_GIOP/BiDirPolicy_Validator.h:
* TAO/tao/BiDir_GIOP/BiDir_ORBInitializer.h:
* TAO/tao/BiDir_GIOP/BiDir_PolicyFactory.h:
* TAO/tao/BiDir_GIOP/BiDir_Policy_i.h:
* TAO/tao/BiDir_GIOP/BiDir_Service_Context_Handler.h:
=> Make use of C++11 features in BiDIR

ACE/bin/MakeProjectCreator/config/acedefaults.mpb, ACE/bin/libsize.pl, TAO/docs/minimumTAO.html, TAO/docs/performance.html
* ACE/bin/MakeProjectCreator/config/acedefaults.mpb:
* ACE/bin/libsize.pl:
* TAO/docs/minimumTAO.html:
* TAO/docs/performance.html:
=> Removed lef over for rcsid

.github/workflows/linux.yml, ACE/ace/ACE_FOR_TAO.pc.in, ACE/ace/Monitor_Control/ACE_Monitor_Control.pc.in, ACE/ace/Monitor_Control/Monitor_Control.mpc, ACE/ace/ace_for_tao.mpc, ACE/bin/ace_install_pkgconfig.pl, TAO/orbsvcs/orbsvcs/TAO_CosProperty_Serv.pc.in, TAO/tao/Monitor/TAO_Monitor.pc.in
Also fixed some ace_for_tao issues
=> make install, pkgconfig, ace_for_tao fixes

TAO/TAO_IDL/ast/ast_expression.cpp
=> [TAO 2]: fixed warning in ast_expression.cpp

ACE/ace/Log_Msg.cpp, ACE/ace/NT_Service.cpp, ACE/ace/Object_Manager.cpp, ACE/ace/Object_Manager.h, ACE/ace/Thread.inl, ACE/tests/Task_Test.cpp, TAO/tao/DynamicInterface/Request.cpp, TAO/tao/GIOP_Message_Base.cpp, TAO/tao/Messaging/AMH_Response_Handler.cpp
* ACE/ace/Log_Msg.cpp:
* ACE/ace/NT_Service.cpp:
* ACE/ace/Object_Manager.cpp:
* ACE/ace/Object_Manager.h:
* ACE/ace/Thread.inl:
* ACE/tests/Task_Test.cpp:
* TAO/tao/DynamicInterface/Request.cpp:
* TAO/tao/GIOP_Message_Base.cpp:
* TAO/tao/Messaging/AMH_Response_Handler.cpp:
=> Use doxygen/nullptr/bool

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, ACE/html/README, TAO/NEWS
* ACE/NEWS:
* ACE/html/README:
* TAO/NEWS:
=> Make x.0.6 public

TAO/TAO_IDL/driver/drv_args.cpp, TAO/TAO_IDL/driver/drv_preproc.cpp
TAO_IDL: Fix Space In Path Handling
(cherry picked from commit e4b72cc9a0fcc5e0f4449eef2598d84df37715b2)
=> [TAO 2] TAO_IDL: Fix Space In Path Handling

TAO/NEWS
It was requested I add the changes from #1772 and #1778 to the TAO news file.
=> Update news file for PRs 1772 and 1778

ACE/ace/OS_NS_Thread.inl
=> Cleanup double check

.github/workflows/windows.yml
=> Upgrade to vcpkg 2022.02.23 release

TAO/TAO_IDL/be/be_visitor_operation/upcall_command_ss.cpp
(cherry picked from commit 0bfdaeb95608f3652cfe499e1960988c71476f30)
=> [TAO 2] tao_idl: avoid undefined behavior (adding to nullptr)

.github/workflows/windows.yml
=> Github deprecated their Visual Studio 2017 runner

ACE/ace/Configuration.cpp, ACE/ace/Configuration.h, ACE/ace/Configuration.inl, ACE/ace/Configuration_Import_Export.cpp, ACE/ace/Configuration_Import_Export.h, ACE/ace/Dirent_Selector.h
* ACE/ace/Configuration.cpp:
* ACE/ace/Configuration.h:
* ACE/ace/Configuration.inl:
* ACE/ace/Configuration_Import_Export.cpp:
* ACE/ace/Configuration_Import_Export.h:
* ACE/ace/Dirent_Selector.h:
=> Make use of delete/default/nullptr

ACE/bin/PerlACE/Process_Unix.pm, ACE/bin/PerlACE/Process_VMS.pm
Reverts PR#1803. Some tests in OpenDDS deliberately send signals to themself to simulate crashes. The current changes caused those tests to be reported incorrectly as failures. And thus, these changes will be reverted in the meantime while new changes will be worked on.
=> Revert "Get signal information from PerlACE"

ACE/bin/PerlACE/Process_Unix.pm, ACE/bin/PerlACE/Process_VMS.pm, TAO/orbsvcs/tests/Bug_2247_Regression/run_test.pl, TAO/orbsvcs/tests/Bug_2248_Regression/run_test.pl, TAO/orbsvcs/tests/Bug_2285_Regression/run_test2.pl, TAO/orbsvcs/tests/ImplRepo/servers_list/run_test.pl, TAO/tests/Bug_1020_Basic_Regression/run_test.pl, TAO/tests/Bug_1020_Regression/run_test.pl, TAO/tests/Bug_1269_Regression/run_test.pl, TAO/tests/Bug_1270_Regression/run_test.pl, TAO/tests/Bug_1361_Regression/run_test.pl, TAO/tests/Bug_1482_Regression/run_test.pl, TAO/tests/Bug_1551_Regression/run_test.pl, TAO/tests/Crash_On_Write/run_test.pl, TAO/tests/Crashed_Callback/run_test.pl, TAO/tests/DII_Deferred_Transient/run_test.pl, TAO/tests/Faults/run_test.pl, TAO/tests/Nested_Upcall_Crash/run_test.pl
Apply the same changes in #1815 to the master branch.
=> Get signal information from PerlACE

ACE/bin/PerlACE/Process_Unix.pm
Apply the same changes from #1833 to the master branch.
=> Handle core patterns that are not file paths

ACE/NEWS, TAO/NEWS
=> Prepare for next 6.5.x release

ACE/ace/NT_Service.h, TAO/tests/MT_Server/test_i.h
* ACE/ace/NT_Service.h:
* TAO/tests/MT_Server/test_i.h:
=> Removed redundant void

.github/workflows/linux.yml
=> Use clang14 on github action CI

.github/workflows/linux.yml, TAO/TAO_IDL/be/be_codegen.cpp, TAO/TAO_IDL/be/be_util.cpp, TAO/TAO_IDL/be/be_valuetype.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/marshal_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ch.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_obv_ch.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_obv_cs.cpp, TAO/TAO_IDL/be_include/be_visitor_valuetype/marshal_cs.h, TAO/TAO_IDL/be_include/be_visitor_valuetype/valuetype_cs.h, TAO/tests/IDL_Test/Versioned_Namespace/TestVersionedNamespace.idl, TAO/tests/IDL_Test/Versioned_Namespace/UserVersionedNamespace.h, TAO/tests/IDL_Test/Versioned_Namespace/Versioned_Namespace.mpc
=> TAO_IDL updates for valuetypes and versioned namespaces

TAO/TAO_IDL/be/be_codegen.cpp, TAO/TAO_IDL/be/be_util.cpp, TAO/TAO_IDL/be/be_valuetype.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/marshal_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_ch.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_obv_ch.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/valuetype_obv_cs.cpp, TAO/TAO_IDL/be_include/be_visitor_valuetype/marshal_cs.h, TAO/TAO_IDL/be_include/be_visitor_valuetype/valuetype_cs.h, TAO/tests/IDL_Test/Versioned_Namespace/TestVersionedNamespace.idl, TAO/tests/IDL_Test/Versioned_Namespace/UserVersionedNamespace.h, TAO/tests/IDL_Test/Versioned_Namespace/Versioned_Namespace.mpc
=> [TAO 2] TAO_IDL updates for valuetypes and versioned namespaces

TAO/TAO_IDL/be/be_visitor_valuetype/marshal_cs.cpp
Fixed issue introduced in #1860
=> Corrected a nullptr that was merged from the TAO 3 branch

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/docs/bczar/bczar.html, ACE/etc/index.html, TAO/NEWS
=> Update for x.0.8

ACE/ace/Name_Proxy.cpp, ACE/ace/Name_Proxy.h
* ACE/ace/Name_Proxy.cpp:
* ACE/ace/Name_Proxy.h:
=> Removed not used reactor_ member, cleanup, and const changes

ACE/ace/OS_NS_Thread.cpp, ACE/ace/OS_NS_Thread.inl
=> Use VxWorks type for return value of sysClkRateGet

ACE/ace/Synch_Options.h
Porting fix from #1879 to master.
=> Fixes for Static Initialization Order Issues Reported By AddressSanitizer

ACE/ace/Select_Reactor_T.cpp
* ACE/ace/Select_Reactor_T.cpp:
=> Log the operation when reporting an error

TAO/bin/tao_orb_tests.lst, TAO/bin/tao_other_tests.lst, TAO/orbsvcs/tests/Security/ssliop_corbaloc/client.cpp, TAO/tao/IIOP_Connection_Handler.cpp, TAO/tao/IIOP_Transport.cpp
* TAO/bin/tao_orb_tests.lst:
* TAO/bin/tao_other_tests.lst:
* TAO/orbsvcs/tests/Security/ssliop_corbaloc/client.cpp:
* TAO/tao/IIOP_Connection_Handler.cpp:
* TAO/tao/IIOP_Transport.cpp:
=> Removed some old Irix related code

.github/workflows/windows.yml, TAO/tests/Bug_1628_Regression/run_test.pl, TAO/tests/Bug_3154_Regression/README, TAO/tests/Bug_3743_Regression/README, TAO/tests/Bug_3845_Regression/README
=> Upgrade to vcpkg v10

ACE/ace/ACE.cpp
=> Changed internal debug_ flag to bool and initialise it to false

ACE/NEWS
=> List changes for next release

ACE/ace/OS_NS_Thread.cpp, ACE/ace/OS_NS_Thread.inl, ACE/ace/OS_NS_sys_socket.inl, ACE/ace/OS_NS_unistd.inl, ACE/ace/SOCK_Dgram_Mcast.cpp, ACE/include/makeinclude/platform_vxworks.GNU, ACE/include/makeinclude/platform_vxworks7.0.GNU
* Does not include VxWorks 22.03 support (#1877 #1876), those can be merged separately if needed
=> [ACE6 TAO2] Merged recent VxWorks changes

TAO/TAO_IDL/include/ast_annotation_appls.h
=> [TAO 2] Use ACE's Sync(h) traits in AST_Annotation_Appls

TAO/TAO_IDL/be/be_visitor_array/any_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_component/executor_exs.cpp, TAO/TAO_IDL/be/be_visitor_component/servant_svs.cpp, TAO/TAO_IDL/be/be_visitor_exception/exception_cs.cpp, TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_interface/smart_proxy_cs.cpp, TAO/TAO_IDL/be/be_visitor_typecode/struct_typecode.cpp, TAO/TAO_IDL/be/be_visitor_union/union_cs.cpp, TAO/TAO_IDL/be/be_visitor_union_branch/public_assign_cs.cpp, TAO/TAO_IDL/be/be_visitor_union_branch/public_reset_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuebox/any_op_cs.cpp, TAO/TAO_IDL/be/be_visitor_valuetype/any_op_cs.cpp
* TAO/TAO_IDL/be/be_visitor_array/any_op_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_component/executor_exs.cpp:
* TAO/TAO_IDL/be/be_visitor_component/servant_svs.cpp:
* TAO/TAO_IDL/be/be_visitor_exception/exception_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_interface/any_op_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_interface/smart_proxy_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_typecode/struct_typecode.cpp:
* TAO/TAO_IDL/be/be_visitor_union/union_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_union_branch/public_assign_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_union_branch/public_reset_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_valuebox/any_op_cs.cpp:
* TAO/TAO_IDL/be/be_visitor_valuetype/any_op_cs.cpp:
=> Use nullptr, check pointers with 1, use std::addressof, reduced sloc

ACE/ace/config-win32-borland.h
=> bcc64 needs different commandline arguments to be used as preprocessor

TAO/TAO_IDL/be/be_visitor_typecode/typecode_defn.cpp, TAO/TAO_IDL/be/be_visitor_typecode/value_typecode.cpp
* TAO/TAO_IDL/be/be_visitor_typecode/typecode_defn.cpp:
* TAO/TAO_IDL/be/be_visitor_typecode/value_typecode.cpp:
=> Revert addressof changes, looks it broke something

ACE/ace/Dirent.h, ACE/ace/Dirent.inl, ACE/ace/Dirent_Selector.cpp, ACE/ace/Dirent_Selector.h, ACE/ace/Malloc_T.cpp, ACE/ace/POSIX_Asynch_IO.cpp
* ACE/ace/Dirent.h:
* ACE/ace/Dirent.inl:
* ACE/ace/Dirent_Selector.cpp:
* ACE/ace/Dirent_Selector.h:
* ACE/ace/Malloc_T.cpp:
* ACE/ace/POSIX_Asynch_IO.cpp:
=> Make use of default, uniform initialisation, and nullptr

TAO/tests/IDL_Test/Versioned_Namespace/TestVersionedNamespace.idl
* TAO/tests/IDL_Test/Versioned_Namespace/TestVersionedNamespace.idl:
=> Extend test IDL

TAO/tao/Wait_On_LF_No_Upcall.cpp, TAO/tao/Wait_On_LF_No_Upcall.h, TAO/tao/Wait_On_Leader_Follower.cpp, TAO/tao/Wait_On_Leader_Follower.h, TAO/tao/Wait_On_Reactor.cpp, TAO/tao/Wait_On_Reactor.h, TAO/tao/Wait_On_Read.cpp, TAO/tao/Wait_On_Read.h, TAO/tao/Wait_Strategy.cpp, TAO/tao/Wait_Strategy.h
* TAO/tao/Wait_On_LF_No_Upcall.cpp:
* TAO/tao/Wait_On_LF_No_Upcall.h:
* TAO/tao/Wait_On_Leader_Follower.cpp:
* TAO/tao/Wait_On_Leader_Follower.h:
* TAO/tao/Wait_On_Reactor.cpp:
* TAO/tao/Wait_On_Reactor.h:
* TAO/tao/Wait_On_Read.cpp:
* TAO/tao/Wait_On_Read.h:
* TAO/tao/Wait_Strategy.cpp:
* TAO/tao/Wait_Strategy.h:
=> Use default destructors and override in TAO wait strategies

.github/workflows/face.yml, .github/workflows/linux.yml
=> Upgrade from 18.04 to 20.04

TAO/TAO_IDL/ast/ast_decl.cpp, TAO/TAO_IDL/include/ast_decl.h, TAO/TAO_IDL/include/utl_string.h
Small contribution to making it easier to write const correct code for users. Maybe just a drop in the ocean, but it is a start.
=> Added const accessors for AST_Decl::local_name () and UTL_String::get_string ()

ACE/ace/Containers_T.h, ACE/ace/Containers_T.inl
* ACE/ace/Containers_T.h:
* ACE/ace/Containers_T.inl:
=> Fixed documentation of ~ACE_DLList and use nullptr

ACE/ace/OS_NS_netdb.inl, TAO/tao/Endpoint.h, TAO/tao/Endpoint.inl, TAO/tao/IIOP_Endpoint.cpp, TAO/tao/IIOP_Endpoint.h
:
* ACE/ace/OS_NS_netdb.inl:
* TAO/tao/Endpoint.h:
* TAO/tao/Endpoint.inl:
* TAO/tao/IIOP_Endpoint.cpp:
* TAO/tao/IIOP_Endpoint.h:
=> Use nullptr/std::addressof/default/uniform initialization

ACE/ace/os_include/os_netdb.h, ACE/ace/os_include/os_unistd.h
* ACE/ace/os_include/os_netdb.h:
* ACE/ace/os_include/os_unistd.h:
=> Moved VxWorks define to os_netdb.h

ACE/ace/SOCK_Dgram_Mcast.cpp
* ACE/ace/SOCK_Dgram_Mcast.cpp:
=> VxWorks 7 has ifaddrs.h

TAO/tao/String_Const_Sequence_Element_T.h, TAO/tao/String_Sequence_Element_T.h, TAO/tao/UserException.cpp, TAO/tao/UserException.h
* TAO/tao/String_Const_Sequence_Element_T.h:
* TAO/tao/String_Sequence_Element_T.h:
* TAO/tao/UserException.cpp:
* TAO/tao/UserException.h:
=> Use default destructors

ACE/ace/os_include/os_netdb.h
* ACE/ace/os_include/os_netdb.h:
=> Updated VxWorks checks

ACE/ace/Message_Block.cpp, ACE/ace/Message_Block.h
* ACE/ace/Message_Block.cpp:
* ACE/ace/Message_Block.h:
=> Fixed potential memory leak on an allocation error, use nullptr

ACE/ace/OS_NS_stropts.cpp, TAO/tao/PortableServer/Active_Policy_Strategies.cpp, TAO/tao/PortableServer/ThreadStrategy.h, TAO/tao/PortableServer/ThreadStrategyFactoryImpl.cpp, TAO/tao/PortableServer/ThreadStrategyFactoryImpl.h, TAO/tao/PortableServer/ThreadStrategyORBControl.h, TAO/tao/PortableServer/ThreadStrategySingle.h, TAO/tao/PortableServer/ThreadStrategySingleFactoryImpl.h, TAO/tests/POA/Single_Threaded_POA/Single_Threaded_POA.cpp
* ACE/ace/OS_NS_stropts.cpp:
* TAO/tao/PortableServer/Active_Policy_Strategies.cpp:
* TAO/tao/PortableServer/ThreadStrategy.h:
* TAO/tao/PortableServer/ThreadStrategyFactoryImpl.cpp:
* TAO/tao/PortableServer/ThreadStrategyFactoryImpl.h:
* TAO/tao/PortableServer/ThreadStrategyORBControl.h:
* TAO/tao/PortableServer/ThreadStrategySingle.h:
* TAO/tao/PortableServer/ThreadStrategySingleFactoryImpl.h:
* TAO/tests/POA/Single_Threaded_POA/Single_Threaded_POA.cpp:
=> Use override

ACE/ace/Process.cpp, ACE/ace/Process.h, TAO/tao/ORB_Core.cpp
* ACE/ace/Process.cpp:
* ACE/ace/Process.h:
* TAO/tao/ORB_Core.cpp:
=> Use const/override/default and some layout changes

ACE/tests/Process_Env_Test.cpp
* ACE/tests/Process_Env_Test.cpp:
=> The environment variable set is Z, not ZZ

ACE/NEWS, TAO/NEWS
=> Update NEWS files for next release

ACE/rpmbuild/etc/logrotate.d/tao-cosconcurrency, ACE/rpmbuild/etc/logrotate.d/tao-cosevent, ACE/rpmbuild/etc/logrotate.d/tao-cosnaming, ACE/rpmbuild/etc/logrotate.d/tao-cosnotification, ACE/rpmbuild/etc/logrotate.d/tao-costrading, ACE/rpmbuild/etc/logrotate.d/tao-rtevent
=> [#1981] Removed invalid 'endscript' drectives from logrotate configuration files

ACE/include/makeinclude/platform_macosx.GNU
Merge pull request #1741 from iedutu/master
```
Support for macOS major version fallback
(cherry picked from commit 61da3abdcfc16295ed34ab552b35dce4f2b78bad)
#	ACE/include/makeinclude/platform_macosx.GNU
#	ACE/include/makeinclude/platform_macosx_monterey.GNU
```
=> [ACE6] macOS major version fallback

ACE/docs/bczar/bczar.html
=> Updated OpenDDS url

ACE/ace/OS_NS_macros.h, ACE/ace/OS_NS_time.h
=> move ACE_Make_QWORD to OS_NS_macros.h

ACE/ace/SSL/SSL_Context.cpp, ACE/ace/Sock_Connect.cpp, TAO/TAO-INSTALL.html
* ACE/ace/SSL/SSL_Context.cpp:
* ACE/ace/Sock_Connect.cpp:
* TAO/TAO-INSTALL.html:
=> Removed some OpenVMS code

ACE/ace/OS_NS_Thread.inl
=> Fixed warning

ACE/ace/config-g++-common.h
Trivial change to align the `endif` on line 34 with the corresponding `if` on line 30.
=> Align one endif with its associated if

ACE/ace/config-win32-msvc-141.h
* ACE/ace/config-win32-msvc-141.h:
=> Set ACE_HAS_CPP20 when C++20 is supported

ACE/ace/config-win32-mingw64.h
* ACE/ace/config-win32-mingw64.h:
=> Ruby 3.1 ships ucrt which has a 3 param wcstok

ACE/ace/os_include/sys/os_mman.h
* ACE/ace/os_include/sys/os_mman.h:
=> Fix redefinition warnings when using mingw64 with ucrt

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html
=> Make ACE 7.1.0 and TAO 3.1.0 public available

ACE/ace/OS_NS_Thread.inl, ACE/ace/OS_NS_unistd.inl, TAO/NEWS
* ACE/ace/OS_NS_Thread.inl:
* ACE/ace/OS_NS_unistd.inl:
=> Add space to resolve compiler warnings on condaforge

ACE/bin/fuzz.pl
=> Mention that nullptr should be used

.github/workflows/windows.yml
=> Upgrade to run-vcpkg@v11

ACE/tests/Message_Queue_Test_Ex.cpp
* ACE/tests/Message_Queue_Test_Ex.cpp:
=> Fixed trailing whitespace

TAO/TAO_IDL/be/be_scope.cpp
* TAO/TAO_IDL/be/be_scope.cpp:
=> Removed redundant c-style cast

.github/workflows/face.yml, .github/workflows/linux.yml, ACE/ace/MMAP_Memory_Pool.cpp, ACE/ace/Malloc_T.cpp, ACE/ace/Malloc_T.h, ACE/ace/Malloc_T.inl, ACE/ace/Mem_Map.cpp, ACE/ace/SV_Shared_Memory.h, ACE/ace/Shared_Memory.h, ACE/ace/Shared_Memory_MM.h, ACE/ace/Shared_Memory_Pool.cpp, ACE/ace/Shared_Memory_Pool.h, ACE/apps/drwho/README, ACE/examples/System_V_IPC/SV_Semaphores/Semaphores_2.cpp, ACE/include/makeinclude/platform_clang_common.GNU, ACE/include/makeinclude/platform_g++_common.GNU, ACE/include/makeinclude/rules.local.GNU, ACE/tests/SV_Shared_Memory_Test.cpp, ACE/tests/run_test.pl
Includes cherry-picked #2077 from ACE 7 and the fixes from #2081 and #2083 
Also merged #2078 for grep -E
=> [ACE 6] Updated Shared_Memory_Pool

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html, TAO/NEWS
=> Make ACE 7.1.1 and TAO 3.1.1 available

TAO/bin/tao_orb_tests.lst
=> Add IDL4 maps test

ACE/ace/OS_NS_sys_stat.h
=> Reorder defines

ACE/ace/config-win32-borland.h
=> Embarcadero C++ Builder changes

ACE/ACE-INSTALL.html
=> Updated documentation for new Embarcadero C++ Builder compiler selection

TAO/tao/Base_Transport_Property.h, TAO/tao/Base_Transport_Property.inl
* TAO/tao/Base_Transport_Property.h:
* TAO/tao/Base_Transport_Property.inl:
=> Use default

TAO/docs/Options.html
See the detailed explanation for this change in #2119.
=> Fix #2119: Improve documentation for TAO_UIPMC_Protocol_Factory and TAO_MIOP_Resource_Factory

ACE/examples/APG/Timers/Timers.cpp
* ACE/examples/APG/Timers/Timers.cpp:
=> Fixed incorrect preprocessor define check

TAO/tao/IORManipulation/IORManip_IIOP_Filter.cpp, TAO/tao/LocateRequest_Invocation.cpp, TAO/tao/Object.cpp, TAO/tao/Synch_Invocation.cpp
* TAO/tao/IORManipulation/IORManip_IIOP_Filter.cpp:
* TAO/tao/LocateRequest_Invocation.cpp:
* TAO/tao/Object.cpp:
* TAO/tao/Synch_Invocation.cpp:
=> Make use of std::nothrow

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html, TAO/NEWS
=> Make x.1.2 publicly available

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html, TAO/NEWS
=> Make 7.1.4 public and prepare for 7.1.5

ACE/include/makeinclude/platform_g++_common.GNU
* ACE/include/makeinclude/platform_g++_common.GNU:
=> Remove check for gcc 4.2, any compiler we support is newer

ACE/ace/Based_Pointer_Repository.h, ACE/ace/UUID.h
* ACE/ace/Based_Pointer_Repository.h:
* ACE/ace/UUID.h:
=> Changes to attempt to silence bcc64x

TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/GroupInfoPublisher.cpp, TAO/orbsvcs/orbsvcs/FtRtEvent/EventChannel/GroupInfoPublisher.h, TAO/orbsvcs/orbsvcs/Trader/Constraint_Nodes.cpp
Fix compile warnings with bcc64x
=> Fix compile warning with bcc64x

ACE/bin/MakeProjectCreator/config/acedefaults.mpb
* ACE/bin/MakeProjectCreator/config/acedefaults.mpb:
=> Simplify handling of platform_libs for bmake

ACE/NEWS, ACE/bin/make_release.py, TAO/NEWS
=> Next release will be ACE8 with TAO4

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html, TAO/NEWS
=> Make ACE 8.0.0 and TAO 4.0.0 public

TAO/tao/AnyTypeCode/Indirected_Type_TypeCode.cpp, TAO/tao/DynamicAny/DynAnyUtils_T.cpp, TAO/tao/DynamicAny/DynAny_i.cpp, TAO/tao/DynamicAny/DynAny_i.h, TAO/tao/DynamicAny/DynArray_i.cpp, TAO/tao/DynamicAny/DynArray_i.h, TAO/tao/DynamicAny/DynCommon.cpp, TAO/tao/DynamicAny/DynEnum_i.cpp, TAO/tao/DynamicAny/DynEnum_i.h, TAO/tao/DynamicAny/DynSequence_i.cpp, TAO/tao/DynamicAny/DynSequence_i.h, TAO/tao/DynamicAny/DynStruct_i.cpp, TAO/tao/DynamicAny/DynStruct_i.h, TAO/tao/DynamicAny/DynUnion_i.cpp, TAO/tao/DynamicAny/DynUnion_i.h, TAO/tao/DynamicAny/DynValueBox_i.cpp, TAO/tao/DynamicAny/DynValueBox_i.h, TAO/tao/DynamicAny/DynValueCommon_i.h, TAO/tao/DynamicAny/DynValue_i.cpp, TAO/tao/DynamicAny/DynValue_i.h, TAO/tao/PI/Interceptor_List_T.h, TAO/tests/DynValue_Test/Analyzer.cpp
* Delete all not needed methods
* Use std::vector
* Use nullptr
* Check return value of cdr streaming
* Check return value of Any extraction
=> Minor modernization of DynamicAny code

TAO/tao/AnyTypeCode/Indirected_Type_TypeCode.cpp, TAO/tao/DynamicAny/DynAnyUtils_T.cpp, TAO/tao/DynamicAny/DynAny_i.cpp, TAO/tao/DynamicAny/DynAny_i.h, TAO/tao/DynamicAny/DynArray_i.cpp, TAO/tao/DynamicAny/DynArray_i.h, TAO/tao/DynamicAny/DynCommon.cpp, TAO/tao/DynamicAny/DynEnum_i.cpp, TAO/tao/DynamicAny/DynEnum_i.h, TAO/tao/DynamicAny/DynSequence_i.cpp, TAO/tao/DynamicAny/DynSequence_i.h, TAO/tao/DynamicAny/DynStruct_i.cpp, TAO/tao/DynamicAny/DynStruct_i.h, TAO/tao/DynamicAny/DynUnion_i.cpp, TAO/tao/DynamicAny/DynUnion_i.h, TAO/tao/DynamicAny/DynValueBox_i.cpp, TAO/tao/DynamicAny/DynValueBox_i.h, TAO/tao/DynamicAny/DynValueCommon_i.h, TAO/tao/DynamicAny/DynValue_i.cpp, TAO/tao/DynamicAny/DynValue_i.h, TAO/tests/DynValue_Test/Analyzer.cpp
Reverts DOCGroup/ACE_TAO#2238, seems to break security tests
=> Revert "Minor modernization of DynamicAny code"

ACE/ACE-INSTALL.html
=> Fix formatting

TAO/tao/Exception_Data.h, TAO/tao/Messaging/ExceptionHolder_i.cpp, TAO/tao/operation_details.cpp
* TAO/tao/Exception_Data.h:
* TAO/tao/Messaging/ExceptionHolder_i.cpp:
* TAO/tao/operation_details.cpp:
=> Use std::string_view as part of Exception_Data

TAO/tao/Object.inl
=> Use nullptr

ACE/tests/Singleton_Restart_Test.cpp
* ACE/tests/Singleton_Restart_Test.cpp:
=> Add wmain for unicode builds on windows

ACE/ace/config-g++-common.h, ACE/ace/config-macros.h
* ACE/ace/config-g++-common.h:
* ACE/ace/config-macros.h:
=> Cleanup ACE_FALLTHROUGH

ACE/include/makeinclude/platform_qnx_gcc.GNU
* ACE/include/makeinclude/platform_qnx_gcc.GNU:
=> Set ACE_PLATFORM_CONFIG on QNX

ACE/NEWS, ACE/bin/copy-local-script.sh, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html, TAO/NEWS
=> Make 8.0.2/4.0.2 public and prepare for next release

TAO/tao/RTCORBA/RT_Stub.h, TAO/tao/RTCORBA/RT_Transport_Descriptor_Property.h, TAO/tao/ZIOP/ZIOP_Stub.h
* TAO/tao/RTCORBA/RT_Stub.h:
* TAO/tao/RTCORBA/RT_Transport_Descriptor_Property.h:
* TAO/tao/ZIOP/ZIOP_Stub.h:
=> Use =delete

ACE/NEWS
=> List dropped platforms

ace/OS_NS_Thread.cpp, ace/OS_NS_Thread.h, ace/OS_NS_Thread.inl, ace/OS_NS_sys_utsname.inl, ace/config-integrity-common.h, ace/config-integritySCA.h
Apply relevant changes for INTEGRITY from master.
=> [ACE 5.4.7] Update support for INTEGRITY

ACE/NEWS, ACE/bin/diff-builds-and-group-fixed-tests-only.sh, ACE/docs/Download.html, ACE/etc/index.html, TAO/NEWS
=> Make ACE 8.0.3 and TAO 4.0.3 available

ACE/examples/Reactor/WFMO_Reactor/Window_Messages.cpp, ACE/examples/Threads/task_four.cpp, ACE/examples/Threads/thread_pool.cpp
* ACE/examples/Reactor/WFMO_Reactor/Window_Messages.cpp:
* ACE/examples/Threads/task_four.cpp:
* ACE/examples/Threads/thread_pool.cpp:
=> Add missing includes

ACE/NEWS, ACE/bin/copy-local-script.sh, TAO/NEWS
=> Prepare for next ace6tao2

ACE/NEWS, ACE/bin/copy-local-script.sh, TAO/NEWS
=> Update for next ACE6TAO2 release
